import AsyncStorage from '@react-native-async-storage/async-storage';
import {useSyncExternalStore} from 'react';
import {loadMessages} from './staticMessages';
export const LANGUAGES=[
 ['ar','العربية','Arabic'],['zh','中文','Chinese'],['kw','Kernewek','Cornish'],['cs','Čeština','Czech'],['nl','Nederlands','Dutch'],['en','English','English'],['fr','Français','French'],['de','Deutsch','German'],['el','Ελληνικά','Greek'],['he','עברית','Hebrew'],['hi','हिन्दी','Hindi'],['it','Italiano','Italian'],['ja','日本語','Japanese'],['kk','Қазақша','Kazakh'],['ko','한국어','Korean'],['pl','Polski','Polish'],['pt','Português','Portuguese'],['ru','Русский','Russian'],['es','Español','Spanish'],['tl','Tagalog','Tagalog'],['vi','Tiếng Việt','Vietnamese'],
] as const;
export type LanguageCode=typeof LANGUAGES[number][0];
const keys=['Bản đồ','Bạn bè','Hành trình','Kỷ niệm','Cá nhân','Cài đặt','Ngôn ngữ','Đăng nhập','Đăng ký','Mật khẩu','Điện thoại','Đóng','Hủy','Lưu','Tìm kiếm','Thêm bạn bè','Tìm địa điểm','Ghi hành trình','Dừng ghi hành trình','Âm nhạc','Quyền riêng tư','Điều khoản sử dụng','Chính sách quyền riêng tư','Giới thiệu MyMap','Xuất dữ liệu','Thiết bị','Thông báo','Vị trí & theo dõi','Dẫn đường','Tránh phà','Tránh cao tốc','Tránh đường thô sơ','Cảnh báo tốc độ','Âm thanh','Rung thiết bị','Tôi an toàn','Mở số khẩn cấp','Nghe','Tìm nhạc','Ngày','Tháng','Hôm nay','Quảng cáo','Quay lại'] as const;
const rows:Record<Exclude<LanguageCode,'vi'>,string>={
 en:'Map|Friends|Journey|Memories|Profile|Settings|Language|Sign in|Sign up|Password|Phone|Close|Cancel|Save|Search|Add friends|Search places|Record journey|Stop recording|Music|Privacy|Terms of use|Privacy policy|About MyMap|Export data|Devices|Notifications|Location & tracking|Navigation|Avoid ferries|Avoid highways|Avoid unpaved roads|Speed warnings|Sound|Vibration|I am safe|Open emergency number|Listen|Find music|Day|Month|Today|Advertisement|Back',
 ar:'الخريطة|الأصدقاء|الرحلة|الذكريات|الملف الشخصي|الإعدادات|اللغة|تسجيل الدخول|إنشاء حساب|كلمة المرور|الهاتف|إغلاق|إلغاء|حفظ|بحث|إضافة أصدقاء|البحث عن أماكن|تسجيل الرحلة|إيقاف التسجيل|الموسيقى|الخصوصية|شروط الاستخدام|سياسة الخصوصية|حول MyMap|تصدير البيانات|الأجهزة|الإشعارات|الموقع والتتبع|الملاحة|تجنب العبّارات|تجنب الطرق السريعة|تجنب الطرق غير المعبدة|تنبيهات السرعة|الصوت|الاهتزاز|أنا بخير|فتح رقم الطوارئ|استماع|البحث عن موسيقى|اليوم|الشهر|اليوم|إعلان|رجوع',
 zh:'地图|朋友|行程|回忆|个人资料|设置|语言|登录|注册|密码|电话|关闭|取消|保存|搜索|添加朋友|搜索地点|记录行程|停止记录|音乐|隐私|使用条款|隐私政策|关于 MyMap|导出数据|设备|通知|位置与跟踪|导航|避开渡轮|避开高速公路|避开未铺设道路|速度警告|声音|振动|我很安全|打开紧急号码|收听|查找音乐|日|月|今天|广告|返回',
 kw:'Mappa|Kowetha|Jorna|Kovyon|Profil|Settyansow|Yeth|Omgelmi|Enskrifa|Ger-tremena|Fôn|Degea|Hedhi|Gwitha|Hwilas|Keworra kowetha|Hwilas tylleryow|Recordya jorna|Astel recordya|Ilow|Privetter|Termynyow devnydh|Polisi privetter|A-dro dhe MyMap|Esportya data|Devisow|Rebyansow|Tyller ha sewya|Lewya|Hep feriow|Hep fordhow bras|Hep fordhow hep pavyans|Gwarnyansow tooth|Son|Krenans|Yth esov yn saw|Ygeri niver argyfwng|Goslowes|Hwilas ilow|Dydh|Mis|Hedhyw|Brassa|Dehweles',
 cs:'Mapa|Přátelé|Cesta|Vzpomínky|Profil|Nastavení|Jazyk|Přihlásit se|Registrovat se|Heslo|Telefon|Zavřít|Zrušit|Uložit|Hledat|Přidat přátele|Hledat místa|Zaznamenat cestu|Zastavit záznam|Hudba|Soukromí|Podmínky použití|Zásady ochrany soukromí|O MyMap|Exportovat data|Zařízení|Oznámení|Poloha a sledování|Navigace|Vyhnout se trajektům|Vyhnout se dálnicím|Vyhnout se nezpevněným cestám|Upozornění na rychlost|Zvuk|Vibrace|Jsem v bezpečí|Otevřít tísňové číslo|Poslechnout|Hledat hudbu|Den|Měsíc|Dnes|Reklama|Zpět',
 nl:'Kaart|Vrienden|Reis|Herinneringen|Profiel|Instellingen|Taal|Inloggen|Registreren|Wachtwoord|Telefoon|Sluiten|Annuleren|Opslaan|Zoeken|Vrienden toevoegen|Plaatsen zoeken|Reis opnemen|Opname stoppen|Muziek|Privacy|Gebruiksvoorwaarden|Privacybeleid|Over MyMap|Gegevens exporteren|Apparaten|Meldingen|Locatie en volgen|Navigatie|Veerboten vermijden|Snelwegen vermijden|Onverharde wegen vermijden|Snelheidswaarschuwingen|Geluid|Trillen|Ik ben veilig|Noodnummer openen|Luisteren|Muziek zoeken|Dag|Maand|Vandaag|Advertentie|Terug',
 fr:'Carte|Amis|Trajet|Souvenirs|Profil|Paramètres|Langue|Connexion|Inscription|Mot de passe|Téléphone|Fermer|Annuler|Enregistrer|Rechercher|Ajouter des amis|Rechercher des lieux|Enregistrer le trajet|Arrêter le suivi|Musique|Confidentialité|Conditions d’utilisation|Politique de confidentialité|À propos de MyMap|Exporter les données|Appareils|Notifications|Position et suivi|Navigation|Éviter les ferries|Éviter les autoroutes|Éviter les routes non goudronnées|Alertes de vitesse|Son|Vibration|Je suis en sécurité|Ouvrir le numéro d’urgence|Écouter|Chercher de la musique|Jour|Mois|Aujourd’hui|Publicité|Retour',
 de:'Karte|Freunde|Reise|Erinnerungen|Profil|Einstellungen|Sprache|Anmelden|Registrieren|Passwort|Telefon|Schließen|Abbrechen|Speichern|Suchen|Freunde hinzufügen|Orte suchen|Reise aufzeichnen|Aufzeichnung stoppen|Musik|Datenschutz|Nutzungsbedingungen|Datenschutzerklärung|Über MyMap|Daten exportieren|Geräte|Benachrichtigungen|Standort und Aufzeichnung|Navigation|Fähren vermeiden|Autobahnen vermeiden|Unbefestigte Straßen vermeiden|Geschwindigkeitswarnungen|Ton|Vibration|Ich bin sicher|Notrufnummer öffnen|Anhören|Musik suchen|Tag|Monat|Heute|Werbung|Zurück',
 el:'Χάρτης|Φίλοι|Διαδρομή|Αναμνήσεις|Προφίλ|Ρυθμίσεις|Γλώσσα|Σύνδεση|Εγγραφή|Κωδικός|Τηλέφωνο|Κλείσιμο|Ακύρωση|Αποθήκευση|Αναζήτηση|Προσθήκη φίλων|Αναζήτηση τοποθεσιών|Καταγραφή διαδρομής|Διακοπή καταγραφής|Μουσική|Απόρρητο|Όροι χρήσης|Πολιτική απορρήτου|Σχετικά με το MyMap|Εξαγωγή δεδομένων|Συσκευές|Ειδοποιήσεις|Τοποθεσία και παρακολούθηση|Πλοήγηση|Αποφυγή πορθμείων|Αποφυγή αυτοκινητοδρόμων|Αποφυγή χωματόδρομων|Προειδοποιήσεις ταχύτητας|Ήχος|Δόνηση|Είμαι ασφαλής|Άνοιγμα αριθμού έκτακτης ανάγκης|Ακρόαση|Αναζήτηση μουσικής|Ημέρα|Μήνας|Σήμερα|Διαφήμιση|Πίσω',
 he:'מפה|חברים|מסלול|זיכרונות|פרופיל|הגדרות|שפה|כניסה|הרשמה|סיסמה|טלפון|סגירה|ביטול|שמירה|חיפוש|הוספת חברים|חיפוש מקומות|הקלטת מסלול|עצירת ההקלטה|מוזיקה|פרטיות|תנאי שימוש|מדיניות פרטיות|אודות MyMap|ייצוא נתונים|מכשירים|התראות|מיקום ומעקב|ניווט|הימנעות ממעבורות|הימנעות מכבישים מהירים|הימנעות מדרכים לא סלולות|התראות מהירות|צליל|רטט|אני בטוח|פתיחת מספר חירום|האזנה|חיפוש מוזיקה|יום|חודש|היום|פרסומת|חזרה',
 hi:'मानचित्र|मित्र|यात्रा|यादें|प्रोफ़ाइल|सेटिंग|भाषा|साइन इन|पंजीकरण|पासवर्ड|फ़ोन|बंद करें|रद्द करें|सहेजें|खोजें|मित्र जोड़ें|स्थान खोजें|यात्रा रिकॉर्ड करें|रिकॉर्डिंग रोकें|संगीत|गोपनीयता|उपयोग की शर्तें|गोपनीयता नीति|MyMap के बारे में|डेटा निर्यात करें|डिवाइस|सूचनाएँ|स्थान और ट्रैकिंग|नेविगेशन|फ़ेरी से बचें|राजमार्ग से बचें|कच्ची सड़कों से बचें|गति चेतावनी|ध्वनि|कंपन|मैं सुरक्षित हूँ|आपातकालीन नंबर खोलें|सुनें|संगीत खोजें|दिन|महीना|आज|विज्ञापन|वापस',
 it:'Mappa|Amici|Viaggio|Ricordi|Profilo|Impostazioni|Lingua|Accedi|Registrati|Password|Telefono|Chiudi|Annulla|Salva|Cerca|Aggiungi amici|Cerca luoghi|Registra viaggio|Interrompi registrazione|Musica|Privacy|Condizioni d’uso|Informativa sulla privacy|Informazioni su MyMap|Esporta dati|Dispositivi|Notifiche|Posizione e tracciamento|Navigazione|Evita traghetti|Evita autostrade|Evita strade sterrate|Avvisi di velocità|Suono|Vibrazione|Sono al sicuro|Apri numero di emergenza|Ascolta|Cerca musica|Giorno|Mese|Oggi|Pubblicità|Indietro',
 ja:'地図|友達|旅程|思い出|プロフィール|設定|言語|ログイン|登録|パスワード|電話|閉じる|キャンセル|保存|検索|友達を追加|場所を検索|旅程を記録|記録を停止|音楽|プライバシー|利用規約|プライバシーポリシー|MyMapについて|データをエクスポート|デバイス|通知|位置情報と記録|ナビゲーション|フェリーを避ける|高速道路を避ける|未舗装道路を避ける|速度警告|音声|振動|無事です|緊急番号を開く|聴く|音楽を検索|日|月|今日|広告|戻る',
 kk:'Карта|Достар|Сапар|Естеліктер|Профиль|Баптаулар|Тіл|Кіру|Тіркелу|Құпиясөз|Телефон|Жабу|Бас тарту|Сақтау|Іздеу|Достар қосу|Орындарды іздеу|Сапарды жазу|Жазуды тоқтату|Музыка|Құпиялық|Пайдалану шарттары|Құпиялық саясаты|MyMap туралы|Деректерді экспорттау|Құрылғылар|Хабарландырулар|Орналасу және бақылау|Навигация|Паромдардан аулақ болу|Автомагистральдардан аулақ болу|Топырақ жолдардан аулақ болу|Жылдамдық ескертулері|Дыбыс|Діріл|Мен қауіпсізбін|Жедел нөмірді ашу|Тыңдау|Музыка іздеу|Күн|Ай|Бүгін|Жарнама|Артқа',
 ko:'지도|친구|여정|추억|프로필|설정|언어|로그인|가입|비밀번호|전화|닫기|취소|저장|검색|친구 추가|장소 검색|여정 기록|기록 중지|음악|개인정보|이용 약관|개인정보 처리방침|MyMap 소개|데이터 내보내기|기기|알림|위치 및 추적|내비게이션|페리 피하기|고속도로 피하기|비포장도로 피하기|속도 경고|소리|진동|안전합니다|긴급 번호 열기|듣기|음악 검색|일|월|오늘|광고|뒤로',
 pl:'Mapa|Znajomi|Podróż|Wspomnienia|Profil|Ustawienia|Język|Zaloguj się|Zarejestruj się|Hasło|Telefon|Zamknij|Anuluj|Zapisz|Szukaj|Dodaj znajomych|Szukaj miejsc|Rejestruj podróż|Zatrzymaj zapis|Muzyka|Prywatność|Warunki korzystania|Polityka prywatności|O MyMap|Eksportuj dane|Urządzenia|Powiadomienia|Lokalizacja i śledzenie|Nawigacja|Unikaj promów|Unikaj autostrad|Unikaj dróg nieutwardzonych|Ostrzeżenia o prędkości|Dźwięk|Wibracje|Jestem bezpieczny|Otwórz numer alarmowy|Słuchaj|Szukaj muzyki|Dzień|Miesiąc|Dzisiaj|Reklama|Wstecz',
 pt:'Mapa|Amigos|Viagem|Memórias|Perfil|Definições|Idioma|Entrar|Registar|Palavra-passe|Telefone|Fechar|Cancelar|Guardar|Pesquisar|Adicionar amigos|Pesquisar locais|Gravar viagem|Parar gravação|Música|Privacidade|Termos de utilização|Política de privacidade|Sobre o MyMap|Exportar dados|Dispositivos|Notificações|Localização e rastreio|Navegação|Evitar ferries|Evitar autoestradas|Evitar estradas não pavimentadas|Alertas de velocidade|Som|Vibração|Estou em segurança|Abrir número de emergência|Ouvir|Pesquisar música|Dia|Mês|Hoje|Publicidade|Voltar',
 ru:'Карта|Друзья|Маршрут|Воспоминания|Профиль|Настройки|Язык|Войти|Регистрация|Пароль|Телефон|Закрыть|Отмена|Сохранить|Поиск|Добавить друзей|Поиск мест|Записать маршрут|Остановить запись|Музыка|Конфиденциальность|Условия использования|Политика конфиденциальности|О MyMap|Экспорт данных|Устройства|Уведомления|Местоположение и отслеживание|Навигация|Избегать паромов|Избегать автомагистралей|Избегать грунтовых дорог|Предупреждения о скорости|Звук|Вибрация|Я в безопасности|Открыть экстренный номер|Слушать|Найти музыку|День|Месяц|Сегодня|Реклама|Назад',
 es:'Mapa|Amigos|Viaje|Recuerdos|Perfil|Ajustes|Idioma|Iniciar sesión|Registrarse|Contraseña|Teléfono|Cerrar|Cancelar|Guardar|Buscar|Añadir amigos|Buscar lugares|Registrar viaje|Detener registro|Música|Privacidad|Condiciones de uso|Política de privacidad|Acerca de MyMap|Exportar datos|Dispositivos|Notificaciones|Ubicación y seguimiento|Navegación|Evitar ferris|Evitar autopistas|Evitar caminos sin pavimentar|Avisos de velocidad|Sonido|Vibración|Estoy a salvo|Abrir número de emergencia|Escuchar|Buscar música|Día|Mes|Hoy|Anuncio|Volver',
 tl:'Mapa|Mga kaibigan|Paglalakbay|Mga alaala|Profile|Mga setting|Wika|Mag-sign in|Magrehistro|Password|Telepono|Isara|Kanselahin|I-save|Maghanap|Magdagdag ng kaibigan|Maghanap ng lugar|I-record ang biyahe|Itigil ang pag-record|Musika|Pagkapribado|Mga tuntunin ng paggamit|Patakaran sa pagkapribado|Tungkol sa MyMap|I-export ang datos|Mga device|Mga abiso|Lokasyon at pagsubaybay|Nabigasyon|Iwasan ang mga ferry|Iwasan ang mga expressway|Iwasan ang mga hindi sementadong daan|Babala sa bilis|Tunog|Panginginig|Ligtas ako|Buksan ang emergency number|Makinig|Maghanap ng musika|Araw|Buwan|Ngayon|Advertisement|Bumalik',
};
export const DICTIONARIES:Record<string,Record<string,string>>=Object.fromEntries(Object.entries(rows).map(([code,row])=>{const values=row.split('|');if(values.length!==keys.length)throw new Error(`Locale ${code} has ${values.length}, expected ${keys.length}`);return [code,Object.fromEntries(keys.map((key,index)=>[key,values[index]!]))];}));

const travelKeys=['An toàn khi di chuyển','Phát hiện va chạm & rơi','Số khẩn cấp trên thiết bị này','Liên kết Spotify','Hủy liên kết','Mở Spotify','Tài khoản MyMap','Tôi đồng ý Điều khoản & Quyền riêng tư','Tìm bài hát hoặc nghệ sĩ','Mức cảnh báo tốc độ','Đang tải…','Đang xử lý…','Xe máy','Ô tô','Mở Bản đồ','Chưa thể hoàn tất'];
const travelRows:Record<string,string>={
en:'Travel safety|Crash and fall detection|Emergency number on this device|Connect Spotify|Disconnect|Open Spotify|MyMap account|I agree to the Terms & Privacy Policy|Find a song or artist|Speed warning threshold|Loading…|Working…|Motorcycle|Car|Open map|Unable to complete',
ar:'السلامة أثناء التنقل|اكتشاف الاصطدام والسقوط|رقم الطوارئ على هذا الجهاز|ربط Spotify|إلغاء الربط|فتح Spotify|حساب MyMap|أوافق على الشروط وسياسة الخصوصية|ابحث عن أغنية أو فنان|حد تنبيه السرعة|جارٍ التحميل…|جارٍ التنفيذ…|دراجة نارية|سيارة|فتح الخريطة|تعذر الإكمال',
zh:'出行安全|碰撞和跌落检测|此设备的紧急号码|连接 Spotify|取消连接|打开 Spotify|MyMap 账户|我同意条款和隐私政策|查找歌曲或艺人|速度提醒阈值|加载中…|处理中…|摩托车|汽车|打开地图|无法完成',
kw:'Sawder an jorna|Dygemmer treusya ha kodha|Niver argyfwng war an devis ma|Junya Spotify|Dijunya|Ygeri Spotify|Akont MyMap|Yth asantav dhe an termynyow ha polisi privetter|Hwilas kan po artyst|Troth gwarnyans tooth|Ow karga…|Owth oberi…|Motorbeyk|Karr|Ygeri an gartenn|Ny yllir gorfenna',
cs:'Bezpečnost na cestách|Detekce nárazu a pádu|Tísňové číslo v tomto zařízení|Propojit Spotify|Odpojit|Otevřít Spotify|Účet MyMap|Souhlasím s podmínkami a ochranou soukromí|Najít skladbu nebo interpreta|Práh upozornění na rychlost|Načítání…|Zpracování…|Motocykl|Auto|Otevřít mapu|Nelze dokončit',
nl:'Veilig onderweg|Botsingen en vallen detecteren|Noodnummer op dit apparaat|Spotify koppelen|Ontkoppelen|Spotify openen|MyMap-account|Ik ga akkoord met de voorwaarden en het privacybeleid|Zoek een nummer of artiest|Drempel voor snelheidswaarschuwing|Laden…|Bezig…|Motorfiets|Auto|Kaart openen|Kan niet voltooien',
fr:'Sécurité en déplacement|Détection des collisions et chutes|Numéro d’urgence sur cet appareil|Connecter Spotify|Déconnecter|Ouvrir Spotify|Compte MyMap|J’accepte les conditions et la politique de confidentialité|Trouver un titre ou un artiste|Seuil d’alerte de vitesse|Chargement…|Traitement…|Moto|Voiture|Ouvrir la carte|Impossible de terminer',
de:'Sicher unterwegs|Unfall- und Sturzerkennung|Notrufnummer auf diesem Gerät|Spotify verbinden|Verbindung trennen|Spotify öffnen|MyMap-Konto|Ich stimme den Bedingungen und dem Datenschutz zu|Titel oder Künstler suchen|Schwelle für Geschwindigkeitswarnung|Wird geladen…|Wird verarbeitet…|Motorrad|Auto|Karte öffnen|Abschluss nicht möglich',
el:'Ασφάλεια στη μετακίνηση|Ανίχνευση σύγκρουσης και πτώσης|Αριθμός έκτακτης ανάγκης σε αυτή τη συσκευή|Σύνδεση Spotify|Αποσύνδεση|Άνοιγμα Spotify|Λογαριασμός MyMap|Συμφωνώ με τους όρους και την πολιτική απορρήτου|Βρείτε τραγούδι ή καλλιτέχνη|Όριο προειδοποίησης ταχύτητας|Φόρτωση…|Επεξεργασία…|Μοτοσικλέτα|Αυτοκίνητο|Άνοιγμα χάρτη|Αδυναμία ολοκλήρωσης',
he:'בטיחות בנסיעה|זיהוי התנגשות ונפילה|מספר חירום במכשיר זה|חיבור Spotify|ניתוק|פתיחת Spotify|חשבון MyMap|אני מסכים לתנאים ולמדיניות הפרטיות|חיפוש שיר או אמן|סף התראת מהירות|בטעינה…|בעיבוד…|אופנוע|רכב|פתיחת מפה|לא ניתן להשלים',
hi:'यात्रा सुरक्षा|टक्कर और गिरने का पता लगाना|इस डिवाइस का आपातकालीन नंबर|Spotify जोड़ें|लिंक हटाएँ|Spotify खोलें|MyMap खाता|मैं शर्तों और गोपनीयता नीति से सहमत हूँ|गीत या कलाकार खोजें|गति चेतावनी सीमा|लोड हो रहा है…|प्रक्रिया जारी है…|मोटरसाइकिल|कार|मानचित्र खोलें|पूरा नहीं हो सका',
it:'Sicurezza in viaggio|Rilevamento di urti e cadute|Numero di emergenza su questo dispositivo|Collega Spotify|Scollega|Apri Spotify|Account MyMap|Accetto le condizioni e la privacy|Trova un brano o un artista|Soglia di avviso velocità|Caricamento…|Elaborazione…|Moto|Auto|Apri mappa|Impossibile completare',
ja:'移動中の安全|衝突と転落の検知|このデバイスの緊急番号|Spotify と連携|連携を解除|Spotify を開く|MyMap アカウント|利用規約とプライバシーポリシーに同意する|曲やアーティストを検索|速度警告のしきい値|読み込み中…|処理中…|バイク|車|地図を開く|完了できません',
kk:'Сапар қауіпсіздігі|Соқтығыс пен құлауды анықтау|Осы құрылғыдағы жедел нөмір|Spotify қосу|Байланысты ажырату|Spotify ашу|MyMap тіркелгісі|Шарттармен және құпиялық саясатымен келісемін|Ән немесе орындаушы іздеу|Жылдамдық ескерту шегі|Жүктелуде…|Өңделуде…|Мотоцикл|Көлік|Картаны ашу|Аяқтау мүмкін болмады',
ko:'이동 중 안전|충돌 및 낙상 감지|이 기기의 긴급 전화번호|Spotify 연결|연결 해제|Spotify 열기|MyMap 계정|약관 및 개인정보 처리방침에 동의합니다|노래 또는 아티스트 찾기|속도 경고 기준|로딩 중…|처리 중…|오토바이|자동차|지도 열기|완료할 수 없습니다',
pl:'Bezpieczeństwo w podróży|Wykrywanie zderzeń i upadków|Numer alarmowy na tym urządzeniu|Połącz Spotify|Odłącz|Otwórz Spotify|Konto MyMap|Akceptuję warunki i politykę prywatności|Znajdź utwór lub artystę|Próg ostrzeżenia o prędkości|Ładowanie…|Przetwarzanie…|Motocykl|Samochód|Otwórz mapę|Nie można ukończyć',
pt:'Segurança em viagem|Deteção de colisões e quedas|Número de emergência neste dispositivo|Ligar Spotify|Desligar|Abrir Spotify|Conta MyMap|Aceito os termos e a política de privacidade|Encontrar música ou artista|Limiar de aviso de velocidade|A carregar…|A processar…|Motociclo|Carro|Abrir mapa|Não foi possível concluir',
ru:'Безопасность в пути|Обнаружение столкновений и падений|Экстренный номер на этом устройстве|Подключить Spotify|Отключить|Открыть Spotify|Аккаунт MyMap|Принимаю условия и политику конфиденциальности|Найти песню или исполнителя|Порог предупреждения о скорости|Загрузка…|Обработка…|Мотоцикл|Автомобиль|Открыть карту|Не удалось завершить',
es:'Seguridad en el viaje|Detección de choques y caídas|Número de emergencia en este dispositivo|Conectar Spotify|Desconectar|Abrir Spotify|Cuenta MyMap|Acepto las condiciones y la política de privacidad|Buscar canción o artista|Umbral de aviso de velocidad|Cargando…|Procesando…|Moto|Coche|Abrir mapa|No se pudo completar',
tl:'Kaligtasan sa biyahe|Pagtukoy ng banggaan at pagkahulog|Emergency number sa device na ito|I-link ang Spotify|Alisin ang link|Buksan ang Spotify|MyMap account|Sumasang-ayon ako sa mga tuntunin at patakaran sa pagkapribado|Maghanap ng kanta o artist|Antas ng babala sa bilis|Naglo-load…|Pinoproseso…|Motorsiklo|Kotse|Buksan ang mapa|Hindi makumpleto',
};
for(const [code,row]of Object.entries(travelRows)){const values=row.split('|');if(values.length!==travelKeys.length)throw new Error('Travel locale mismatch: '+code);Object.assign(DICTIONARIES[code]!,Object.fromEntries(travelKeys.map((key,i)=>[key,values[i]])));}

const aliases:Record<string,string>={'Tạo tài khoản':'Đăng ký','Về MyMap':'Giới thiệu MyMap','Thêm bạn':'Thêm bạn bè','Dừng ghi':'Dừng ghi hành trình','Đăng nhập Firebase':'Đăng nhập','Đăng ký tài khoản Firebase':'Đăng ký','Tạo tài khoản Firebase':'Đăng ký','ĐỊA CHỈ EMAIL':'Email','MẬT KHẨU':'Mật khẩu','Tìm bằng @username':'Tìm kiếm','Bạn bè của tôi':'Bạn bè','Hôm nay của bạn':'Hôm nay','Khẩn cấp SOS':'Mở số khẩn cấp'};
let language:LanguageCode='vi';const listeners=new Set<()=>void>();
const subscribe=(fn:()=>void)=>{listeners.add(fn);return()=>{listeners.delete(fn);};};
export function getLanguage(){return language;}
export function useLanguage(){return useSyncExternalStore(subscribe,getLanguage,getLanguage);}
export async function initializeLanguage(){const saved=await AsyncStorage.getItem('mymap.language.v1');if(LANGUAGES.some(l=>l[0]===saved)){language=saved as LanguageCode;listeners.forEach(fn=>fn());}}
export async function setLanguage(code:LanguageCode){await AsyncStorage.setItem('mymap.language.v1',code);language=code;listeners.forEach(fn=>fn());}
const formats=(require('./templateMessages.json') as string[]).map(pattern=>{
 const parts=pattern.split(/\$\{\d+\}/g);
 const hint=[...parts].sort((a,b)=>b.length-a.length)[0]||'';
 const expression=parts.map(part=>part.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('([\\s\\S]*?)');
 return {pattern,hint,expression:new RegExp('^'+expression+'$'),weight:parts.join('').length};
}).sort((a,b)=>b.weight-a.weight);
export function translate(text:string,code:LanguageCode=language):string {
 if(code==='vi')return text;
 const clean=text.trim();const key=aliases[clean]||clean;
 const catalog=loadMessages(code);const english=loadMessages('en');
 const translated=DICTIONARIES[code]?.[key]||catalog[key]||DICTIONARIES.en?.[key]||english[key];
 if(translated)return text.replace(clean,translated);
 if(clean.length<=4096)for(const format of formats){
  if(!clean.includes(format.hint))continue;
  const match=clean.match(format.expression);if(!match)continue;
  const template=catalog[format.pattern]||english[format.pattern];if(!template)continue;
  const indexes=[...template.matchAll(/\$\s*\{\s*(\d+)\s*\}/g)].map(item=>Number(item[1]));
  if(indexes.length!==match.length-1||new Set(indexes).size!==indexes.length||indexes.some(index=>index>=match.length-1))continue;
  return text.replace(clean,template.replace(/\$\s*\{\s*(\d+)\s*\}/g,(_,index:string)=>match[Number(index)+1]||''));
 }
 return text;
}
