const{test}=require('node:test'),assert=require('node:assert/strict');
const{loadService}=require('./service-loader.cjs');
function setup(){const data=new Map(),uploaded=[],deleted=[];let id='alice',offline=true,failUpdate=false,uploadHook=async()=>{},server={id:'canonical-alice',name:'Alice',bio:'',avatar_path:null};const api=loadService('src/services/localProfile.ts',{'@react-native-async-storage/async-storage':{getItem:async k=>data.get(k)||null,setItem:async(k,v)=>data.set(k,v)},'./auth':{getCurrentUser:async()=>id?{id,is_anonymous:false}:null},'./profileAvatars':{uploadProfileAvatar:async(account,canonical,uri)=>{assert.equal(account.owner,'alice');assert.equal(canonical,'canonical-alice');const path='canonical-alice/'+uploaded.length+'.jpg';uploaded.push({uri,path});await uploadHook();return path;},removeRemoteAvatar:async(account,path)=>{if(path)deleted.push(path);},cacheOwnAvatar:async(account,path)=>'file:///cached-'+path},'./accountApi':{accountApi:async()=>{const pinned=id;return{owner:pinned,assertCurrent:async()=>{if(id!==pinned)throw Error('account changed');},client:{rpc:async(name,args)=>{if(offline)throw Error('offline');if(name==='mm_profile_update'){if(failUpdate)return{error:Error('update failed')};server={...server,name:args.p_name,bio:args.p_bio,avatar_path:args.p_update_avatar?args.p_avatar:server.avatar_path};return{error:null};}return{data:server,error:null};}}};}}});return{api,data,uploaded,deleted,user(value){id=value;},online(){offline=false;},failUpdate(){failUpdate=true;},uploadHook(fn){uploadHook=fn;},server(){return server;}};}
test('profile queues an offline edit and synchronizes the original account when online',async()=>{const s=setup();assert.equal((await s.api.saveLocalProfile({name:'New Alice',bio:'Hello',avatarUri:null},'alice')).synced,false);assert.equal(await s.api.profileNeedsSync(),true);s.online();await s.api.flushLocalProfile();assert.equal(s.server().name,'New Alice');assert.equal(await s.api.profileNeedsSync(),false);});
test('switching accounts does not expose another profile or accept its open editor',async()=>{const s=setup();await s.api.saveLocalProfile({name:'Alice private',bio:'Private bio',avatarUri:'file:///a.jpg'},'alice');s.user('bob');assert.equal((await s.api.getLocalProfile()).name,'');await assert.rejects(s.api.saveLocalProfile({name:'wrong',bio:'',avatarUri:null},'alice'),/Tài khoản/);assert.equal(s.data.has('mymap.local-profile.v2:bob'),false);s.user('alice');assert.equal((await s.api.getLocalProfile()).bio,'Private bio');});
test('legacy unowned profile is not silently assigned to a signed-in account',async()=>{const s=setup();s.data.set('mymap.local-profile.v1',JSON.stringify({name:'Old device profile',bio:'private',avatarUri:null}));assert.equal((await s.api.getLocalProfile()).name,'');s.user(null);assert.equal((await s.api.getLocalProfile()).name,'Old device profile');});
test('avatar queues offline then uploads under canonical identity and does not reupload on a name edit',async()=>{const s=setup();await s.api.saveLocalProfile({name:'Alice',bio:'',avatarUri:'file:///avatar.jpg'},'alice');s.online();assert.equal(await s.api.flushLocalProfile(),true);assert.equal(s.server().avatar_path,s.uploaded[0].path);await s.api.saveLocalProfile({name:'Alice 2',bio:'',avatarUri:'file:///avatar.jpg'},'alice');assert.equal(s.uploaded.length,1);assert.equal(s.server().avatar_path,s.uploaded[0].path);});
test('failed profile mutation removes new orphan and retains the offline pending avatar',async()=>{const s=setup();s.online();s.failUpdate();assert.equal((await s.api.saveLocalProfile({name:'Alice',bio:'',avatarUri:'file:///avatar.jpg'},'alice')).synced,false);assert.deepEqual(s.deleted,[s.uploaded[0].path]);assert.equal(await s.api.profileNeedsSync(),true);assert.equal(JSON.parse(s.data.get('mymap.local-profile.v2:alice')).avatarDirty,true);});
test('switching account during avatar upload cancels the profile mutation and cleans its orphan',async()=>{const s=setup();s.online();s.uploadHook(async()=>s.user('bob'));await assert.rejects(s.api.saveLocalProfile({name:'Alice',bio:'',avatarUri:'file:///avatar.jpg'},'alice'),/Tài khoản/);assert.equal(s.server().avatar_path,null);assert.deepEqual(s.deleted,[s.uploaded[0].path]);assert.equal(s.data.has('mymap.local-profile.v2:bob'),false);});
