const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {loadPure}=require('./helpers.cjs');
function load(file,mocks={},globals={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:name=>{if(!(name in mocks))throw Error('Missing '+name);return mocks[name];},Date,Number,Math,Map,Set,Promise,JSON,Error,AbortController,URLSearchParams,setTimeout,clearTimeout,process:{env:{}},...globals});return module.exports;}
const plain=v=>JSON.parse(JSON.stringify(v));
function explorer(globals={},env={}){return load('src/services/roadExplorer.ts',{'../config/env':{env:{osmOverpassUrl:'https://example.test/overpass',mapillaryToken:'',...env}},'./mapillaryTiles':{nearbyImageIds:async()=>['123']}},globals);}
test('expanded layers default off, ignore unknown fields and malformed preference values',()=>{
 const module=load('src/services/mapFeaturePreferences.ts',{'@react-native-async-storage/async-storage':{getItem:async()=>null}});
 assert.equal(Object.keys(module.DEFAULT_MAP_FEATURES).length,14);assert.equal(module.DEFAULT_MAP_FEATURES.communityReports,false);assert.ok(Object.values(module.DEFAULT_MAP_FEATURES).every(v=>v===false));
 const p=module.normalizeMapFeatures({traffic:true,places:'true',streetImagery:1,unknown:true});assert.equal(p.traffic,true);assert.equal(p.places,false);assert.equal(p.streetImagery,false);assert.equal(p.unknown,undefined);
});
test('serialized preference writes do not lose simultaneous toggle changes; failed writes do not enable a layer',async()=>{
 let raw=null,fail=false;const module=load('src/services/mapFeaturePreferences.ts',{'@react-native-async-storage/async-storage':{getItem:async()=>raw,setItem:async(_,v)=>{if(fail)throw Error('disk');raw=v;}}});let updates=0;module.subscribeMapFeatures(()=>updates++);
 await Promise.all([module.setMapFeature('traffic',true),module.setMapFeature('places',true)]);assert.equal(module.getMapFeatureSnapshot().traffic,true);assert.equal(module.getMapFeatureSnapshot().places,true);assert.equal(JSON.parse(raw).places,true);fail=true;await assert.rejects(module.setMapFeature('fuelPrices',true));assert.equal(module.getMapFeatureSnapshot().fuelPrices,false);assert.equal(updates,3);
});
test('road explorer makes no network requests with every layer off and cancels enabled requests on cleanup',async()=>{
 const effects=[],states=[];let calls=0,signal;const react={useState:initial=>{const slot=states.length;states.push(initial);return[initial,v=>{states[slot]=v;}]},useEffect:fn=>effects.push(fn),createElement:()=>null};const providers={fetchOsmRoadData:async(p,f,s)=>{calls++;signal=s;return{features:[],lines:[]}},fetchStreetImages:async()=>{calls++;return[]},fetchMapillaryFeatures:async()=>{calls++;return[]},imageAnnotation:()=>{}};
 const module=load('src/components/RoadExplorer.tsx',{'react':react,'react-native':{},'../ui/Text':{},'../ui/ActionSheet':{},'../ui/glass':{},'../ui/theme':{},'../config/env':{env:{}},'../services/roadExplorer':providers,'../services/vietFuel':{}});
 module.useRoadExplorer({latitude:21,longitude:105},true,15,{});effects.splice(0).forEach(fn=>fn());await Promise.resolve();assert.equal(calls,0);
 module.useRoadExplorer({latitude:21,longitude:105},true,15,{trafficSigns:true});const cleanup=effects.pop()();assert.equal(calls,1);cleanup();assert.equal(signal.aborted,true);await Promise.resolve();
});
test('OSM annotations preserve actual geometry, explicit dead ends and road metadata without inferring dead ends',()=>{
 const r=explorer().parseOsmRoadData({elements:[{type:'node',id:1,lat:21,lon:105,tags:{traffic_sign:'VN:P.127',maxspeed:'50'}},{type:'node',id:2,lat:21,lon:105.001,tags:{noexit:'yes'}},{type:'way',id:3,center:{lat:21,lon:105},tags:{highway:'service',lanes:'2',surface:'asphalt'},geometry:[{lat:21,lon:105},{lat:21.001,lon:105}]},{type:'node',id:4,lat:99,lon:105,tags:{noexit:'yes'}}]});assert.equal(r.features.length,3);assert.equal(r.features[0].speedKmh,50);assert.equal(r.features.filter(f=>f.kind==='dead_end').length,1);assert.match(r.features[2].details,/Số làn: 2/);assert.equal(r.lines.length,1);
});
test('Mapillary AI detections do not assume speed units or override legal speed limits',()=>{
 const module=explorer();const r=module.parseMapillaryFeatures({data:[{id:'123',geometry:{coordinates:[105,21]},object_type:'trafficsign',object_value:'regulatory--maximum-speed-limit-50--g1',last_seen_at:1700000000000},{id:'124',geometry:{coordinates:[105,99]},object_type:'trafficsign',object_value:'stop'}]});assert.equal(r.length,1);assert.equal(r[0].speedKmh,undefined);assert.match(r[0].displayName,/50.*kiểm tra đơn vị/);assert.match(r[0].details,/Vị trí ước tính/);assert.equal(module.signDescription('VN:P.127','50 mph').speedKmh,undefined);
});
test('Mapillary imagery requires valid point, date and HTTPS thumbnail and history sorts actual capture times',()=>{
 const r=explorer().parseStreetImages({data:[{id:'1',geometry:{coordinates:[105,21]},captured_at:1700000000000,thumb_1024_url:'https://image.example/a',creator:{username:'A'}},{id:'2',computed_geometry:{coordinates:[105,21]},captured_at:1750000000000,thumb_1024_url:'https://image.example/b'},{id:'3',geometry:{coordinates:[105,21]},captured_at:1700000000000,thumb_1024_url:'javascript:bad'}]});assert.equal(r.length,2);assert.equal(r[0].id,'2');assert.equal(r[1].creator,'A');
});
test('Mapillary uses OAuth header without token in URL and summarizes actual detections',async()=>{
 let url,headers;const r=explorer({fetch:async(u,o)=>{url=u;headers=o.headers;return{ok:true,json:async()=>({data:[{value:'object--traffic-light'},{value:'object--traffic-light'},{value:'object--bench'}]})}}},{mapillaryToken:'private-test-token'});assert.deepEqual(plain(await r.fetchImageAnalysis('123')),[{value:'object--traffic-light',count:2},{value:'object--bench',count:1}]);assert.ok(!url.includes('private-test-token'));assert.equal(headers.Authorization,'OAuth private-test-token');await assert.rejects(r.fetchImageAnalysis('../123'));
});
test('aborted or failed provider calls cannot cache data; errors never include credentials',async()=>{
 let calls=0;const controller=new AbortController();controller.abort();const module=explorer({fetch:async()=>{calls++;return{ok:false,status:401}}},{mapillaryToken:'secret-never-log'});await assert.rejects(module.fetchStreetImages({latitude:21,longitude:105},controller.signal));assert.equal(calls,0);await assert.rejects(module.fetchStreetImages({latitude:21,longitude:105}),error=>!error.message.includes('secret-never-log'));await assert.rejects(module.fetchStreetImages({latitude:21,longitude:105}));assert.equal(calls,1);
});
test('upcoming sign distances follow route bends and discard signs behind, off-route, stale fixes or poor accuracy',()=>{
 const {upcomingRoadSigns}=loadPure('src/services/upcomingRoadSigns.ts');const route=[[0,0],[0,.002],[.002,.002]],now=Date.now(),position={latitude:0,longitude:0};const sign=(lat,lon)=>({kind:'traffic_sign',latitude:lat,longitude:lon});const r=upcomingRoadSigns(route,position,[sign(.002,.002),sign(.001,.001)],5,now,now);assert.equal(r.length,1);assert.ok(r[0].meters>=440&&r[0].meters<=450);assert.equal(upcomingRoadSigns(route,position,[sign(.002,.002)],31,now,now).length,0);assert.equal(upcomingRoadSigns(route,position,[sign(.002,.002)],5,now-16000,now).length,0);assert.equal(upcomingRoadSigns(route,{latitude:.0019,longitude:.002},[sign(0,.002)],5,now,now).length,0);
});
test('looping routes suppress ambiguous sign projections and wrong parallel-road marks',()=>{
 const {upcomingRoadSigns}=loadPure('src/services/upcomingRoadSigns.ts'),now=Date.now();const r=upcomingRoadSigns([[0,0],[0,.004],[.004,.004],[.004,0],[0,0]],{latitude:0,longitude:0},[{kind:'traffic_sign',latitude:0,longitude:.002}],5,now,now);assert.equal(r.length,0);
});
test('VietFuel keeps regional prices, provenance and price date, including AdBlue only when returned',()=>{
 const module=load('src/services/vietFuel.ts',{'../config/env':{env:{}},'./roadExplorer':{}}),now=Date.parse('2026-10-08T12:00:00Z');const r=module.parseVietFuel({success:true,meta:{primarySource:'Petrolimex',priceDate:'2026-10-07'},data:[{name:'RON95',region1:25000,region2:25500,unit:'VND/lít'},{name:'AdBlue',region1:18000,unit:'VND/lít'},{name:'bad',region1:-100}]},now);assert.equal(r.rows.length,2);assert.equal(r.rows[1].name,'AdBlue');assert.equal(r.stale,false);assert.equal(r.source,'Petrolimex');assert.equal(module.stationFuelSource('Petrolimex CHXD 12'),'petrolimex');assert.equal(module.stationFuelSource('Cây xăng Hòa Bình'),null);assert.equal(module.parseVietFuel({success:true,meta:{priceDate:'2026-02-30'},data:[{name:'RON95',region1:25000}]},now).stale,true);assert.throws(()=>module.parseVietFuel({success:true,data:[{name:'invalid',region1:'25000'}]}));
});
test('VietFuel selects matching brand without claiming station-specific prices and permits custom HTTPS base',async()=>{
 const urls=[];const module=load('src/services/vietFuel.ts',{'../config/env':{env:{vietFuelUrl:'https://fuel.example/'}},'./roadExplorer':{explorerRequest:async u=>{urls.push(u);return{success:true,meta:{priceDate:'2026-10-07'},data:[{name:'RON95',region1:25000}]}}}});await module.fetchVietFuel('PVOIL Trạm 2');await module.fetchVietFuel('Cây xăng không rõ hãng');assert.deepEqual(urls,['https://fuel.example/api/fuel-prices/pvoil','https://fuel.example/api/fuel-prices']);
});
test('Mapillary image fallback uses actual nearby feature associations and filters distant photos',async()=>{
 const token='private-test',requests=[];const module=load('src/services/roadExplorer.ts',{'../config/env':{env:{mapillaryToken:token}},'./mapillaryTiles':{nearbyImageIds:async()=>{throw Error('tiles blocked')}}},{fetch:async(url,options)=>{requests.push(url);assert.equal(options.headers.Authorization,'OAuth '+token);const data=url.includes('/map_features?')?{data:[{id:'200',object_type:'point',object_value:'object--bench',geometry:{coordinates:[105,21]}}]}:url.includes('/200?')?{images:{data:[{id:'300',geometry:{coordinates:[105,21]}},{id:'301',geometry:{coordinates:[106,22]}}]}}:{id:'300',geometry:{coordinates:[105,21]},captured_at:1700000000000,thumb_1024_url:'https://img.example/photo',creator:{username:'real-author'}};return{ok:true,json:async()=>data};}});
 const images=await module.fetchStreetImages({latitude:21,longitude:105});assert.equal(images.length,1);assert.equal(images[0].id,'300');assert.equal(requests.length,3);assert.ok(requests.every(url=>!url.includes(token)));
 const history=await module.fetchStreetImages(images[0],undefined,true,images[0]);assert.equal(history[0].id,'300');
});
test('Mapillary vector coverage decodes georeferenced points and timestamp without turning sequences into image markers',()=>{
 const {PbfWriter}=require('pbf'),writer=new PbfWriter();
 const writeValue=(value,p)=>typeof value==='string'?p.writeStringField(1,value):p.writeDoubleField(3,value);
 writer.writeMessage(3,(_,p)=>{p.writeStringField(1,'image');p.writeMessage(2,(_,f)=>{f.writePackedVarint(2,[0,0,1,1]);f.writeVarintField(3,1);f.writePackedVarint(4,[9,4096,4096]);},null);p.writeStringField(3,'id');p.writeStringField(3,'captured_at');p.writeMessage(4,writeValue,'123456789');p.writeMessage(4,writeValue,1700000000000);p.writeVarintField(5,4096);p.writeVarintField(15,2);},null);
 const module=load('src/services/mapillaryTiles.ts',{'pbf':require('pbf'),'@mapbox/vector-tile':require('@mapbox/vector-tile'),'../config/env':{env:{}}});const images=module.decodeCoverage(writer.finish(),{x:0,y:0,z:0});assert.equal(images.length,1);assert.equal(images[0].id,'123456789');assert.equal(images[0].capturedAt,1700000000000);assert.ok(Math.abs(images[0].latitude)<.001);assert.ok(Math.abs(images[0].longitude)<.001);assert.equal(module.coverageTiles(99,105,1000).length,0);assert.equal(module.coverageTiles(21,105,Infinity).length,0);
});
test('web MapLibre retains infrastructure through updates and does not reload traffic tiles with every GPS fix',()=>{
 const react={createElement:(type,props,...children)=>({type,props,children}),forwardRef:fn=>fn,useRef:value=>({current:value}),useMemo:fn=>fn(),useEffect:()=>{},useCallback:fn=>fn,useImperativeHandle:()=>{}};
 const module=load('src/components/WebMapEngine.tsx',{'react':react,'react-native':{View:'View',ActivityIndicator:'ActivityIndicator',StyleSheet:{create:s=>s,absoluteFill:{}}},'react-native-webview':{WebView:'WebView'},'../config/env':{env:{osmTileUrl:'https://example.test/{z}/{x}/{y}',mapLibreDemUrl:''}},'../config/mapProviders':{is3DMapProvider:()=>false,openMapStyleUrl:()=>null},'../services/traveledTrace':{rawTraveledSegments:()=>[]}});
 const tree=module.WebMapEngine({engine:'maplibre_gl',currentPosition:{latitude:21,longitude:105},roadLines:[[[21,105],[21.001,105]]],trafficTileUrl:'https://traffic.test/{z}/{x}/{y}'},null),script=tree.children[0].props.source.html.match(/<script>([\s\S]*?)<\/script>/)[1];
 const sources=new Map(),layers=new Map();let trafficRequests=0;const map={addSource:(id,data)=>{assert.ok(!sources.has(id),'duplicate source '+id);sources.set(id,data);if(id==='traffic-flow')trafficRequests++;},addLayer:data=>{assert.ok(!layers.has(data.id),'duplicate layer '+data.id);layers.set(data.id,data);},getSource:id=>sources.get(id),getLayer:id=>layers.get(id),removeSource:id=>sources.delete(id),removeLayer:id=>layers.delete(id),isStyleLoaded:()=>true,addControl:()=>{},on:(event,fn)=>{if(event==='load')fn();}};
 const window={},element={style:{},addEventListener:()=>{},remove:()=>{}};
 vm.runInNewContext(script,{window,document:{getElementById:()=>element},maplibregl:{Map:function(){return map;},AttributionControl:function(){},ScaleControl:function(){this.getContainer=()=>element;}},JSON,Math});
 assert.ok(sources.has('road-0'));window.myMapBridge.update({current:[105.0001,21]});assert.ok(sources.has('road-0'));assert.equal(trafficRequests,1);window.myMapBridge.update({roadLines:[],trafficTileUrl:''});assert.ok(!sources.has('road-0'));assert.ok(!sources.has('traffic-flow'));
});
test('dense infrastructure cannot hide enabled imagery and signs; closest markers lead each category',()=>{
 const api=explorer(),point={latitude:21,longitude:105},features=Array.from({length:100},(_,i)=>({kind:'infrastructure',latitude:21+i/10000,longitude:105,placeId:i}));features.push({kind:'street_image',latitude:21,longitude:105,placeId:200},{kind:'traffic_sign',latitude:21,longitude:105,placeId:201});const markers=api.prioritizeRoadMarkers(features,point);assert.equal(markers.length,20);assert.ok(markers.some(m=>m.kind==='street_image'));assert.ok(markers.some(m=>m.kind==='traffic_sign'));assert.equal(markers.find(m=>m.kind==='infrastructure').placeId,0);
});
