const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {loadPure}=require('./helpers.cjs');
function load(file,mocks={},globals={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:name=>{if(!(name in mocks))throw Error('Missing '+name);return mocks[name];},Date,Number,Math,Map,Set,Promise,JSON,Error,AbortController,URLSearchParams,setTimeout,clearTimeout,process:{env:{}},...globals});return module.exports;}
const prefs={avoidFerries:true,avoidHighways:true,avoidUnpaved:true};
const route=(offset=0)=>({summary:{lengthInMeters:1200,travelTimeInSeconds:300,trafficDelayInSeconds:60},legs:[{points:[{latitude:21+offset,longitude:105},{latitude:21.001+offset,longitude:105},{latitude:21.002+offset,longitude:105}]}],guidance:{instructions:[{maneuver:'DEPART',routeOffsetInMeters:0,point:{latitude:21+offset,longitude:105}},{maneuver:'TURN_LEFT',street:'Đường A',routeOffsetInMeters:500,point:{latitude:21.001+offset,longitude:105}}]},sections:[{sectionType:'TRAFFIC',simpleCategory:'JAM',startPointIndex:1,endPointIndex:2},{sectionType:'TRAFFIC',simpleCategory:'ROAD_WORK',startPointIndex:0,endPointIndex:1},{sectionType:'TOLL_ROAD',startPointIndex:0,endPointIndex:2}]});
function routing(globals={},storage={getItem:async()=>null,setItem:async()=>{}}){return load('src/services/roadRouting.ts',{'@react-native-async-storage/async-storage':storage,'./navigationPreferences':{getNavigationPreferences:async()=>prefs},'./traveledTrace':loadPure('src/services/traveledTrace.ts')},globals);}
test('TomTom preserves distinct alternatives and paints only actual jam/closure geometry',()=>{const r=routing().parseTomTomRoutes({routes:[route(),route(.01),route()]},123);assert.equal(r.alternatives.length,1);assert.equal(r.trafficSegments.length,1);assert.deepEqual(Array.from(r.trafficSegments[0],p=>Array.from(p)),[[21.001,105],[21.002,105]]);assert.equal(r.trafficDelaySeconds,60);assert.equal(r.hasTolls,true);assert.equal(r.trafficUpdatedAt,123);assert.equal(r.steps[1].instruction,'Rẽ trái · Đường A');});
test('invalid section indexes never color unrelated geometry; invalid coordinates reject route',()=>{const a=route();a.sections=[{sectionType:'TRAFFIC',simpleCategory:'JAM',startPointIndex:-1,endPointIndex:2},{sectionType:'TRAFFIC',simpleCategory:'JAM',startPointIndex:0,endPointIndex:9}];assert.equal(routing().parseTomTomRoutes({routes:[a]}).trafficSegments.length,0);a.legs[0].points[0].latitude=999;assert.throws(()=>routing().parseTomTomRoutes({routes:[a]}),/Invalid route/);});
test('TomTom requests motorcycle alternatives with avoidance, caches briefly and refreshes explicitly',async()=>{const urls=[],writes=[];const r=routing({process:{env:{EXPO_PUBLIC_TOMTOM_TRAFFIC_KEY:'test-key'}},fetch:async url=>{urls.push(new URL(url));return {ok:true,json:async()=>({routes:[route(),route(.01)]})};}},{getItem:async()=>{throw Error('Must not reuse persistent traffic');},setItem:async key=>writes.push(key)});const a={latitude:21,longitude:105},b={latitude:21.002,longitude:105};await r.fetchRoadRoute(a,b,'motorbike',prefs);await r.fetchRoadRoute(a,b,'motorbike',prefs);assert.equal(urls.length,1);const p=urls[0].searchParams;assert.equal(p.get('travelMode'),'motorcycle');assert.equal(p.get('maxAlternatives'),'2');assert.deepEqual(p.getAll('avoid'),['ferries','motorways','unpavedRoads']);assert.deepEqual(p.getAll('sectionType'),['traffic','tollRoad']);assert.equal(writes.length,0);await r.fetchRoadRoute(a,b,'motorbike',prefs,{refresh:true});assert.equal(urls.length,2);});
test('lane bitmasks preserve lane positions and recommended directions in guidance',()=>{const r=routing(),lanes=r.valhallaLanes([{directions:8,active:1},{directions:2,valid:0},{directions:0}]);assert.equal(lanes.length,3);assert.equal(lanes[0].indications[0],'left');assert.equal(lanes[0].valid,true);assert.equal(lanes[2].indications.length,0);const guidance=r.getRouteGuidance([{type:'depart',position:[21,105],distanceMeters:100,instruction:'Đi'},{type:'turn',position:[21.001,105],distanceMeters:50,instruction:'Rẽ',lanes}],{latitude:21,longitude:105});assert.equal(guidance.lanes.length,3);});
test('turning traffic off removes live traffic request parameters and uses a distinct routing cache',async()=>{const urls=[];const r=routing({process:{env:{EXPO_PUBLIC_TOMTOM_TRAFFIC_KEY:'test-key'}},fetch:async url=>{urls.push(new URL(url));return{ok:true,json:async()=>({routes:[route()]})};}});const a={latitude:21,longitude:105},b={latitude:21.002,longitude:105};await r.fetchRoadRoute(a,b,'car',prefs,{traffic:false});await r.fetchRoadRoute(a,b,'car',prefs,{traffic:false});assert.equal(urls.length,1);assert.equal(urls[0].searchParams.get('traffic'),'false');assert.deepEqual(urls[0].searchParams.getAll('sectionType'),['tollRoad']);await r.fetchRoadRoute(a,b,'car',prefs,{traffic:true});assert.equal(urls.length,2);assert.equal(urls[1].searchParams.get('traffic'),'true');});
test('navigation switches at 30 km/h and keeps a fixed span over 500 m in all directions',()=>{const {navigationCamera}=loadPure('src/utils/navigationCamera.ts');const point={latitude:21,longitude:105},slow=navigationCamera(point,29,390,420),fast=navigationCamera(point,30,390,420),faster=navigationCamera(point,100,390,420);assert.ok(slow.zoom>fast.zoom);assert.equal(fast.zoom,faster.zoom);assert.equal(fast.latitude,point.latitude);assert.ok(fast.latitudeDelta*111320/2>=500);assert.equal(fast.pitch,0);assert.equal(navigationCamera(point,30,390,420,256).zoom,fast.zoom+1);});
test('search history serializes simultaneous writes, deduplicates a selected place and clears',async()=>{const data=new Map(),h=load('src/services/placeSearchHistory.ts',{'@react-native-async-storage/async-storage':{getItem:async k=>data.get(k)||null,setItem:async(k,v)=>data.set(k,v),removeItem:async k=>data.delete(k)}});const p=h.familiarSearchPlace('Nhà',21,105);await Promise.all([h.rememberPlaceSearch('A',p),h.rememberPlaceSearch('B',p),h.rememberPlaceSearch('C')]);const saved=await h.readPlaceSearchHistory();assert.deepEqual(Array.from(saved,x=>x.query),['C','B']);await h.clearPlaceSearchHistory();assert.equal((await h.readPlaceSearchHistory()).length,0);data.set('mymap.place_search_history.v1','broken');assert.equal((await h.readPlaceSearchHistory()).length,0);});
test('TomTom places keep provider identity, real coordinates and reject malformed results',async()=>{let calls=0;const p=load('src/services/tomTomPlaces.ts',{'../config/env':{env:{tomTomTrafficKey:'test'}}},{fetch:async()=>{calls++;return {ok:true,json:async()=>({results:[{id:'real-poi',position:{lat:21,lon:105},poi:{name:'Trạm sạc',classifications:[{code:'ELECTRIC_VEHICLE_STATION'}]},address:{freeformAddress:'Đường A'}}]})};}});const places=await p.nearbyTomTomPlaces(21,105,'charging_station');await p.nearbyTomTomPlaces(21,105,'charging_station');assert.equal(calls,1);assert.equal(places[0].provider,'tomtom');assert.equal(places[0].providerId,'real-poi');assert.equal(places[0].osmId,0);assert.equal(p.parseTomTomPlaces({results:[{position:{lat:999,lon:105},poi:{name:'Sai'}}]}).length,0);});
const react={forwardRef:fn=>fn,useMemo:fn=>fn(),useEffect:()=>{},useRef:current=>({current}),useCallback:fn=>fn,useImperativeHandle:()=>{},createElement:(type,props,...children)=>({type,props,children})};
test('Leaflet document supports the new layers and bridge without invalid inline JavaScript',()=>{
 const leaflet=load('src/components/LeafletMap.tsx',{'react':react,'react-native':{View:'View',ActivityIndicator:'ActivityIndicator',StyleSheet:{create:s=>s}},'react-native-webview':{WebView:'WebView'},'../config/env':{env:{stadiaMapsKey:''}},'../services/traveledTrace':loadPure('src/services/traveledTrace.ts'),'./leafletBundle':{LEAFLET_JS:'',LEAFLET_CSS:''}});
 const html=leaflet.LeafletMap({currentPosition:{latitude:21,longitude:105}},null).children[0].props.source.html;
 for(const match of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new vm.Script(match[1]));
 assert.match(html,/ROUTE_CHOICE/);assert.match(html,/POI_CHOICE/);assert.match(html,/VIEWPORT/);assert.doesNotMatch(html,/\[\[origin.latitude, origin.longitude\], \[dLat, dLng\]\]/);
});
test('native POI markers have distinct identities even though TomTom has no OSM IDs',()=>{
 const native=load('src/components/MapLibreNativeMap.tsx',{'react':react,'react-native':{Image:'Image',View:'View',StyleSheet:{create:s=>s,absoluteFill:{}}},'../ui/Text':{Text:'Text'},'@maplibre/maplibre-react-native':{Camera:'Camera',GeoJSONSource:'GeoJSONSource',Layer:'Layer',Map:'Map',Marker:'Marker'},'../config/env':{env:{osmTileUrl:'https://example.org/{z}/{x}/{y}',mapLibreDemUrl:''}},'../config/mapProviders':{DEFAULT_MAP_PROVIDER:'osm',is3DMapProvider:()=>false,openMapStyleUrl:()=>null},'../services/traveledTrace':loadPure('src/services/traveledTrace.ts')});
 const places=[-1,-2].map(placeId=>({provider:'tomtom',placeId,osmType:'node',osmId:0,kind:'fuel',latitude:21,longitude:105,displayName:'Cây xăng'}));const tree=native.MapLibreNativeMap({places},null),markers=[];
 const walk=node=>{if(Array.isArray(node))return node.forEach(walk);if(!node||typeof node!=='object')return;if(node.type==='Marker'&&String(node.props.id).startsWith('poi-'))markers.push(node.props.id);node.children?.forEach(walk);};walk(tree);assert.equal(markers.length,2);assert.equal(new Set(markers).size,2);
});
test('metric map scale tracks latitude and zoom and fits a compact 85 px corner',()=>{const {mapScale}=loadPure('src/utils/mapScale.ts');for(const lat of [0,21,60])for(const zoom of [8,14,18]){const scale=mapScale(lat,zoom);assert.ok(scale.width>0&&scale.width<=85);assert.match(scale.label,/ (m|km)$/);const resolution=40075016.686*Math.cos(lat*Math.PI/180)/(512*2**zoom);assert.ok(Math.abs(scale.width*resolution-scale.meters)<.001);}assert.equal(mapScale(NaN,14),null);});
test('every web engine keeps alternatives, traffic and POIs in incremental updates with safe payload encoding',()=>{const web=load('src/components/WebMapEngine.tsx',{'react':react,'react-native':{View:'View',ActivityIndicator:'ActivityIndicator',StyleSheet:{create:s=>s,absoluteFill:{}}},'react-native-webview':{WebView:'WebView'},'../config/env':{env:{osmTileUrl:'https://example.org/{z}/{x}/{y}',mapLibreDemUrl:'',cesiumIonToken:''}},'../config/mapProviders':{is3DMapProvider:()=>false,openMapStyleUrl:()=>null},'../services/traveledTrace':loadPure('src/services/traveledTrace.ts')});for(const engine of ['maplibre_gl','openlayers','cesium']){const tree=web.WebMapEngine({engine,currentPosition:{latitude:21,longitude:105},routeAlternatives:[[[21,105],[21.01,105]]],trafficSegments:[[[21,105],[21.01,105]]],places:[{placeId:-1,displayName:'</script><script>unsafe',latitude:21,longitude:105}]},null),html=tree.children[0].props.source.html,script=html.match(/<script>([\s\S]*?)<\/script>/)[1];assert.doesNotThrow(()=>new vm.Script(script));const payload=JSON.parse(script.match(/const payload=(.*?);const send=/)[1]);assert.equal(payload.alternatives[0][0][0],105);assert.equal(payload.traffic.length,1);assert.equal(payload.places.length,1);const update=engine==='maplibre_gl'?script.slice(script.indexOf('const refresh='),script.indexOf("map.on('load'")):script.slice(script.indexOf('update:(p)=>')); assert.match(update,/payload\.alternatives/);assert.match(update,/payload\.traffic/);assert.match(update,/payload\.places|addPoints/);}});
