import React,{useCallback,useEffect,useRef,useState}from'react';
import{View,Pressable,Modal,Switch,ScrollView,AppState,Alert,Image}from'react-native';
import{useFocusEffect,useNavigation,useRoute}from'@react-navigation/native';
import*as Crypto from'expo-crypto';
import*as Notifications from'expo-notifications';
import*as Location from'expo-location';
import*as ImagePicker from'expo-image-picker';
import{persistParkingPhoto,deleteParkingPhoto}from'../services/parkingPhoto';
import{VehicleInsights}from'../components/VehicleInsights';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{Text}from'../ui/Text';
import{TextInput}from'../ui/TextInput';
import{ScreenScaffold}from'../ui/ScreenScaffold';
import{GlassSurface,GlassButton,GlassChip,glassColors}from'../ui/glass';
import{PlaceSearchSheet}from'../components/PlaceSearchSheet';
import{TripPoll}from'../components/TripPoll';
import{NearbyContent}from'../components/NearbyContent';
import{ContentInteractions}from'../components/ContentInteractions';
import{DeviceAiComposer}from'../components/DeviceAiComposer';
import{getDeviceCurrentPosition}from'../services/platformLocation';
import{listDocuments,saveDocument,removeDocument,syncCatalog,acceptRemoteDocument,pendingCatalogDeletes}from'../services/catalogStore';
import{calculateItinerary,type PlannedLeg}from'../services/tripPlanner';
import{validateTrip,validateVehicle,tripCost,remainingBatteryRange,validateRoadReport,validateExpense,validateJournal,validateEvent,validateReview,localDateTime,parseLocalDateTime}from'../utils/catalogRules';
import{getSharingPrivacy,saveSharingPrivacy,type SharingPrivacy}from'../services/sharingPrivacy';
import{createLocationProof,exportEncryptedHistory}from'../services/locationProof';
import{encryptPrivate,decryptPrivate,authenticateDevice}from'../services/platformCapabilities';
import{setAppLock,APP_LOCK_KEY}from'../components/AppLock';
import{listConnections,type FriendConnection}from'../services/friendDiscovery';
import{shareLocalFile}from'../services/shareFile';
import{subscribeAuthState}from'../services/auth';
import{getFavoriteRoutes,favoriteRoute}from'../services/favoriteRoutes';
import{useAppTheme}from'../ui/theme';
import type{CatalogDocument,CatalogKind,TripPlan,TripStop,Vehicle,Parking,Expense,Maintenance,PlaceCollection,RoadReport,EmergencyCard,CatalogPlace,TravelJournal,MeetupEvent,PlaceReview}from'../types/catalog';
const inputStyle={backgroundColor:'#121C2D',color:'#fff',padding:13,borderRadius:12,minHeight:48};
const reports:RoadReport['category'][]=['hazard','pothole','flood','accident','closure','broken_light'];
const reportLabels=['Nguy hiểm','Ổ gà','Ngập nước','Tai nạn','Đóng đường','Đèn hỏng'];
export default function CatalogScreen(){
 const nav=useNavigation<any>();const route=useRoute<any>();const{theme}=useAppTheme();const[favorites,setFavorites]=useState<string[]>([]),[onlyFavorites,setOnlyFavorites]=useState(false);const[tab,setTab]=useState<'trip'|'vehicle'|'collection'|'journal'|'event'|'review'|'road_report'|'privacy'>(route.params?.tab||'trip');
 const[interactionId,setInteractionId]=useState<string|null>(null);const pending=useRef(false),generation=useRef(0);const[parkingPhoto,setParkingPhoto]=useState(''),[fullFill,setFullFill]=useState(false);const[proofDays,setProofDays]=useState<7|30|90>(30);
 const[deletions,setDeletions]=useState<Awaited<ReturnType<typeof pendingCatalogDeletes>>>([]);const[docs,setDocs]=useState<CatalogDocument<any>[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 const[editor,setEditor]=useState<CatalogKind|null>(null),[editing,setEditing]=useState<CatalogDocument<any>|undefined>(),[name,setName]=useState(''),[note,setNote]=useState(''),[amount,setAmount]=useState(''),[quantity,setQuantity]=useState(''),[people,setPeople]=useState('1'),[odometer,setOdometer]=useState(''),[consumption,setConsumption]=useState(''),[price,setPrice]=useState(''),[fuel,setFuel]=useState<Vehicle['fuel']>('petrol'),[vehicleId,setVehicleId]=useState(''),[hours,setHours]=useState(''),[category,setCategory]=useState<RoadReport['category']>('hazard');
 const[stops,setStops]=useState<TripStop[]>([]),[places,setPlaces]=useState<PlaceCollection['places']>([]),[search,setSearch]=useState(false),[mode,setMode]=useState<TripPlan['mode']>('motorbike'),[legs,setLegs]=useState<PlannedLeg[]>([]),[tripView,setTripView]=useState<CatalogDocument<TripPlan>|null>(null),[friends,setFriends]=useState<FriendConnection[]>([]),[members,setMembers]=useState<string[]>([]);
 const[privacy,setPrivacy]=useState<SharingPrivacy>({privateTrip:false,delayMinutes:0,ghostUntil:null}),[locked,setLocked]=useState(false),[card,setCard]=useState<EmergencyCard|null>(null);
 const[battery,setBattery]=useState(''),[reserve,setReserve]=useState('15'),[batteryPercent,setBatteryPercent]=useState('80'),[startsAt,setStartsAt]=useState(''),[endsAt,setEndsAt]=useState(''),[entryPlace,setEntryPlace]=useState<CatalogPlace|null>(null),[publish,setPublish]=useState(false),[rating,setRating]=useState<PlaceReview['rating']>(5),[expenseCategory,setExpenseCategory]=useState<Expense['category']>('fuel');
 const reload=useCallback(async()=>{const token=generation.current;const [all,p,l,f,d]=await Promise.all([listDocuments(),getSharingPrivacy(),AsyncStorage.getItem(APP_LOCK_KEY),getFavoriteRoutes(),pendingCatalogDeletes()]);if(token!==generation.current)return;setDocs(all);setDeletions(d);setPrivacy(p);setLocked(l==='true');setFavorites(f);},[]);
 useFocusEffect(useCallback(()=>{const token=generation.current;void reload().catch(e=>{if(token===generation.current)setError(e.message);});void listConnections().then(f=>{if(token===generation.current)setFriends(f.filter(x=>x.direction==='accepted'));}).catch(()=>{});return()=>{generation.current++;setCard(null);};},[reload]));
 useEffect(()=>{let previous:string|undefined;return subscribeAuthState((_event,session)=>{const id=session?.user.id||'local';if(previous!==undefined&&previous!==id){generation.current++;setDocs([]);setDeletions([]);setFavorites([]);setFriends([]);setCard(null);setEditor(null);setInteractionId(null);setTripView(null);setLegs([]);void reload().catch(()=>{});}previous=id;});},[reload]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state!=='active'){setCard(null);if(editor==='emergency_card'){setEditor(null);setName('');setNote('');setAmount('');setPrice('');setConsumption('');setQuantity('');}}});return()=>sub.remove();},[editor]);
 useEffect(()=>{if(route.params?.tab)setTab(route.params.tab);},[route.params?.tab]);
 async function action(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');setStatus('');try{await work();}catch(e){setError(e instanceof Error?e.message:String((e as{message?:string})?.message||e));}finally{await reload().catch(()=>{});pending.current=false;setBusy(false);}}
 const vehicles=docs.filter(d=>d.kind==='vehicle')as CatalogDocument<Vehicle>[];
 const button=(text:string,fn:()=>void)=> <GlassButton tone="blue" disabled={busy} onPress={fn}><Text style={{color:'#fff'}}>{text}</Text></GlassButton>;
 const field=(label:string,value:string,set:(value:string)=>void,numeric=false)=><View style={{gap:5}}><Text style={{color:theme.colors.muted}}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={set} keyboardType={numeric?'decimal-pad':'default'} style={{...inputStyle,backgroundColor:theme.colors.bgRaised,color:theme.colors.text,borderWidth:1,borderColor:theme.colors.border}} editable={!busy}/></View>;
 function open(kind:CatalogKind,doc?:CatalogDocument<any>){setEditor(kind);setEditing(doc);setName(doc?.data.name||'');setNote(doc?.data.note||'');setAmount(String(doc?.data.amount??''));setQuantity(String(doc?.data.quantity??''));setPeople(String(doc?.data.splitPeople??1));setOdometer(kind==='maintenance'?'':String(doc?.data.odometerKm??0));setConsumption(String(doc?.data.consumptionPer100Km??0));setPrice(String(doc?.data.unitPrice??0));setFuel(doc?.data.fuel||'petrol');setVehicleId(doc?.data.vehicleId||vehicles[0]?.id||'');setStops(doc?.data.stops||[]);setPlaces(doc?.data.places||[]);setMode(doc?.data.mode||'motorbike');setHours('');setMembers(doc?.members||[]);setBattery(String(doc?.data.batteryKwh??''));setReserve(String(doc?.data.reservePercent??15));setStartsAt(localDateTime(doc?.data.startsAt??doc?.data.at??doc?.data.visitedAt??Date.now()));setEndsAt(localDateTime(doc?.data.endsAt??Date.now()+3600000));setEntryPlace(doc?.data.place||null);setRating(doc?.data.rating||5);setPublish(doc?.sync!=='local'&&!!doc);setExpenseCategory(doc?.data.category&&['fuel','charging','toll','parking','other'].includes(doc.data.category)?doc.data.category:'fuel');setParkingPhoto('');setFullFill(doc?.data.fullFill===true);if(kind==='emergency_card'){setConsumption('');setPrice('');}setError('');}
 function numeric(value:string,label:string,allowZero=true){const n=Number(value.replace(',','.'));if(!value.trim()||!Number.isFinite(n)||n<0||(!allowZero&&n===0))throw new Error(`${label} không hợp lệ.`);return n;}
 async function current(){const p=await Location.requestForegroundPermissionsAsync();if(!p.granted)throw new Error('Cần quyền vị trí.');return(await getDeviceCurrentPosition({accuracy:Location.Accuracy.High})).coords;}
 async function save(){if(!editor)return;const now=Date.now();
  if(editor==='trip'){const data:TripPlan={name,mode,startsAt:parseLocalDateTime(startsAt),stops,votes:editing?.data.votes||{},favorite:editing?.data.favorite||false};validateTrip(data);await saveDocument('trip',data,editing,{members,share:members.length>0});setTripView(null);setLegs([]);}
  if(editor==='collection'){if(!name.trim())throw new Error('Nhập tên danh sách.');await saveDocument('collection',{name,places},editing,{members,share:members.length>0});}
  if(editor==='vehicle'){const data:Vehicle={name,fuel,odometerKm:numeric(odometer,'Số km'),consumptionPer100Km:numeric(consumption,'Mức tiêu hao'),unitPrice:numeric(price,'Đơn giá'),...(fuel==='electric'?{batteryKwh:battery.trim()?numeric(battery,'Dung lượng pin',false):undefined,reservePercent:numeric(reserve,'Pin dự phòng')}:{})};validateVehicle(data);await saveDocument('vehicle',data,editing);}
  if(editor==='parking'){if(!vehicleId)throw new Error('Thêm xe trước.');const c=await current();let reminderAt:number|undefined,notificationId:string|undefined;let photoUri:string|undefined;if(hours.trim()){reminderAt=now+numeric(hours,'Thời gian đỗ',false)*60000;const p=await Notifications.requestPermissionsAsync();if(!p.granted)throw new Error('Cần quyền thông báo cho hẹn giờ đỗ.');notificationId=await Notifications.scheduleNotificationAsync({content:{title:'MyMap · Hết thời gian đỗ xe',body:note||'Kiểm tra xe và thời gian đỗ.'},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date:new Date(reminderAt)}});}try{if(parkingPhoto)photoUri=await persistParkingPhoto(parkingPhoto);await saveDocument<Parking>('parking',{vehicleId,latitude:c.latitude,longitude:c.longitude,at:now,note,photoUri,reminderAt,notificationId});}catch(e){if(notificationId)await Notifications.cancelScheduledNotificationAsync(notificationId).catch(()=>{});if(photoUri)deleteParkingPhoto(photoUri);throw e;}}
  if(editor==='expense'){const data:Expense={tripId:editing?.data.tripId||tripView?.id||null,vehicleId:vehicleId||null,category:expenseCategory,amount:numeric(amount,'Số tiền'),at:editing?.data.at||now,note,splitPeople:numeric(people,'Số người',false),quantity:quantity.trim()?numeric(quantity,'Lượng nhiên liệu'):undefined,odometerKm:odometer.trim()?numeric(odometer,'Mốc km'):undefined,fullFill};validateExpense(data);await saveDocument('expense',data,editing);}
  if(editor==='journal'){const data:TravelJournal={name,note,at:parseLocalDateTime(startsAt),place:entryPlace};validateJournal(data);await saveDocument('journal',data,editing,{members,share:members.length>0});}
  if(editor==='event'){const data:MeetupEvent={name,note,startsAt:parseLocalDateTime(startsAt),endsAt:parseLocalDateTime(endsAt),place:entryPlace!};validateEvent(data);if(publish&&data.endsAt<=now)throw new Error('Sự kiện công khai cần kết thúc trong tương lai.');await saveDocument('event',data,editing,{share:publish,expiresAt:data.endsAt});}
  if(editor==='review'){const data:PlaceReview={name,note,rating,visitedAt:parseLocalDateTime(startsAt),place:entryPlace!};validateReview(data);await saveDocument('review',data,editing,{share:publish});}
  if(editor==='maintenance'){if(!vehicleId||!name.trim())throw new Error('Chọn xe và nhập công việc.');const dueKm=odometer.trim()?numeric(odometer,'Mốc km'):null;const dueAt=hours.trim()?now+numeric(hours,'Số ngày',false)*86400000:null;if(dueKm==null&&dueAt==null)throw new Error('Nhập mốc km hoặc số ngày.');let notificationId:string|undefined;if(dueAt){const p=await Notifications.requestPermissionsAsync();if(!p.granted)throw new Error('Cần quyền thông báo.');notificationId=await Notifications.scheduleNotificationAsync({content:{title:'MyMap · Nhắc bảo dưỡng',body:name},trigger:{type:Notifications.SchedulableTriggerInputTypes.DATE,date:new Date(dueAt)}});}try{await saveDocument<Maintenance>('maintenance',{vehicleId,name,dueAt,dueKm,done:false,notificationId});}catch(e){if(notificationId)await Notifications.cancelScheduledNotificationAsync(notificationId).catch(()=>{});throw e;}}
  if(editor==='road_report'){const c=await current();const data:RoadReport={category,latitude:c.latitude,longitude:c.longitude,note,createdAt:now};validateRoadReport(data);await saveDocument('road_report',data,undefined,{share:true,expiresAt:now+6*3600000});}
  if(editor==='emergency_card'){const data:EmergencyCard={name,bloodType:quantity,allergies:note,medications:consumption,contacts:[{name:price,phone:amount}]};if(!name.trim())throw new Error('Nhập tên.');await saveDocument('emergency_card',{ciphertext:await encryptPrivate(data)},editing);}
  setEditor(null);setStatus('Đã lưu trên thiết bị. Dữ liệu chia sẻ được đưa vào hàng đợi đồng bộ.');
 }
 const list=docs.filter(d=>tab==='vehicle'?['vehicle','parking','expense','maintenance'].includes(d.kind):d.kind===tab).filter(d=>tab!=='trip'||!onlyFavorites||favorites.includes(d.id)).sort((a,b)=>Number(b.id===route.params?.documentId)-Number(a.id===route.params?.documentId)||Number(favorites.includes(b.id))-Number(favorites.includes(a.id)));
 return <ScreenScaffold title="Công cụ hành trình" subtitle="Lên kế hoạch, quản lý xe và giữ dữ liệu riêng tư">
  <ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={{flexDirection:'row',gap:8}}>{(['trip','vehicle','collection','journal','event','review','road_report','privacy']as const).map((t,i)=><GlassChip key={t} label={['Chuyến đi','Xe của tôi','Danh sách','Nhật ký','Hẹn gặp','Đánh giá','Đường cộng đồng','Bảo mật'][i]!} active={tab===t} onPress={()=>setTab(t)}/>)}</View></ScrollView>
  {!!error&&<Text style={{color:'#FFBCBC'}}>{error}</Text>}{!!status&&<Text style={{color:'#7EE2BF'}}>{status}</Text>}
  {!!deletions.length&&<GlassSurface style={{padding:16,gap:8}}><Text>{deletions.length} mục đang chờ xóa trên máy chủ</Text><Text style={{color:theme.colors.muted}}>Mục đã ẩn trên thiết bị. Các thiết bị khác cập nhật sau khi kết nối và đồng bộ thành công.</Text>{deletions.map(d=>d.error?<Text key={d.id} style={{color:theme.colors.danger}}>{d.error}</Text>:null)}{button('Đồng bộ các mục chờ xóa',()=>void action(syncCatalog))}</GlassSurface>}
  {tab!=='privacy'&&<View style={{gap:8}}>{button(tab==='trip'?'Tạo chuyến đi':tab==='vehicle'?'Thêm xe':tab==='collection'?'Tạo danh sách':tab==='journal'?'Viết nhật ký':tab==='event'?'Tạo cuộc hẹn':tab==='review'?'Đánh giá địa điểm':'Báo cáo tại vị trí hiện tại',()=>open(tab))}{button(busy?'Đang đồng bộ…':'Đồng bộ với tài khoản',()=>void action(syncCatalog))}</View>}
  {tab==='trip'&&<GlassChip label={onlyFavorites?'Đang xem tuyến yêu thích':'Chỉ xem tuyến yêu thích'} active={onlyFavorites} onPress={()=>setOnlyFavorites(!onlyFavorites)}/>}
  {(tab==='event'||tab==='review')&&<NearbyContent kind={tab}/>}
  {tab==='vehicle'&&<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{button('Lưu chỗ đỗ',()=>open('parking'))}{button('Ghi chi phí',()=>open('expense'))}{button('Nhắc bảo dưỡng',()=>open('maintenance'))}</View>}
  {tab!=='privacy'&&list.length===0&&<GlassSurface style={{padding:18}}><Text>Chưa có dữ liệu. Thêm mục đầu tiên để bắt đầu.</Text></GlassSurface>}
  {tab!=='privacy'&&list.map(doc=><GlassSurface key={doc.id} style={{padding:16,gap:10}}><Text style={{fontSize:18,fontWeight:'700'}}>{doc.data.name||({parking:'Chỗ đỗ đã lưu',expense:'Chi phí',road_report:reportLabels[reports.indexOf(doc.data.category)]}as Record<string,string>)[doc.kind]||doc.kind}</Text>
   <Text style={{color:glassColors.muted}}>{doc.kind==='trip'?`${doc.data.stops.length} điểm dừng`:doc.kind==='vehicle'?`${doc.data.odometerKm} km · ${doc.data.consumptionPer100Km} ${doc.data.fuel==='electric'?'kWh':'lít'}/100 km`:doc.kind==='collection'?`${doc.data.places.length} địa điểm`:doc.kind==='expense'?`${doc.data.amount.toLocaleString('vi-VN')} đ · ${(doc.data.amount/doc.data.splitPeople).toLocaleString('vi-VN')} đ/người`:doc.kind==='maintenance'?`${doc.data.done?'Đã xong':'Chưa xong'} · ${doc.data.dueKm??'—'} km · ${doc.data.dueAt?new Date(doc.data.dueAt).toLocaleDateString():'—'}`:doc.data.note||new Date(doc.updatedAt).toLocaleString()}</Text>
   {['journal','review','event'].includes(doc.kind)&&<View style={{gap:8}}><Text style={{lineHeight:22}}>{doc.data.note}</Text>{doc.kind==='review'&&<Text>{'★'.repeat(doc.data.rating)} · ghé thăm {new Date(doc.data.visitedAt).toLocaleDateString('vi-VN')}</Text>}{doc.kind==='event'&&<Text>{new Date(doc.data.startsAt).toLocaleString('vi-VN')} → {new Date(doc.data.endsAt).toLocaleString('vi-VN')}</Text>}{doc.data.place&&button(`Đi đến ${doc.data.place.name}`,()=>nav.navigate('Tabs',{screen:'Map',params:{destination:doc.data.place}}))}</View>}
   {doc.kind==='trip'&&<><TripPoll document={doc}/>{button(favorites.includes(doc.id)?'Bỏ khỏi tuyến yêu thích':'Lưu tuyến yêu thích',()=>void action(()=>favoriteRoute(doc.id,!favorites.includes(doc.id))))}</>}
   {doc.kind==='vehicle'&&<VehicleInsights id={doc.id} vehicle={doc.data} expenses={docs.filter(d=>d.kind==='expense').map(d=>d.data)}/>}
   {doc.kind==='parking'&&doc.data.photoUri&&<Image accessibilityLabel="Ảnh chỗ đỗ xe" source={{uri:doc.data.photoUri}} style={{height:180,borderRadius:12}} resizeMode="contain"/>}
   {doc.kind==='vehicle'&&doc.data.fuel==='electric'&&doc.data.batteryKwh&&<View style={{gap:8}}>{field('Mức pin hiện tại (%)',batteryPercent,setBatteryPercent,true)}<Text>Tầm hoạt động dự kiến: {remainingBatteryRange(doc.data,Number(batteryPercent))?.toFixed(1)??'—'} km · đã giữ {doc.data.reservePercent??15}% pin dự phòng. Ước tính theo mức tiêu hao nhập thủ công.</Text></View>}
   {(doc.kind==='event'||doc.kind==='review')&&doc.sync==='synced'&&<View style={{gap:10}}>{button(interactionId===doc.id?'Đóng bình luận và tương tác':'Bình luận và tương tác',()=>setInteractionId(interactionId===doc.id?null:doc.id))}{interactionId===doc.id&&<ContentInteractions documentId={doc.id} event={doc.kind==='event'}/>}</View>}
   {doc.sync!=='local'&&<Text style={{color:doc.error?'#FFBCBC':glassColors.muted}}>{doc.sync==='synced'?'Đã đồng bộ':doc.sync==='conflict'?'Có thay đổi trên thiết bị khác':'Đang chờ đồng bộ'}{doc.error?` · ${doc.error}`:''}</Text>}
   <View style={{gap:8}}>{doc.kind==='trip'&&button('Xem lịch trình',()=>void action(async()=>{const planned=await calculateItinerary(doc.data);setTripView(doc);setLegs(planned);}))}{doc.kind==='parking'&&button('Tìm xe',()=>nav.navigate('Tabs',{screen:'Map',params:{destination:{name:'Xe đã đỗ',latitude:doc.data.latitude,longitude:doc.data.longitude},travelMode:'foot'}}))}{doc.kind==='collection'&&doc.data.places.map((p:PlaceCollection['places'][number])=>button(`Đi đến ${p.name}`,()=>nav.navigate('Tabs',{screen:'Map',params:{destination:p}})))}{doc.kind==='maintenance'&&!doc.data.done&&button('Đánh dấu đã bảo dưỡng',()=>void action(async()=>{if(doc.data.notificationId)await Notifications.cancelScheduledNotificationAsync(doc.data.notificationId);await saveDocument('maintenance',{...doc.data,done:true},doc);}))}{['trip','vehicle','collection','expense','journal','event','review'].includes(doc.kind)&&button('Chỉnh sửa',()=>open(doc.kind,doc))}{doc.sync==='conflict'&&button('Dùng bản trên máy chủ',()=>void action(()=>acceptRemoteDocument(doc)))}{doc.owned!==false&&button('Xóa mục',()=>Alert.alert('Xóa mục này?',doc.sync==='local'?'Xóa dữ liệu trên thiết bị.':'Xóa khỏi tài khoản và các thiết bị đã chia sẻ.',[{text:'Giữ lại',style:'cancel'},{text:'Xóa',style:'destructive',onPress:()=>void action(async()=>{await removeDocument(doc);if(doc.data.notificationId)await Notifications.cancelScheduledNotificationAsync(doc.data.notificationId);if(doc.kind==='parking'&&doc.data.photoUri)deleteParkingPhoto(doc.data.photoUri);if(tripView?.id===doc.id){setTripView(null);setLegs([]);}})}]))}</View>
  </GlassSurface>)}
  {tripView&&tab==='trip'&&<GlassSurface style={{padding:16,gap:12}}><Text style={{fontSize:19,fontWeight:'700'}}>Lịch trình · {tripView.data.name}</Text>{legs.map((leg,i)=><View key={i} style={{gap:5}}><Text>{tripView.data.stops[i]!.name} → {tripView.data.stops[i+1]!.name}</Text><Text>{(leg.route.distanceMeters/1000).toFixed(1)} km · {Math.round(leg.route.durationSeconds/60)} phút · đến {new Date(leg.arrivalAt).toLocaleTimeString()}</Text>{button('Dẫn đường chặng này',()=>nav.navigate('Tabs',{screen:'Map',params:{destination:tripView.data.stops[i+1],travelMode:tripView.data.mode}}))}</View>)}{vehicles.map(v=><Text key={v.id}>Chi phí dự kiến {v.data.name}: {tripCost(v.data,legs.reduce((sum,l)=>sum+l.route.distanceMeters,0)).amount.toLocaleString('vi-VN')} đ (theo mức tiêu hao đã nhập)</Text>)}{button('Ghi chi phí chuyến đi',()=>open('expense'))}</GlassSurface>}
  {tab==='privacy'&&<View style={{gap:14}}><GlassSurface style={{padding:16,gap:14}}><Text style={{fontSize:19,fontWeight:'700'}}>Chia sẻ vị trí</Text><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text>Chuyến đi riêng tư</Text><Switch value={privacy.privateTrip} onValueChange={v=>void action(()=>saveSharingPrivacy({...privacy,privateTrip:v}))}/></View><Text style={{color:glassColors.muted}}>Dừng gửi vị trí tự động. SOS vẫn cần bạn chủ động xác nhận.</Text><Text>Trễ vị trí</Text><View style={{flexDirection:'row',gap:6}}>{([0,5,15,30]as const).map(n=><GlassChip key={n} label={n===0?'Tắt':`${n} phút`} active={privacy.delayMinutes===n} onPress={()=>void action(()=>saveSharingPrivacy({...privacy,delayMinutes:n}))}/>)}</View>{button(privacy.ghostUntil?'Tắt lịch ẩn':'Ẩn vị trí trong 1 giờ',()=>void action(()=>saveSharingPrivacy({...privacy,ghostUntil:privacy.ghostUntil?null:Date.now()+3600000})))}</GlassSurface>
   <GlassSurface style={{padding:16,gap:12}}><Text style={{fontSize:19,fontWeight:'700'}}>Bảo vệ trên thiết bị</Text><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text>Khóa bằng sinh trắc</Text><Switch value={locked} onValueChange={v=>void action(()=>setAppLock(v))}/></View><View style={{flexDirection:'row',gap:6}}>{([7,30,90]as const).map(d=><GlassChip key={d} label={`${d} ngày`} active={proofDays===d} onPress={()=>setProofDays(d)}/>)}</View>{button('Xuất lịch sử có chữ ký thiết bị',()=>void action(async()=>{const uri=await createLocationProof(proofDays);await shareLocalFile(uri,'Lịch sử MyMap có chữ ký');}))}{button('Xuất bản sao lịch sử mã hóa',()=>void action(async()=>{if(!await authenticateDevice())throw new Error('Chưa xác thực.');await shareLocalFile(await exportEncryptedHistory(proofDays),'Lịch sử MyMap mã hóa');}))}<Text style={{color:glassColors.muted}}>Bản sao mã hóa chỉ giải mã bằng khóa của thiết bị này. Chữ ký giúp kiểm tra thay đổi dữ liệu; thời gian là giờ thiết bị.</Text></GlassSurface>
   <GlassSurface style={{padding:16,gap:12}}><Text style={{fontSize:19,fontWeight:'700'}}>Thẻ khẩn cấp ngoại tuyến</Text>{button(docs.some(d=>d.kind==='emergency_card')?'Chỉnh sửa thẻ mã hóa':'Tạo thẻ được mã hóa',()=>void action(async()=>{const d=docs.find(d=>d.kind==='emergency_card');if(d){if(!await authenticateDevice())throw new Error('Chưa xác thực.');const c=await decryptPrivate<EmergencyCard>(d.data.ciphertext);open('emergency_card',d);setName(c.name);setQuantity(c.bloodType);setNote(c.allergies);setConsumption(c.medications);setPrice(c.contacts[0]?.name||'');setAmount(c.contacts[0]?.phone||'');}else open('emergency_card');}))}{button('Mở thẻ',()=>void action(async()=>{const d=docs.find(d=>d.kind==='emergency_card');if(!d)throw new Error('Chưa có thẻ.');if(!await authenticateDevice())throw new Error('Chưa xác thực.');setCard(await decryptPrivate<EmergencyCard>(d.data.ciphertext));}))}{card&&<View style={{gap:7}}><Text>{card.name} · {card.bloodType}</Text><Text>Dị ứng: {card.allergies||'Chưa ghi'}</Text><Text>Thuốc: {card.medications||'Chưa ghi'}</Text>{card.contacts.map((c,i)=><Text key={i}>{c.name}: {c.phone}</Text>)}{button('Đóng thẻ',()=>setCard(null))}</View>}</GlassSurface></View>}
  <Modal visible={!!editor} transparent animationType="slide" onRequestClose={()=>{if(!busy)setEditor(null);}}><View style={{flex:1,backgroundColor:'#000A',justifyContent:'center',padding:18}}><GlassSurface style={{padding:18,maxHeight:'90%'}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:13}}><Text style={{fontSize:22,fontWeight:'700'}}>Thêm / chỉnh sửa</Text>
   {['trip','vehicle','collection','maintenance','emergency_card','journal','event','review'].includes(editor||'')&&field('Tên',name,setName)}
   {editor==='vehicle'&&<><View style={{flexDirection:'row',gap:6}}>{(['petrol','diesel','electric']as const).map((f,i)=><GlassChip key={f} label={['Xăng','Dầu','Điện'][i]!} active={fuel===f} onPress={()=>setFuel(f)}/>)}</View>{field('Công-tơ-mét (km)',odometer,setOdometer,true)}{field(fuel==='electric'?'Mức tiêu hao (kWh/100 km)':'Mức tiêu hao (lít/100 km)',consumption,setConsumption,true)}{field(fuel==='electric'?'Giá mỗi kWh (đ)':'Giá mỗi lít (đ)',price,setPrice,true)}{fuel==='electric'&&<>{field('Dung lượng pin (kWh, tùy chọn)',battery,setBattery,true)}{field('Giữ lại mức pin dự phòng (%)',reserve,setReserve,true)}</>}</>}
   {['parking','expense','maintenance'].includes(editor||'')&&<View style={{gap:8}}><Text>Xe</Text>{vehicles.map(v=><GlassChip key={v.id} label={v.data.name} active={vehicleId===v.id} onPress={()=>setVehicleId(v.id)}/>)}</View>}
   {editor==='trip'&&<>{field('Ngày giờ khởi hành (YYYY-MM-DD HH:mm)',startsAt,setStartsAt)}<View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{(['motorbike','car','foot','bike']as const).map((m,i)=><GlassChip key={m} label={['Xe máy','Ô tô','Đi bộ','Xe đạp'][i]!} active={mode===m} onPress={()=>setMode(m)}/>)}</View>{stops.map((p,i)=><View key={p.id} style={{gap:6}}><Text>{i+1}. {p.name}</Text>{field('Dừng lại (phút)',String(p.stayMinutes),value=>setStops(stops.map((s,j)=>j===i?{...s,stayMinutes:Number(value)}:s)),true)}{button('Bỏ điểm',()=>setStops(stops.filter(s=>s.id!==p.id)))}{i>0&&button('Chuyển lên',()=>{const next=[...stops];[next[i-1],next[i]]=[next[i]!,next[i-1]!];setStops(next);})}</View>)}{button('Thêm điểm dừng',()=>setSearch(true))}</>}
   {editor==='collection'&&<>{places.map(p=><View key={p.id}><Text>{p.name}</Text>{button('Bỏ địa điểm',()=>setPlaces(places.filter(x=>x.id!==p.id)))}</View>)}{button('Thêm địa điểm',()=>setSearch(true))}</>}
   {(editor==='trip'||editor==='collection'||editor==='journal')&&editing?.owned!==false&&friends.length>0&&<View style={{gap:7}}><Text>Bạn cùng chỉnh sửa</Text>{friends.map(f=><GlassChip key={f.user_id} label={f.display_name||f.username||'Bạn'} active={members.includes(f.user_id)} onPress={()=>setMembers(members.includes(f.user_id)?members.filter(id=>id!==f.user_id):[...members,f.user_id])}/>)}</View>}
   {editor==='expense'&&<><View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{(['fuel','charging','toll','parking','other']as const).map((c,i)=><GlassChip key={c} label={['Xăng dầu','Sạc điện','Phí đường','Đỗ xe','Khác'][i]!} active={expenseCategory===c} onPress={()=>setExpenseCategory(c)}/>)}</View>{field('Số tiền (đ)',amount,setAmount,true)}{field('Lượng nhiên liệu (lít/kWh, tùy chọn)',quantity,setQuantity,true)}{field('Chia đều cho số người',people,setPeople,true)}{field('Mốc công-tơ-mét (km, tùy chọn)',odometer,setOdometer,true)}{(expenseCategory==='fuel'||expenseCategory==='charging')&&<View style={{flexDirection:'row',justifyContent:'space-between'}}><Text>Đã đầy bình / đầy pin</Text><Switch value={fullFill} onValueChange={setFullFill}/></View>}</>}
   {['journal','event','review'].includes(editor||'')&&<>{field(editor==='event'?'Bắt đầu (YYYY-MM-DD HH:mm)':'Ngày ghi nhận (YYYY-MM-DD HH:mm)',startsAt,setStartsAt)}{editor==='event'&&field('Kết thúc (YYYY-MM-DD HH:mm)',endsAt,setEndsAt)}<Text>{entryPlace?.name||'Chưa chọn địa điểm'}</Text>{button('Chọn địa điểm',()=>setSearch(true))}{editor==='review'&&<View style={{flexDirection:'row',gap:6}}>{([1,2,3,4,5]as const).map(n=><GlassChip key={n} label={`${n} ★`} active={rating===n} onPress={()=>setRating(n)}/>)}</View>}{(editor==='event'||editor==='review')&&<><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text>Công khai cho người dùng MyMap</Text><Switch value={publish} disabled={!!editing&&editing.sync!=='local'} onValueChange={setPublish}/></View><Text style={{color:glassColors.muted}}>Mặc định chỉ lưu trên máy. Mục đã công khai cần xóa để gỡ khỏi máy chủ.</Text></>}</>}
   {editor==='parking'&&<>{field('Nhắc sau bao nhiêu phút (tùy chọn)',hours,setHours,true)}{button('Chụp ảnh chỗ đỗ',()=>void action(async()=>{const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted)throw new Error('Cần quyền camera để chụp chỗ đỗ.');const photo=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.7});if(!photo.canceled&&photo.assets[0])setParkingPhoto(photo.assets[0].uri);} ))}{!!parkingPhoto&&<Image source={{uri:parkingPhoto}} style={{height:160,borderRadius:12}} resizeMode="contain"/>}</>}
   {editor==='maintenance'&&<>{field('Mốc công-tơ-mét (km)',odometer,setOdometer,true)}{field('Nhắc sau số ngày (tùy chọn)',hours,setHours,true)}</>}
   {editor==='road_report'&&<View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{reports.map((c,i)=><GlassChip key={c} label={reportLabels[i]!} active={category===c} onPress={()=>setCategory(c)}/>)}</View>}
   {editor==='emergency_card'&&<>{field('Nhóm máu',quantity,setQuantity)}{field('Thuốc đang dùng',consumption,setConsumption)}{field('Tên liên hệ khẩn cấp',price,setPrice)}{field('Số điện thoại liên hệ',amount,setAmount)}</>}
   {editor==='journal'&&<DeviceAiComposer key={editing?.id||'new-journal'} task="journal" facts={[name,entryPlace?.name,startsAt,note].filter(Boolean).join('\n')} onUse={setNote} disabled={busy}/>}
   {!['trip','collection','vehicle'].includes(editor||'')&&field(editor==='emergency_card'?'Dị ứng':'Ghi chú',note,setNote)}
   {!!error&&<Text style={{color:'#FFBCBC'}}>{error}</Text>}{button(busy?'Đang lưu…':'Lưu',()=>void action(save))}{button('Hủy',()=>setEditor(null))}
  </ScrollView></GlassSurface></View></Modal>
  <PlaceSearchSheet position={null} visible={search} onClose={()=>setSearch(false)} onSelect={p=>{const value={id:Crypto.randomUUID(),name:p.displayName.split(',')[0]!,latitude:p.latitude,longitude:p.longitude};if(editor==='trip')setStops([...stops,{...value,stayMinutes:0}]);else if(editor==='collection')setPlaces([...places,{...value,note:''}]);else setEntryPlace(value);setSearch(false);}}/>
 </ScreenScaffold>;
}
