import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Alert,AppState,Linking,View} from 'react-native';
import {useFocusEffect,useNavigation,useRoute} from '@react-navigation/native';
import * as DocumentPicker from 'expo-document-picker';
import {useExtensions} from '../hooks/useExtensions';
import {useAccountEpoch} from '../hooks/useAccountEpoch';
import {deviceAiHardware,downloadDefaultAiModel,prepareSystemAi,generateDeviceAi,getAiModel,importAiModel,systemAiStatus,removeAiModel,stopDeviceAi} from '../services/deviceAi';
import {DEFAULT_AI_MODEL} from '../utils/aiModels';
import type {AiTask} from '../utils/aiRules';
import {ScreenScaffold} from '../ui/ScreenScaffold';
import {GlassChip,GlassSurface} from '../ui/glass';
import {ActionButton} from '../ui/ActionButton';
import {Text} from '../ui/Text';
import {TextInput} from '../ui/TextInput';
export default function DeviceAiScreen(){
 const route=useRoute<any>(),nav=useNavigation<any>(),enabled=useExtensions().deviceAi,epoch=useAccountEpoch(),generation=useRef(0),pending=useRef(false);
 const [provider,setProvider]=useState<'system'|'local'>('local'),[task,setTask]=useState<AiTask>(route.params?.task||'assistant'),[input,setInput]=useState(route.params?.draft||''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('Chưa kiểm tra'),[model,setModel]=useState<Awaited<ReturnType<typeof getAiModel>>>(null),[progress,setProgress]=useState<number|null>(null),[hardware,setHardware]=useState<Awaited<ReturnType<typeof deviceAiHardware>>|null>(null);
 useFocusEffect(useCallback(()=>{const token=++generation.current;setAnswer('');setError('');setBusy(pending.current);const stop=()=>{generation.current++;void stopDeviceAi();setBusy(pending.current);setAnswer('');};const sub=AppState.addEventListener('change',state=>{if(state!=='active')stop();});if(enabled)void Promise.all([deviceAiHardware(),getAiModel(),systemAiStatus()]).then(([h,m,s])=>{if(token===generation.current){setHardware(h);setModel(m);setStatus(s==='available'?'Sẵn sàng':s==='downloadable'?'Cần tải mô hình':s==='downloading'?'Đang tải mô hình':'Máy chưa hỗ trợ Apple Intelligence');}}).catch(()=>{if(token===generation.current)setStatus('Chưa kiểm tra được AI trên thiết bị');});return()=>{sub.remove();stop();};},[enabled,epoch]));
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const previousEpoch=useRef(epoch);useEffect(()=>{if(previousEpoch.current!==epoch){previousEpoch.current=epoch;setInput('');}},[epoch]);
 async function work(action:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');const token=generation.current;try{await action();}catch(e){if(token===generation.current)setError((e as Error).message||'AI chưa sẵn sàng.');}finally{pending.current=false;if(mounted.current)setBusy(false);}}
 async function choose(){const token=generation.current;const result=await DocumentPicker.getDocumentAsync({type:'*/*',copyToCacheDirectory:false,multiple:false});if(result.canceled||token!==generation.current)return;const selected=await importAiModel(result.assets[0]!);if(token===generation.current)setModel(selected);}
 async function downloadModel(){const token=generation.current;setProgress(0);try{const selected=await downloadDefaultAiModel(value=>{if(token===generation.current)setProgress(value);});if(token===generation.current)setModel(selected);}finally{if(mounted.current)setProgress(null);}}
 async function generate(){const token=generation.current;setAnswer('');const result=await generateDeviceAi(provider,task,input,(text)=>{if(token===generation.current)setAnswer(text);});if(token===generation.current)setAnswer(result);}
 return <ScreenScaffold title="AI trên thiết bị" subtitle="Trợ lý, chú thích và nhật ký từ ghi chú của bạn">
 {!enabled?<ActionButton title="Bật AI trong Cài đặt" onPress={()=>nav.navigate('Settings')}/>:<>
 <GlassSurface style={{padding:18,gap:12}}><Text>Chỉ xử lý nội dung bạn nhập. Kết quả AI cần được kiểm tra trước khi dùng. App không tự gửi câu hỏi lên dịch vụ AI đám mây.</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><GlassChip label="Apple Intelligence" active={provider==='system'} disabled={busy} onPress={()=>setProvider('system')}/><GlassChip label="Mô hình cục bộ · GGUF" active={provider==='local'} disabled={busy} onPress={()=>setProvider('local')}/></View>
 {provider==='system'?<><Text>{status}</Text><Text>Cần iOS 26 và thiết bị hỗ trợ Apple Intelligence. Bật Apple Intelligence và tải mô hình trong Cài đặt của iPhone; suy luận chạy trên thiết bị.</Text><ActionButton title="Kiểm tra Apple Intelligence" disabled={busy||!hardware?.systemSupported} onPress={()=>void work(async()=>{const token=generation.current;await prepareSystemAi();if(token===generation.current)setStatus((await systemAiStatus())==='available'?'Sẵn sàng':'Chưa sẵn sàng');})}/></>:<><Text>{model?`${model.name} · ${Math.round(model.bytes/1024/1024)} MB`:'Chưa chọn mô hình'}</Text><Text>Chọn tệp GGUF instruct đa ngôn ngữ dưới 750 MB có giấy phép phù hợp. Cần máy 64 bit và đủ RAM. Mô hình được giữ trong bộ nhớ riêng của app; không tự tải tệp.</Text><Text>Qwen2.5 0.5B Instruct · Apache-2.0 · khoảng 469 MB. Bản nhỏ có thể trả lời sai hoặc chưa tốt bằng tiếng Việt.</Text><ActionButton title={progress===null?'Tải mô hình Qwen miễn phí':`Đang tải mô hình · ${Math.round(progress*100)}%`} disabled={busy||hardware?.local64Bit===false} onPress={()=>Alert.alert('Tải mô hình AI?', 'Tải khoảng 469 MB từ kho Qwen chính thức trên Hugging Face. Sau khi tải, câu hỏi được xử lý trên thiết bị. Nên dùng Wi-Fi.',[{text:'Hủy',style:'cancel'},{text:'Tải mô hình',onPress:()=>void work(downloadModel)}])}/><ActionButton title="Nguồn và giấy phép mô hình" onPress={()=>void Linking.openURL(DEFAULT_AI_MODEL.source).catch(()=>setError('Chưa thể mở trang mô hình.'))}/><ActionButton title="Chọn tệp mô hình GGUF" disabled={busy||hardware?.local64Bit===false} onPress={()=>void work(choose)}/>{model&&<ActionButton title="Xóa mô hình khỏi app" disabled={busy} onPress={()=>Alert.alert('Xóa mô hình?','Bạn có thể nhập lại mô hình sau.',[{text:'Hủy',style:'cancel'},{text:'Xóa',style:'destructive',onPress:()=>void work(async()=>{await removeAiModel();setModel(null);})}])}/>}</>}
 </GlassSurface>
 <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{(['assistant','caption','journal','search'] as AiTask[]).map(t=><GlassChip key={t} label={{assistant:'Trợ lý',caption:'Chú thích',journal:'Nhật ký',search:'Từ khóa địa điểm'}[t]} active={task===t} disabled={busy} onPress={()=>setTask(t)}/>)}</View>
 <TextInput value={input} onChangeText={setInput} editable={!busy} multiline maxLength={4500} placeholder="Nhập câu hỏi hoặc những sự kiện bạn muốn viết lại…" accessibilityLabel="Nội dung dành cho AI"/>
 <ActionButton title={busy?'AI đang xử lý…':'Tạo câu trả lời'} disabled={busy||!input.trim()||provider==='local'&&!model} onPress={()=>void work(generate)}/>{busy&&<ActionButton title="Dừng AI" onPress={()=>{generation.current++;void stopDeviceAi();setAnswer('');}}/>}
 {!!answer&&<GlassSurface style={{padding:18,gap:12}}><Text selectable>{answer}</Text>{task==='search'&&<ActionButton title="Tìm địa điểm bằng kết quả này" onPress={()=>nav.navigate('Tabs',{screen:'Map',params:{searchQuery:answer.trim().slice(0,150)}})}/>}</GlassSurface>}{!!error&&<Text accessibilityRole="alert">{error}</Text>}
 </>}
 </ScreenScaffold>;
}
