import {TextInput} from '../ui/TextInput';
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,AppState,Image,Pressable,StyleSheet,View} from 'react-native';
import {MaterialCommunityIcons} from '@expo/vector-icons';
import {useFocusEffect,useNavigation,useRoute} from '@react-navigation/native';
import {createAudioPlayer,useAudioRecorder,useAudioRecorderState,RecordingPresets,requestRecordingPermissionsAsync,setAudioModeAsync,setIsAudioActiveAsync,type AudioPlayer} from 'expo-audio';
import {ScreenScaffold} from '../ui/ScreenScaffold';
import {Text} from '../ui/Text';
import {MomentVideo} from '../components/MomentVideo';
import {listLocalMoments,listSharedMoments,listMomentGroups,listMomentReplies,replyToMoment,momentUrl,queueMoment,retryMoment,deleteMoment,shareMomentFile,configureMomentWidget,subscribeMomentChanges,downloadOwnMoment,type Moment,type MomentGroup,type MomentReply} from '../services/moments';
import {listConnections,type FriendConnection} from '../services/friendDiscovery';
import {pauseMusicPlayback} from '../services/musicPlayback';
import {stopMomentRecording} from '../services/momentAudioLifecycle';
const msg=(e:unknown)=>e instanceof Error?e.message:'Chưa hoàn tất. Hãy thử lại.';
export default function MomentDetailScreen(){
 const nav=useNavigation<any>(),route=useRoute<any>(),id=route.params.momentId as string;
 const [moment,setMoment]=useState<Moment|null>(null),[replies,setReplies]=useState<MomentReply[]>([]),[friends,setFriends]=useState<FriendConnection[]>([]),[groups,setGroups]=useState<MomentGroup[]>([]),[recipients,setRecipients]=useState<string[]>([]),[group,setGroup]=useState<string|null>(null),[shareLocation,setShareLocation]=useState(false),[text,setText]=useState(''),[voice,setVoice]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY),record=useAudioRecorderState(recorder,200),audio=useRef<AudioPlayer|null>(null),live=useRef(true);
 const load=useCallback(async()=>{setError(null);try{const local=(await listLocalMoments()).find(m=>m.id===id);const m=local??(await listSharedMoments()).find(m=>m.id===id);if(!m)throw new Error('Khoảnh khắc không còn tồn tại hoặc bạn không còn quyền xem.');if(m.remote&&m.mediaPath)m.uri=await momentUrl(m.mediaPath);if(!live.current)return;setMoment(m);if(m.status==='published')setReplies(await listMomentReplies(id));try{const [f,g]=await Promise.all([listConnections(),listMomentGroups()]);if(live.current){setFriends(f.filter(x=>x.relationship_status==='accepted'));setGroups(g);}}catch{/* Offline captures remain viewable. */}}catch(e){if(live.current)setError(msg(e));}finally{if(live.current)setLoading(false);}},[id]);
 useFocusEffect(useCallback(()=>{live.current=true;void load();const unsubscribe=subscribeMomentChanges(()=>void load());return()=>{unsubscribe();live.current=false;audio.current?.pause();void stopMomentRecording(recorder);};},[load,recorder]));
 useEffect(()=>{const sub=AppState.addEventListener('change',s=>{if(s!=='active'){audio.current?.pause();void stopMomentRecording(recorder).then(stopped=>{if(live.current&&stopped){try{setVoice(recorder.uri);}catch{/* Recorder was released during navigation. */}}});}});return()=>{sub.remove();const player=audio.current;audio.current=null;try{player?.remove();}catch{/* Already released. */}};},[recorder]);
 async function action(work:()=>Promise<void>){if(busy)return;setBusy(true);setError(null);try{await work();}catch(e){setError(msg(e));}finally{if(live.current)setBusy(false);}}
 async function recordVoice(){
  if(recorder.isRecording){await recorder.stop();setVoice(recorder.uri);await setAudioModeAsync({allowsRecording:false});return;}
  const permission=await requestRecordingPermissionsAsync();if(!permission.granted)throw new Error('Cần quyền micro để ghi lời nhắn.');await pauseMusicPlayback();audio.current?.pause();await setIsAudioActiveAsync(true);await setAudioModeAsync({allowsRecording:true,playsInSilentMode:true,shouldPlayInBackground:false,interruptionMode:'doNotMix'});await recorder.prepareToRecordAsync();recorder.record({forDuration:30});setVoice(null);
 }
 useEffect(()=>{if(!record.isRecording&&record.durationMillis>0&&recorder.uri){setVoice(recorder.uri);void setAudioModeAsync({allowsRecording:false}).catch(()=>{});}},[record.isRecording,record.durationMillis,recorder]);
 async function playVoice(uri:string){await pauseMusicPlayback();await setIsAudioActiveAsync(true);await setAudioModeAsync({allowsRecording:false,interruptionMode:'doNotMix',shouldPlayInBackground:false});audio.current?.remove();audio.current=createAudioPlayer(uri);audio.current.play();}
 const button=(label:string,onPress:()=>void,primary=false)=><Pressable accessibilityRole="button" disabled={busy||record.isRecording} style={[s.button,primary&&s.primary,busy&&{opacity:.5}]} onPress={onPress}><Text style={[s.btnText,primary&&{color:'#052C38'}]}>{label}</Text></Pressable>;
 return <ScreenScaffold title="Khoảnh khắc" subtitle={moment?new Date(moment.capturedAt).toLocaleString():''}>
  {loading&&<ActivityIndicator color="#64DBCF"/>}{error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
  {moment&&<>
   <View style={s.media}>{moment.kind==='photo'?<Image source={{uri:moment.uri}} style={s.fill} resizeMode="contain"/>:<MomentVideo uri={moment.uri}/>}</View>
   <View style={s.panel}><Text style={s.heading}>{moment.authorName||'Khoảnh khắc của bạn'}</Text>{!!moment.caption&&<Text style={s.copy}>{moment.caption}</Text>}
    <Text style={s.muted}>{moment.remote?'Được chia sẻ riêng':moment.status==='local'?'Chỉ lưu trên thiết bị':moment.status==='published'?'Đã chia sẻ riêng':moment.status==='queued'?'Đang chờ gửi':'Chưa gửi · bản lưu trên máy vẫn còn'}</Text>
    {moment.latitude!==null&&<Text style={s.muted}>{moment.remote?'Vị trí được chia sẻ':'Vị trí đã lưu riêng'}: {moment.latitude.toFixed(5)}, {moment.longitude?.toFixed(5)}</Text>}
    {!!moment.error&&<Text style={s.error}>{moment.error}</Text>}
   </View>
   {!moment.remote&&moment.status!=='published'&&<View style={s.panel}><Text style={s.heading}>Dành cho ai?</Text><Text style={s.muted}>Chọn bạn bè hoặc một nhóm. Không chọn ai thì chỉ đồng bộ riêng vào tài khoản của bạn.</Text>
    {friends.map(f=><Pressable key={f.user_id} disabled={busy} style={s.row} onPress={()=>{setGroup(null);setRecipients(recipients.includes(f.user_id)?recipients.filter(x=>x!==f.user_id):[...recipients,f.user_id]);}}><Text style={s.copy}>{f.display_name}</Text><MaterialCommunityIcons name={recipients.includes(f.user_id)?'checkbox-marked':'checkbox-blank-outline'} size={25} color="#64DBCF"/></Pressable>)}
    {groups.map(g=><Pressable key={g.id} disabled={busy} style={s.row} onPress={()=>{setGroup(group===g.id?null:g.id);setRecipients([]);}}><Text style={s.copy}>Nhóm · {g.name}</Text><MaterialCommunityIcons name={group===g.id?'radiobox-marked':'radiobox-blank'} size={25} color="#64DBCF"/></Pressable>)}
    {moment.latitude!==null&&<Pressable accessibilityRole="switch" accessibilityState={{checked:shareLocation}} style={s.row} onPress={()=>setShareLocation(!shareLocation)}><Text style={s.copy}>Gửi kèm vị trí đã lưu</Text><MaterialCommunityIcons name={shareLocation?'toggle-switch':'toggle-switch-off-outline'} size={32} color="#64DBCF"/></Pressable>}
    {button(group?'Gửi vào nhật ký nhóm':recipients.length?`Gửi cho ${recipients.length} người bạn`:'Đồng bộ riêng',()=>void action(async()=>{const result=await queueMoment(moment,recipients,group,shareLocation);setMoment(result);if(result.status==='failed')setError(result.error||'Chưa gửi được.');else await load();}),true)}
    {(moment.status==='failed'||moment.status==='queued')&&button('Gửi lại theo lựa chọn trước',()=>void action(async()=>{await retryMoment(moment);await load();}))}
   </View>}
   {moment.status==='published'&&<View style={s.panel}><Text style={s.heading}>Lời nhắn cho khoảnh khắc</Text><View style={s.emoji}>{['❤️','😂','😍','👏','🔥'].map(e=><Pressable key={e} disabled={busy} accessibilityRole="button" accessibilityLabel={`Thả cảm xúc ${e}`} style={s.reaction} onPress={()=>void action(async()=>{await replyToMoment(id,'emoji',e);await load();})}><Text style={{fontSize:26}}>{e}</Text></Pressable>)}</View>
    {replies.map(r=><View key={r.id} style={s.reply}><Text style={s.muted}>{new Date(r.created_at).toLocaleString()}</Text>{r.kind==='voice'?button('▶ Nghe lời nhắn',()=>void action(async()=>playVoice(await momentUrl(r.body)))):<Text style={s.copy}>{r.body}</Text>}</View>)}
    <TextInput value={text} onChangeText={setText} maxLength={500} multiline placeholder="Viết lời nhắn…" placeholderTextColor="#92AABD" accessibilityLabel="Nội dung lời nhắn" style={s.input}/>
    {button('Gửi lời nhắn',()=>void action(async()=>{if(!text.trim())throw new Error('Nhập lời nhắn trước khi gửi.');await replyToMoment(id,'text',text.trim());setText('');await load();}),true)}
    <Pressable disabled={busy} style={s.button} onPress={()=>void action(recordVoice)}><Text style={s.btnText}>{record.isRecording?`■ Dừng ghi · ${Math.round(record.durationMillis/1000)}s`:'Ghi lời nhắn giọng nói (tối đa 30s)'}</Text></Pressable>
    {voice&&!record.isRecording&&<View style={s.emoji}>{button('Nghe lại',()=>void action(()=>playVoice(voice)))}{button('Gửi giọng nói',()=>void action(async()=>{await replyToMoment(id,'voice',voice);setVoice(null);await load();}),true)}{button('Bỏ ghi âm',()=>setVoice(null))}</View>}
   </View>}
   {moment.remote&&moment.isMine&&<View style={s.emoji}>{button('Lưu trên máy',()=>void action(async()=>{setMoment(await downloadOwnMoment(moment));}))}{button('Xóa khoảnh khắc',()=>Alert.alert('Xóa khoảnh khắc?','Xóa bản chia sẻ của bạn.',[{text:'Hủy',style:'cancel'},{text:'Xóa',style:'destructive',onPress:()=>void action(async()=>{await deleteMoment(moment);nav.goBack();})}]))}</View>}{!moment.remote&&<View style={s.emoji}>{button('Đưa lên widget',()=>void action(async()=>{await configureMomentWidget({mode:'personal',momentId:moment.id});}))}{button('Chia sẻ tệp',()=>void shareMomentFile(moment.uri).catch(e=>setError(msg(e))))}{button('Xóa khoảnh khắc',()=>Alert.alert('Xóa khoảnh khắc?','Xóa bản lưu này và bản chia sẻ của bạn.',['photo','video'].includes(moment.kind)?[{text:'Hủy',style:'cancel'},{text:'Xóa',style:'destructive',onPress:()=>void action(async()=>{await deleteMoment(moment);nav.goBack();})}]:[]))}</View>}
  </>}{busy&&<ActivityIndicator color="#64DBCF"/>}
 </ScreenScaffold>;
}
const s=StyleSheet.create({media:{width:'100%',aspectRatio:.8,borderRadius:24,backgroundColor:'#02060C',overflow:'hidden'},fill:{width:'100%',height:'100%'},panel:{backgroundColor:'#152C43',borderRadius:24,padding:18,gap:14},heading:{color:'#F4FAFF',fontSize:19,fontWeight:'700'},copy:{color:'#F4FAFF',fontSize:15,lineHeight:23,flexShrink:1},muted:{color:'#9DB7CC',fontSize:12,lineHeight:18},error:{color:'#FFAFB8',fontSize:13,lineHeight:20},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',minHeight:48,paddingVertical:8,gap:10},button:{padding:15,borderRadius:17,backgroundColor:'#254057',minHeight:48,alignItems:'center'},primary:{backgroundColor:'#64DBCF'},btnText:{color:'#F4FAFF',fontSize:13,fontWeight:'700'},emoji:{flexDirection:'row',flexWrap:'wrap',gap:9},reaction:{width:48,height:48,justifyContent:'center',alignItems:'center'},reply:{borderLeftWidth:2,borderLeftColor:'#64DBCF',paddingLeft:12,gap:6},input:{backgroundColor:'#203A51',borderRadius:16,padding:15,minHeight:65,color:'#fff'}});
