import {TextInput} from '../ui/TextInput';
import React,{useCallback,useRef,useState} from 'react';
import {ActivityIndicator,Alert,Image,Modal,Pressable,RefreshControl,ScrollView,StyleSheet,View} from 'react-native';
import {MaterialCommunityIcons} from '@expo/vector-icons';
import {useFocusEffect,useNavigation,useRoute} from '@react-navigation/native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {ScreenScaffold,EmptyGlass} from '../ui/ScreenScaffold';
import {Text} from '../ui/Text';
import {LinearGradient} from 'expo-linear-gradient';
import {useAppTheme} from '../ui/theme';
import {useResponsiveLayout} from '../ui/glass';
import {momentWidgetSupported,disableMomentWidget,listLocalMoments,listSharedMoments,listMomentGroups,createMomentGroup,leaveMomentGroup,exportMomentRecap,shareMomentFile,configureMomentWidget,syncMomentQueue,subscribeMomentChanges,listUnclaimedMoments,claimUnclaimedMoments,listMomentRecaps,type MomentRecap,type Moment,type MomentGroup,type WidgetFilter} from '../services/moments';
import {sameLocalDate} from '../services/momentPolicy';
import {listConnections,type FriendConnection} from '../services/friendDiscovery';
import {pauseMusicPlayback} from '../services/musicPlayback';
const message=(e:unknown)=>e instanceof Error?e.message:'Chưa hoàn tất. Hãy thử lại.';
export default function MomentsScreen(){
 const {theme}=useAppTheme(),r=useResponsiveLayout();
 const loadGeneration=useRef(0),loadInFlight=useRef(false);
 const [range,setRange]=useState<0|1|7>(0),[author,setAuthor]=useState<string|null>(null),[limit,setLimit]=useState(40),[cloudError,setCloudError]=useState<string|null>(null);
 const nav=useNavigation<any>(),route=useRoute<any>(),insets=useSafeAreaInsets();
 const [tab,setTab]=useState<'mine'|'friends'|'groups'>('mine'),[local,setLocal]=useState<Moment[]>([]),[shared,setShared]=useState<Moment[]>([]),[groups,setGroups]=useState<MomentGroup[]>([]),[friends,setFriends]=useState<FriendConnection[]>([]),[group,setGroup]=useState<string|null>(route.params?.groupId??null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[modal,setModal]=useState<'group'|'widget'|null>(null),[name,setName]=useState(''),[members,setMembers]=useState<string[]>([]),[recap,setRecap]=useState(false),[selected,setSelected]=useState<string[]>([]),[exportUri,setExportUri]=useState<string|null>(null),[exports,setExports]=useState<MomentRecap[]>([]),[unclaimed,setUnclaimed]=useState(0),[widgetMode,setWidgetMode]=useState<WidgetFilter['mode']>('friends'),[widgetAuthor,setWidgetAuthor]=useState<string|undefined>(),[widgetGroup,setWidgetGroup]=useState<string|undefined>();
 const load=useCallback(async()=>{
  if(loadInFlight.current)return;
  loadInFlight.current=true;setError(null);const generation=++loadGeneration.current;
  const current=()=>generation===loadGeneration.current;
  try{
   const [own,recaps,unowned]=await Promise.all([listLocalMoments(),listMomentRecaps(),listUnclaimedMoments()]);
   if(!current())return;setLocal(own);setExports(recaps);setUnclaimed(unowned.length);setLoading(false);
   try{
    await syncMomentQueue();
    const [f,g,m,updated]=await Promise.all([listConnections(),listMomentGroups(),listSharedMoments(),listLocalMoments()]);
    if(current()){setFriends(f.filter(x=>x.relationship_status==='accepted'));setGroups(g);setShared(m);setLocal(updated);setCloudError(null);}
   }catch(e){if(current()){setShared([]);setCloudError(message(e));}}
  }catch(e){if(current())setError(message(e));}
  finally{if(current()){setLoading(false);loadInFlight.current=false;}}
 },[]);
 useFocusEffect(useCallback(()=>{loadInFlight.current=false;void load();const unsub=subscribeMomentChanges(()=>void load());return()=>{loadGeneration.current++;loadInFlight.current=false;unsub();};},[load]));
 const ownIds=new Set(local.map(m=>m.id));
 const base=tab==='mine'?[...local,...shared.filter(m=>m.isMine&&!ownIds.has(m.id))]:shared.filter(m=>tab==='groups'?!!group&&m.groupId===group:!m.isMine);
 const shown=base.filter(m=>(!range||(range===1?sameLocalDate(m.capturedAt):m.capturedAt>=Date.now()-7*86400000))&&(!author||m.ownerId===author)).sort((a,b)=>b.capturedAt-a.capturedAt);
 const people=[...new Map(shared.filter(m=>!m.isMine&&m.ownerId).map(m=>[m.ownerId!,{id:m.ownerId!,name:m.authorName||'Bạn bè',cover:m.coverUri}])).values()];
 const todayCount=base.filter(m=>sameLocalDate(m.capturedAt)).length;
 const columns=r.width>=900?3:2,contentWidth=Math.min(r.width,r.maxContent)-r.gutter-(r.isLandscape?Math.max(r.gutter,insets.left+68):r.gutter),tileWidth=(contentWidth-12*(columns-1))/columns;
 const toggle=(id:string,list:string[],update:(list:string[])=>void)=>update(list.includes(id)?list.filter(x=>x!==id):[...list,id]);
 async function action(work:()=>Promise<void>){if(busy)return;setBusy(true);setError(null);try{await work();}catch(e){setError(message(e));}finally{setBusy(false);}}
 const button=(label:string,press:()=>void,primary=false)=><Pressable accessibilityRole="button" disabled={busy} onPress={press} style={({pressed})=>[s.button,{backgroundColor:theme.colors.bgRaised},primary&&{backgroundColor:theme.colors.primary},busy&&{opacity:.5},pressed&&{transform:[{scale:.97}]}]}><Text style={[s.buttonText,primary&&{color:'#072E38'}]}>{label}</Text></Pressable>;
 async function exportVideo(){await pauseMusicPlayback();setExportUri(await exportMomentRecap(local.filter(m=>selected.includes(m.id))));setExports(await listMomentRecaps());}
 return <ScreenScaffold title="Khoảnh khắc" subtitle="Mỗi ngày một chút, gần nhau hơn" refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()} tintColor={theme.colors.primary}/>} actions={[
  ...(momentWidgetSupported?[{id:'widget',icon:'widgets-outline' as const,label:'Widget khoảnh khắc',onPress:()=>setModal('widget')}]:[]),
  {id:'friends',icon:tab==='groups'?'account-multiple-plus-outline':'account-heart-outline',label:tab==='groups'?'Tạo nhật ký nhóm':'Xem bạn bè',onPress:()=>{if(tab==='groups'){setName('');setMembers([]);setModal('group');}else{setTab('friends');setRecap(false);setAuthor(null);}}},
  {id:'camera',icon:'camera-outline',label:'Chụp khoảnh khắc',primary:true,onPress:()=>nav.navigate('MomentCamera',{purpose:'moment'})},
 ]}>
  <View style={[s.hero,{backgroundColor:theme.colors.bgRaised}]}>
   <View style={{flex:1,gap:8}}><Text style={[s.eyebrow,{color:theme.colors.primary}]}>NHẬT KÝ NHỎ CỦA CHÚNG TA</Text><Text style={[s.heroTitle,{color:theme.colors.text}]}>Hôm nay của bạn{ '\n' }có gì vui?</Text><Text style={[s.muted,{color:theme.colors.muted}]}>Ảnh và video được chia sẻ với những người bạn chọn.</Text></View>
   <View style={[s.todayCircle,{backgroundColor:theme.colors.primary+'18'}]}><Text style={[s.todayNumber,{color:theme.colors.primary}]}>{todayCount}</Text><Text style={[s.muted,{color:theme.colors.muted}]}>hôm nay</Text></View>
  </View>
  <View style={s.row}>{(['mine','friends','groups'] as const).map(t=><Pressable key={t} accessibilityRole="tab" accessibilityState={{selected:tab===t}} onPress={()=>{setTab(t);setRecap(false);setAuthor(null);setLimit(40);}} style={[s.tab,{backgroundColor:tab===t?theme.colors.primary+'24':theme.colors.bgRaised,borderColor:tab===t?theme.colors.primary:'transparent'}]}><Text style={s.buttonText}>{t==='mine'?'Của tôi':t==='friends'?'Bạn bè':'Nhật ký nhóm'}</Text></Pressable>)}</View>
  <View style={s.row}>{([0,1,7] as const).map(days=><Pressable key={days} accessibilityRole="button" accessibilityState={{selected:range===days}} onPress={()=>{setRange(days);setLimit(40);}} style={[s.filter,{borderColor:range===days?theme.colors.primary:theme.colors.border,backgroundColor:range===days?theme.colors.primary+'18':'transparent'}]}><Text style={{color:range===days?theme.colors.primary:theme.colors.muted,fontWeight:'600'}}>{days===0?'Tất cả':days===1?'Hôm nay':'7 ngày'}</Text></Pressable>)}{tab==='mine'&&button(recap?'Hủy chọn':'Tạo video',()=>{setRecap(!recap);setSelected([]);setExportUri(null);})}</View>
  {tab==='friends'&&people.length>0&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:14,paddingVertical:4}}>
   <Pressable accessibilityRole="button" accessibilityLabel="Tất cả bạn bè" onPress={()=>setAuthor(null)} style={s.person}><View style={[s.personCover,{backgroundColor:theme.colors.primary+'18',borderColor:!author?theme.colors.primary:theme.colors.border}]}><MaterialCommunityIcons name="account-group-outline" size={25} color={theme.colors.primary}/></View><Text style={s.buttonText}>Tất cả</Text></Pressable>
   {people.map(p=><Pressable key={p.id} accessibilityRole="button" accessibilityLabel={'Khoảnh khắc của '+p.name} accessibilityState={{selected:author===p.id}} onPress={()=>{setAuthor(author===p.id?null:p.id);setLimit(40);}} style={s.person}><Image source={{uri:p.cover}} style={[s.personCover,{borderColor:author===p.id?theme.colors.primary:theme.colors.border}]}/><Text numberOfLines={1} style={[s.buttonText,{maxWidth:70}]}>{p.name}</Text></Pressable>)}
  </ScrollView>}
  {cloudError&&tab!=='mine'&&<View style={[s.panel,{backgroundColor:theme.colors.bgRaised}]}><Text accessibilityRole="alert" style={s.error}>{cloudError}</Text>{button('Thử tải lại',()=>void load())}</View>}
  {tab==='mine'&&unclaimed>0&&<View style={s.panel}><Text style={s.muted}>Bạn có khoảnh khắc chụp trước khi đăng nhập trên thiết bị này.</Text>{button('Nhập khoảnh khắc vào tài khoản',()=>Alert.alert('Nhập khoảnh khắc?','Đưa các ảnh và video trước khi đăng nhập vào thư viện riêng của tài khoản hiện tại. Nội dung vẫn chỉ trên máy cho đến khi bạn chọn chia sẻ.',[{text:'Hủy',style:'cancel'},{text:'Nhập',onPress:()=>void action(async()=>{await claimUnclaimedMoments();await load();})}]))}</View>}
  {tab==='groups'&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{groups.map(g=><Pressable key={g.id} onPress={()=>setGroup(g.id)} style={[s.button,group===g.id&&s.tabActive]}><Text style={s.buttonText}>{g.name}</Text></Pressable>)}</ScrollView>}
  {tab==='groups'&&group&&<View style={{gap:10}}><Text style={s.muted}>Chỉ thành viên đang có quyền mới xem được khoảnh khắc trong nhóm.</Text>{button('Rời nhóm',()=>void action(async()=>{await leaveMomentGroup(group);setGroup(null);await load();}))}</View>}
  {recap&&<View style={s.panel}><Text style={s.heading}>Chọn tối đa 20 khoảnh khắc</Text><Text style={s.muted}>Ghép theo thời gian, có ngày giờ. Video tổng kết không kèm âm thanh.</Text><View style={s.row}>{button('Hôm nay',()=>{const d=new Date().toDateString();setSelected(local.filter(m=>new Date(m.capturedAt).toDateString()===d).slice(0,20).map(m=>m.id));})}{button('7 ngày',()=>setSelected(local.filter(m=>m.capturedAt>Date.now()-7*86400000).slice(0,20).map(m=>m.id)))}{button('Theo nhóm',()=>setSelected(local.filter(m=>!!group&&m.groupId===group).slice(0,20).map(m=>m.id)))}</View><ScrollView horizontal>{groups.map(g=><Pressable key={g.id} style={[s.button,group===g.id&&s.tabActive]} onPress={()=>{setGroup(g.id);setSelected(local.filter(m=>m.groupId===g.id).slice(0,20).map(m=>m.id));}}><Text style={s.buttonText}>{g.name}</Text></Pressable>)}</ScrollView>{button(`Xuất video (${selected.length})`,()=>void action(exportVideo),true)}{exportUri&&button('Chia sẻ video đã xuất',()=>void shareMomentFile(exportUri).catch(e=>setError(message(e))))}</View>}
  {tab==='mine'&&!recap&&exports.length>0&&<View style={s.panel}><Text style={s.heading}>Video tổng kết đã lưu</Text>{exports.slice(0,3).map(x=><Pressable key={x.uri} style={s.button} onPress={()=>void shareMomentFile(x.uri).catch(e=>setError(message(e)))}><Text style={s.buttonText}>{new Date(x.createdAt).toLocaleString()} · Chia sẻ</Text></Pressable>)}</View>}
  {loading&&<ActivityIndicator color="#64DBCF"/>}{busy&&<View style={s.row}><ActivityIndicator color="#64DBCF"/><Text style={s.muted}>Đang xử lý…</Text></View>}{error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
  {!loading&&!shown.length&&<EmptyGlass icon="camera-outline" title={tab==='mine'?'Bắt đầu bằng một khoảnh khắc':'Chưa có khoảnh khắc'} body={tab==='mine'?'Chụp ảnh hoặc quay video bằng camera MyMap. Bạn quyết định có chia sẻ hay chỉ giữ cho mình.':'Ảnh và video được bạn bè chia sẻ sẽ xuất hiện tại đây. Chọn nhóm để xem nhật ký chung.'}/>}
  <View style={s.feedHeading}><Text style={[s.heading,{color:theme.colors.text}]}>{tab==='mine'?'Nhật ký của bạn':tab==='friends'?'Từ những người thân quen':groups.find(g=>g.id===group)?.name||'Chọn nhật ký nhóm'}</Text><Text style={[s.muted,{color:theme.colors.muted}]}>{shown.length} khoảnh khắc</Text></View>
  <View style={s.grid}>{shown.slice(0,limit).map((m,index)=><Pressable key={m.id} accessibilityRole="button" accessibilityLabel={`${m.caption||'Khoảnh khắc'} ${new Date(m.capturedAt).toLocaleString()}`} onPress={()=>{if(recap){if(m.remote){setError('Lưu khoảnh khắc này trên máy trước khi đưa vào video tổng kết.');return;}if(selected.length>=20&&!selected.includes(m.id)){setError('Chọn tối đa 20 khoảnh khắc.');return;}toggle(m.id,selected,setSelected);}else nav.navigate('MomentDetail',{momentId:m.id});}} style={({pressed})=>[s.tile,{width:index===0&&!recap?contentWidth:tileWidth,aspectRatio:index===0&&!recap?1.28:.78},selected.includes(m.id)&&{borderWidth:3,borderColor:theme.colors.primary},pressed&&{opacity:.85,transform:[{scale:.985}]}]}>
   <Image source={{uri:m.coverUri}} style={s.image}/><LinearGradient pointerEvents="none" colors={['transparent','rgba(9,16,27,.18)','rgba(9,16,27,.92)']} locations={[0,.45,1]} style={StyleSheet.absoluteFill}/><View style={s.tileTop}><View style={s.authorBadge}><MaterialCommunityIcons name={m.isMine||!m.remote?'account-circle-outline':'account-heart-outline'} size={16} color="#fff"/><Text numberOfLines={1} style={s.authorText}>{m.isMine||!m.remote?'Bạn':m.authorName||'Bạn bè'}</Text></View>{m.kind==='video'&&<View style={s.badge}><MaterialCommunityIcons name="play" size={16} color="#fff"/><Text style={s.small}>{Math.round(m.durationSeconds)}s</Text></View>}{recap&&<MaterialCommunityIcons name={selected.includes(m.id)?'checkbox-marked-circle':'checkbox-blank-circle-outline'} size={28} color="#64DBCF"/>}</View>
   <View style={s.tileBottom}><Text numberOfLines={2} style={s.caption}>{m.caption||m.authorName||'Khoảnh khắc của bạn'}</Text><Text style={s.small}>{new Date(m.capturedAt).toLocaleDateString('vi-VN',{day:'numeric',month:'short'})} · {m.status==='published'?'Đã chia sẻ':m.status==='failed'?'Chưa gửi':m.status==='queued'?'Chờ gửi':'Chỉ trên máy'}</Text></View>
  </Pressable>)}</View>
  {shown.length>limit&&button('Xem thêm khoảnh khắc',()=>setLimit(v=>v+40))}
  <Modal visible={!!modal} transparent animationType="slide" onRequestClose={()=>!busy&&setModal(null)}><View style={s.modalShade}><View style={[s.modal,{paddingBottom:Math.max(insets.bottom,20)}]}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:14}}><Text style={s.heading}>{modal==='group'?'Nhật ký chung':'Widget khoảnh khắc'}</Text>
   {modal==='group'?<><TextInput value={name} onChangeText={setName} maxLength={80} placeholder="Tên nhóm hoặc chuyến đi" placeholderTextColor="#8FA9BC" style={s.input}/><Text style={s.muted}>Chọn bạn bè đã kết nối. Khoảnh khắc gửi vào nhóm sẽ chỉ dành cho thành viên.</Text>{friends.map(f=><Pressable key={f.user_id} style={s.member} onPress={()=>toggle(f.user_id,members,setMembers)}><Text style={s.buttonText}>{f.display_name}</Text><MaterialCommunityIcons name={members.includes(f.user_id)?'checkbox-marked':'checkbox-blank-outline'} size={24} color="#64DBCF"/></Pressable>)}{!friends.length&&<Text style={s.muted}>Đăng nhập và thêm bạn bè để tạo nhật ký chung.</Text>}{button('Tạo nhật ký nhóm',()=>void action(async()=>{const id=await createMomentGroup(name,members);setGroup(id);setModal(null);setTab('groups');await load();}),true)}</>:<>
    {(['friends','personal','anniversary'] as const).map(mode=><Pressable key={mode} style={s.member} onPress={()=>setWidgetMode(mode)}><Text style={s.buttonText}>{mode==='friends'?'Ảnh mới từ bạn bè':mode==='personal'?'Khoảnh khắc gần nhất của tôi':'Ngày này năm xưa'}</Text><MaterialCommunityIcons name={mode===widgetMode?'radiobox-marked':'radiobox-blank'} size={24} color="#64DBCF"/></Pressable>)}
    {widgetMode==='friends'&&<><Text style={s.muted}>Chọn một người bạn hoặc nhóm; bỏ chọn để xem tất cả.</Text>{friends.map(f=><Pressable key={f.user_id} style={s.member} onPress={()=>{setWidgetAuthor(widgetAuthor===f.user_id?undefined:f.user_id);setWidgetGroup(undefined);}}><Text style={s.buttonText}>{f.display_name}</Text><MaterialCommunityIcons name={widgetAuthor===f.user_id?'checkbox-marked':'checkbox-blank-outline'} size={24} color="#64DBCF"/></Pressable>)}{groups.map(g=><Pressable key={g.id} style={s.member} onPress={()=>{setWidgetGroup(widgetGroup===g.id?undefined:g.id);setWidgetAuthor(undefined);}}><Text style={s.buttonText}>{g.name}</Text><MaterialCommunityIcons name={widgetGroup===g.id?'checkbox-marked':'checkbox-blank-outline'} size={24} color="#64DBCF"/></Pressable>)}</>}
    <Text style={s.muted}>Widget cập nhật khi mở MyMap. Ảnh bạn bè tự ẩn sau 15 phút nếu chưa được cập nhật. Bạn phải tự thêm widget từ màn hình chính iOS.</Text>{button('Thêm widget màn hình chính',()=>void action(async()=>{const result=await configureMomentWidget({mode:widgetMode,author:widgetAuthor,group:widgetGroup});if(!result)Alert.alert('Thêm widget','Nhấn giữ màn hình chính → Sửa → Thêm tiện ích → MyMap.');setModal(null);}),true)}
   </>}{modal==='widget'&&button('Tắt widget và xóa ảnh chia sẻ',()=>void action(async()=>{await disableMomentWidget();setModal(null);} ))}{button('Đóng',()=>setModal(null))}{error&&<Text style={s.error}>{error}</Text>}
  </ScrollView></View></View></Modal>
 </ScreenScaffold>;
}
const s=StyleSheet.create({hero:{padding:22,borderRadius:28,flexDirection:'row',alignItems:'center',gap:14},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:.9},heroTitle:{fontSize:30,lineHeight:35,fontWeight:'800',letterSpacing:-.8},todayCircle:{width:78,height:92,borderRadius:28,alignItems:'center',justifyContent:'center',gap:2},todayNumber:{fontSize:32,fontWeight:'800',fontVariant:['tabular-nums']},filter:{minHeight:44,paddingHorizontal:15,borderWidth:1,borderRadius:22,justifyContent:'center'},person:{alignItems:'center',gap:7,width:70},personCover:{width:62,height:62,borderRadius:24,borderWidth:2,alignItems:'center',justifyContent:'center'},feedHeading:{gap:5,paddingTop:8},authorBadge:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:'#10253BCC',padding:8,borderRadius:18,maxWidth:'80%'},authorText:{color:'#fff',fontSize:11,fontWeight:'700',flexShrink:1},row:{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'},tab:{flex:1,borderWidth:1,padding:12,borderRadius:20,alignItems:'center',backgroundColor:'#183046',minHeight:48},tabActive:{backgroundColor:'#365B6B'},button:{backgroundColor:'#20394E',paddingHorizontal:14,paddingVertical:13,borderRadius:17,minHeight:48,alignItems:'center'},primary:{backgroundColor:'#64DBCF'},buttonText:{color:'#F1F8FF',fontSize:13,fontWeight:'700'},panel:{padding:16,borderRadius:24,backgroundColor:'#172D43',gap:12},heading:{color:'#fff',fontSize:21,fontWeight:'700'},muted:{color:'#A5BDD0',fontSize:13,lineHeight:20},error:{color:'#FFACB8',fontSize:13,lineHeight:20},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,paddingBottom:60},tile:{aspectRatio:.78,borderRadius:24,overflow:'hidden',backgroundColor:'#233E53'},image:{width:'100%',height:'100%'},tileTop:{position:'absolute',top:12,left:12,right:12,flexDirection:'row',justifyContent:'space-between'},badge:{flexDirection:'row',backgroundColor:'#092238CC',borderRadius:14,padding:6},tileBottom:{position:'absolute',bottom:0,left:0,right:0,padding:12,backgroundColor:'transparent',gap:5},caption:{color:'#fff',fontSize:14,fontWeight:'700'},small:{color:'#CEE0F0',fontSize:10},fab:{position:'absolute',right:20,width:60,height:60,borderRadius:30,backgroundColor:'#64DBCF',alignItems:'center',justifyContent:'center',zIndex:10,elevation:8},modalShade:{flex:1,backgroundColor:'#0008',justifyContent:'flex-end'},modal:{maxHeight:'85%',backgroundColor:'#10253B',padding:22,borderTopLeftRadius:28,borderTopRightRadius:28},input:{backgroundColor:'#20394E',color:'#fff',padding:16,borderRadius:16,fontSize:16},member:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:12,minHeight:48}});
