import {TextInput} from '../ui/TextInput';
import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{ActivityIndicator,Image,Modal,Pressable,StyleSheet,View}from'react-native';
import{useFocusEffect,useNavigation}from'@react-navigation/native';
import{MaterialCommunityIcons}from'@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import * as FileSystem from 'expo-file-system/legacy';
import{getPhotoPins}from'../db/database';
import{getCurrentUser,signOutUser,subscribeAuthState}from'../services/auth';
import{getLocalProfile,saveLocalProfile,type LocalProfile}from'../services/localProfile';
import{prepareProfileAvatar}from'../services/profileAvatars';
import{getSavedPlaces,type SavedPlace}from'../services/placeMetadata';
import{localDayKey}from'../utils/journeyStats';
import{dailyObservedHistory,type ObservedDay}from'../services/observedHistory';
import{GlassButton,GlassSurface,IconBadge,glassColors,useResponsiveLayout}from'../ui/glass';
import{ScreenScaffold,EmptyGlass,SectionTitle}from'../ui/ScreenScaffold';
import{Text}from'../ui/Text';
import{NativeAdCard}from'../components/NativeAdCard';
import type{PhotoPin}from'../types/photo';import type{User}from'@supabase/supabase-js';

export default function ProfileScreen(){
 const nav=useNavigation<any>();const r=useResponsiveLayout();const mutation=useRef(false),generation=useRef(0);
 const[daysObserved,setDaysObserved]=useState<ObservedDay[]>([]),[photos,setPhotos]=useState<PhotoPin[]>([]),[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<LocalProfile>({name:'',bio:'',avatarUri:null}),[favorites,setFavorites]=useState<SavedPlace[]>([]);
 const[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[editor,setEditor]=useState(false),[draft,setDraft]=useState<LocalProfile>(profile),[busy,setBusy]=useState(false),[logout,setLogout]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let owner:string|undefined;return subscribeAuthState((_event,session)=>{const next=session?.user.id||'local';if(owner!==undefined&&owner!==next){generation.current++;setUser(null);setProfile({name:'',bio:'',avatarUri:null});setFavorites([]);setEditor(false);setDraft({name:'',bio:'',avatarUri:null});setLoading(true);setRetry(v=>v+1);}owner=next;});},[]);
 useFocusEffect(useCallback(()=>{let active=true;void Promise.all([dailyObservedHistory(),getPhotoPins(),getCurrentUser(),getLocalProfile(),getSavedPlaces()]).then(([p,m,u,local,places])=>{if(!active)return;setDaysObserved(p);setPhotos(m);setUser(u);setProfile(local);setFavorites(places.filter(x=>x.favorite));setError(null);}).catch(()=>{if(active)setError('Không thể đọc hồ sơ trên thiết bị.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;generation.current++;};},[retry]));
 const stats=useMemo(()=>{
  const days=[...new Set([...daysObserved.map(d=>d.day),...photos.map(p=>localDayKey(p.capturedAt))])].sort();
  let streak=0;const cursor=new Date();cursor.setHours(12,0,0,0);if(!days.includes(localDayKey(cursor.getTime())))cursor.setDate(cursor.getDate()-1);
  while(days.includes(localDayKey(cursor.getTime()))){streak++;cursor.setDate(cursor.getDate()-1);}
  const record=daysObserved.reduce((max,d)=>Math.max(max,d.distanceMeters),0);
  return{distance:daysObserved.reduce((sum,d)=>sum+d.distanceMeters,0),days:days.length,visits:daysObserved.reduce((sum,d)=>sum+d.visits,0),countries:new Set(photos.map(p=>p.countryCode).filter(Boolean)).size,places:new Set(photos.map(p=>p.placeName).filter(Boolean)).size,streak,record};
 },[daysObserved,photos]);
 const week=useMemo(()=>{const start=new Date();start.setHours(12,0,0,0);start.setDate(start.getDate()-(start.getDay()+6)%7);const groups=new Map(daysObserved.map(d=>[d.day,d.distanceMeters]));return Array.from({length:7},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return{label:i===6?'CN':`T${i+2}`,km:(groups.get(localDayKey(date.getTime()))||0)/1000};});},[daysObserved]);
 const maxWeek=Math.max(1,...week.map(x=>x.km));
 const name=profile.name||user?.user_metadata?.name||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Hồ sơ của bạn';
 const avatar=profile.avatarUri||user?.user_metadata?.avatar_url;
 async function save(){if(mutation.current)return;mutation.current=true;setBusy(true);const token=generation.current;try{const next={...draft,name:draft.name.trim(),bio:draft.bio.trim()};const result=await saveLocalProfile(next,user?.id||'local');if(token!==generation.current)return;setProfile(next);setEditor(false);setError(result.synced?null:'Đã lưu trên máy. Hồ sơ và ảnh đại diện đang chờ đồng bộ khi có mạng.');}catch(e){if(token===generation.current)setError((e as Error).message||'Không thể lưu hồ sơ. Hãy thử lại.');}finally{mutation.current=false;setBusy(false);}}
 async function chooseAvatar(){if(busy)return;const token=generation.current;try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.7});if(result.canceled||token!==generation.current)return;const destination=await prepareProfileAvatar(result.assets[0]!.uri);if(token!==generation.current){await FileSystem.deleteAsync(destination,{idempotent:true});return;}setDraft(v=>({...v,avatarUri:destination}));}catch{setError('Không thể chọn ảnh hồ sơ.');}}
 return <ScreenScaffold title="Cá nhân" actions={[
  {id:'settings',icon:'cog-outline',label:'Cài đặt',onPress:()=>nav.navigate('Settings')},
  {id:'moments',icon:'camera-outline',label:'Khoảnh khắc',onPress:()=>nav.navigate('Moments')},
  {id:'edit',icon:'pencil-outline',label:'Sửa hồ sơ',primary:true,onPress:()=>{setDraft(profile);setEditor(true);}},
 ]}>
  <GlassSurface style={s.profile}>
   <View style={s.profileTop}><View style={s.avatar}>{avatar?<Image source={{uri:avatar}} style={s.avatarImage}/>:<MaterialCommunityIcons name="account-outline" size={47} color="#B5DDFF"/>}</View><View style={s.identity}><Text style={s.name}>{name}</Text><Text style={s.bio}>{profile.bio||'Thêm một vài dòng giới thiệu về bạn'}</Text><Text style={s.muted}>{user?.email||'Lưu hành trình trên thiết bị'}</Text></View></View>
   <View style={s.profileActions}><GlassButton tone="neutral" onPress={()=>{setDraft(profile);setEditor(true);}}><Text style={s.white}>Chỉnh sửa hồ sơ</Text></GlassButton><GlassButton tone={user?'neutral':'blue'} onPress={()=>user?setLogout(true):nav.navigate('Login')}><Text style={s.white}>{user?'Đăng xuất':'Đăng nhập'}</Text></GlassButton></View>
  </GlassSurface>
  {loading&&<ActivityIndicator color={glassColors.cyan}/>}
  {error&&<EmptyGlass title="Chưa thể hoàn tất" body={error} action={<GlassButton onPress={()=>setRetry(v=>v+1)}><Text style={s.white}>Thử lại</Text></GlassButton>}/>}
  <View style={s.metrics}>{[
   {icon:'map-marker-distance' as const,value:`${(stats.distance/1000).toLocaleString('vi-VN',{maximumFractionDigits:1})}`,label:'km hành trình đã lưu'},
   {icon:'map-marker' as const,value:stats.visits,label:'Địa điểm đã đến'}, {icon:'calendar-month' as const,value:stats.days,label:'Ngày khám phá'},
   {icon:'image' as const,value:photos.length,label:'Kỷ niệm đã lưu'}, {icon:'earth' as const,value:stats.countries,label:'Quốc gia từ ảnh'}, {icon:'city-variant-outline' as const,value:stats.places,label:'Địa điểm có tên'},
  ].map((m,i)=><GlassSurface key={m.label} style={[s.metric,{width:r.width<360||r.fontScale>1.2?'48%':'31.5%'}]}><IconBadge name={m.icon} tone={i%3===2?'violet':'cyan'} size={24}/><Text style={s.metricValue}>{loading?'—':m.value}</Text><Text style={s.metricLabel}>{m.label}</Text></GlassSurface>)}</View>
  <View style={[s.insights,r.width>=390&&r.fontScale<=1.2&&s.row]}>
   <GlassSurface style={s.insight}><Text style={s.cardTitle}>Hoạt động trong tuần</Text><Text style={s.muted}>Quãng đường GPS · km</Text><View style={s.chart}>{week.map((day,i)=><View key={day.label} style={s.barCol}><View style={s.barTrack}><View style={[s.bar,{height:day.km/maxWeek*102,backgroundColor:i%2?glassColors.purple:glassColors.cyan}]}/></View><Text style={s.barValue}>{day.km ? day.km.toFixed(1) : '0'}</Text><Text style={s.barLabel}>{day.label}</Text></View>)}</View></GlassSurface>
   <GlassSurface tone="violet" style={s.insight}><Text style={s.cardTitle}>Địa điểm yêu thích</Text>{favorites.length?favorites.slice(0,5).map((place,i)=><Pressable accessibilityRole="button" key={place.key} onPress={()=>nav.navigate('PlaceDetail',place)} style={s.favorite}><Text style={s.rank}>{i+1}</Text><Text numberOfLines={2} style={s.favoriteName}>{place.name}</Text><MaterialCommunityIcons name="heart" size={18} color="#F69BDB"/></Pressable>):<View style={s.emptyFavorite}><MaterialCommunityIcons name="heart-outline" size={28} color={glassColors.purple}/><Text style={s.muted}>Lưu một địa điểm yêu thích từ chi tiết kỷ niệm.</Text></View>}</GlassSurface>
  </View>
  <View style={[s.insights,r.width>=390&&r.fontScale<=1.2&&s.row]}><GlassSurface tone="cyan" style={s.achievement}><IconBadge name="fire" tone="rose"/><View style={s.flex}><Text style={s.muted}>Chuỗi ngày khám phá</Text><Text style={s.achievementValue}>{loading?'—':stats.streak} ngày liên tiếp</Text></View></GlassSurface><GlassSurface tone="violet" style={s.achievement}><IconBadge name="trophy" tone="violet"/><View style={s.flex}><Text style={s.muted}>Kỷ lục cá nhân</Text><Text style={s.achievementValue}>{loading?'—':(stats.record/1000).toFixed(1)} km</Text><Text style={s.muted}>Trong một ngày</Text></View></GlassSurface></View>
  <View style={s.quick}><GlassButton style={s.flex} onPress={()=>nav.navigate('Heatmap')}><Text style={s.white}>Heatmap</Text></GlassButton><GlassButton style={s.flex} tone="purple" onPress={()=>nav.navigate('Smart')}><Text style={s.white}>Smart</Text></GlassButton><GlassButton style={s.flex} tone="red" onPress={()=>nav.navigate('SOS')}><Text style={s.white}>SOS khẩn cấp</Text></GlassButton></View>
  <Pressable accessibilityRole="button" accessibilityLabel="Mở cài đặt" onPress={()=>nav.navigate('Settings')}><GlassSurface style={s.menuRow}><IconBadge name="cog-outline" size={23}/><View style={s.flex}><Text style={s.menuTitle}>Cài đặt</Text><Text style={s.muted}>Quyền riêng tư, dữ liệu, ngôn ngữ và thiết bị</Text></View><MaterialCommunityIcons name="chevron-right" size={24} color={glassColors.muted}/></GlassSurface></Pressable>
  <NativeAdCard placement="profile"/>
  <Modal visible={editor} transparent animationType="fade" onRequestClose={()=>{if(!busy)setEditor(false);}}><View style={s.overlay}><GlassSurface style={s.dialog}><Text style={s.name}>Chỉnh sửa hồ sơ</Text><Text style={s.muted}>Hồ sơ được lưu trên máy và đồng bộ với tài khoản khi có mạng. Ảnh chỉ chia sẻ theo quyền hồ sơ của bạn.</Text><Pressable accessibilityRole="button" accessibilityLabel="Chọn ảnh đại diện" onPress={()=>void chooseAvatar()} style={s.chooseAvatar}>{draft.avatarUri?<Image source={{uri:draft.avatarUri}} style={s.draftAvatar}/>:<IconBadge name="camera-plus-outline"/>}<Text style={s.white}>Chọn ảnh đại diện</Text></Pressable><TextInput accessibilityLabel="Tên hiển thị" value={draft.name} onChangeText={name=>setDraft(v=>({...v,name}))} style={s.input} placeholder="Tên hiển thị" placeholderTextColor={glassColors.faint} maxLength={100} editable={!busy}/><TextInput accessibilityLabel="Giới thiệu" value={draft.bio} onChangeText={bio=>setDraft(v=>({...v,bio}))} style={[s.input,{minHeight:85}]} placeholder="Một chút về bạn…" placeholderTextColor={glassColors.faint} maxLength={500} multiline editable={!busy}/><View style={s.quick}><GlassButton style={s.flex} tone="neutral" disabled={busy} onPress={()=>setEditor(false)}><Text style={s.white}>Hủy</Text></GlassButton><GlassButton style={s.flex} disabled={busy} onPress={()=>void save()}><Text style={s.white}>{busy?'Đang lưu…':'Lưu hồ sơ'}</Text></GlassButton></View></GlassSurface></View></Modal>
  <Modal visible={logout} transparent animationType="fade" onRequestClose={()=>{if(!busy)setLogout(false);}}><View style={s.overlay}><GlassSurface style={s.dialog}><Text style={s.name}>Đăng xuất?</Text><Text style={s.muted}>Hành trình và kỷ niệm trên thiết bị vẫn được giữ lại.</Text><View style={s.quick}><GlassButton style={s.flex} tone="neutral" onPress={()=>setLogout(false)} disabled={busy}><Text style={s.white}>Hủy</Text></GlassButton><GlassButton style={s.flex} tone="red" disabled={busy} onPress={()=>{if(mutation.current)return;mutation.current=true;setBusy(true);void signOutUser().then(()=>{setUser(null);setLogout(false);}).catch(()=>setError('Không thể đăng xuất.')).finally(()=>{mutation.current=false;setBusy(false);});}}><Text style={s.white}>Đăng xuất</Text></GlassButton></View></GlassSurface></View></Modal>
 </ScreenScaffold>;
}
const s=StyleSheet.create({profile:{padding:24,gap:20,borderRadius:30},profileTop:{gap:16,alignItems:'center'},avatar:{width:106,height:106,borderRadius:53,borderWidth:4,borderColor:glassColors.border,backgroundColor:glassColors.bgRaised,alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImage:{width:98,height:98},identity:{gap:6,alignItems:'center'},name:{fontSize:27,fontWeight:'800',color:'#fff',textAlign:'center',letterSpacing:-.7},bio:{color:glassColors.muted,fontSize:14,lineHeight:21,textAlign:'center'},muted:{fontSize:11,color:glassColors.muted,lineHeight:16},profileActions:{flexDirection:'row',justifyContent:'space-between',gap:8},white:{fontSize:12,fontWeight:'700',color:'#fff'},metrics:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:9},metric:{padding:12,alignItems:'center',gap:6,minHeight:105},metricValue:{color:'#fff',fontSize:27,lineHeight:32,fontWeight:'800',fontVariant:['tabular-nums']},metricLabel:{fontSize:11,color:glassColors.muted,textAlign:'center',lineHeight:16},insights:{gap:10},row:{flexDirection:'row'},insight:{flex:1,padding:12,gap:7},cardTitle:{fontSize:14,fontWeight:'800',color:'#fff'},chart:{height:143,flexDirection:'row',alignItems:'flex-end',gap:5},barCol:{flex:1,alignItems:'center',gap:2},barTrack:{height:103,justifyContent:'flex-end',width:'100%',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#6D99CA'},bar:{width:'80%',borderTopLeftRadius:6,borderTopRightRadius:6,borderWidth:1,borderColor:'#BAE4FF'},barValue:{color:'#C8E0FF',fontSize:8},barLabel:{color:'#B2CDEF',fontSize:9},emptyFavorite:{minHeight:138,justifyContent:'center',alignItems:'center',gap:11},favorite:{minHeight:40,flexDirection:'row',alignItems:'center',gap:8,paddingVertical:6,borderBottomWidth:1,borderBottomColor:'rgba(127,178,243,.19)'},rank:{width:22,height:22,borderRadius:11,backgroundColor:'#2C5B9E',color:'#D3E9FF',textAlign:'center'},favoriteName:{flex:1,fontSize:12,color:'#fff'},achievement:{flex:1,padding:14,flexDirection:'row',alignItems:'center',gap:10},achievementValue:{color:'#fff',fontSize:17,fontWeight:'800',lineHeight:23,marginTop:4},flex:{flex:1},quick:{flexDirection:'row',gap:10},menuRow:{minHeight:69,padding:12,flexDirection:'row',gap:12,alignItems:'center'},border:{borderTopWidth:1,borderTopColor:'rgba(139,194,246,.22)'},menuTitle:{fontSize:14,fontWeight:'700',color:'#fff'},overlay:{flex:1,padding:22,backgroundColor:'rgba(2,9,31,.85)',justifyContent:'center'},dialog:{padding:20,gap:13,width:'100%',maxWidth:540,alignSelf:'center'},input:{minHeight:49,borderWidth:1,borderColor:glassColors.border,borderRadius:14,padding:12,color:'#fff',backgroundColor:'rgba(0,0,0,.16)'},chooseAvatar:{flexDirection:'row',alignItems:'center',gap:12,minHeight:56},draftAvatar:{width:55,height:55,borderRadius:28}});
