import {TextInput} from '../ui/TextInput';
import React,{useCallback,useEffect,useRef,useState}from'react';
import{ActivityIndicator,Modal,Pressable,StyleSheet,Switch,View}from'react-native';
import{useFocusEffect,useNavigation}from'@react-navigation/native';
import{MaterialCommunityIcons}from'@expo/vector-icons';
import{checkIn,createPlaceAlert,listPlaceAlerts,createEtaShare}from'../services/smartFeatures';
import{isTracking,startTracking,stopTracking}from'../services/locationTracking';
import{startIncidentDetection,stopIncidentDetection,resolveIncident,type SafetyIncident}from'../services/incidentDetection';
import{syncGeofences}from'../services/geofencing';
import{getLocationPoints}from'../db/database';
import{fetchWeather,type WeatherSnapshot}from'../services/weather';
import{getCurrentSession}from'../services/auth';
import{getSavedPlaces,type SavedPlace}from'../services/placeMetadata';
import{GlassButton,GlassChip,GlassSurface,IconBadge,ScreenQuote,glassColors,useResponsiveLayout,type IconName}from'../ui/glass';
import{ScreenScaffold,SectionTitle,EmptyGlass}from'../ui/ScreenScaffold';
import{WeatherCard}from'../ui/WeatherCard';
import{Text}from'../ui/Text';
import{NativeAdCard}from'../components/NativeAdCard';
import{LinearGradient}from'expo-linear-gradient';
import{supabase}from'../services/supabase';

type Contact={id:string;name:string;contact_user_id:string|null};
export default function SmartScreen(){
 const nav=useNavigation<any>();const r=useResponsiveLayout();const pending=useRef(false);const latestIncident=useRef<SafetyIncident|null>(null);
 const[tracking,setTracking]=useState(false),[safety,setSafety]=useState(false),[alerts,setAlerts]=useState<any[]>([]),[weather,setWeather]=useState<WeatherSnapshot|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[status,setStatus]=useState<string|null>(null),[signedIn,setSignedIn]=useState(false);
 const[incident,setIncident]=useState<SafetyIncident|null>(null),[countdown,setCountdown]=useState(15),[sheet,setSheet]=useState<'alert'|'eta'|null>(null),[label,setLabel]=useState(''),[radius,setRadius]=useState(300),[contacts,setContacts]=useState<Contact[]>([]),[savedPlaces,setSavedPlaces]=useState<SavedPlace[]>([]),[target,setTarget]=useState<string|null>(null),[destination,setDestination]=useState<SavedPlace|null>(null),[etaTime,setEtaTime]=useState('');
 useFocusEffect(useCallback(()=>{let active=true;void Promise.all([isTracking(),getLocationPoints(1),getCurrentSession(),getSavedPlaces()]).then(async([t,pts,session,places])=>{if(!active)return;setTracking(t);setSignedIn(!!session);setSavedPlaces(places);setAlerts([]);setContacts([]);if(session){const results=await Promise.allSettled([listPlaceAlerts(true),supabase.from('vc_trusted_contacts').select('id,name,contact_user_id')]);if(!active)return;if(results[0].status==='fulfilled')setAlerts(results[0].value);else setError('Chưa tải được cảnh báo địa điểm từ tài khoản.');if(results[1].status==='fulfilled'&&!results[1].value.error)setContacts((results[1].value.data||[])as Contact[]);}const p=pts[0];if(p){try{const w=await fetchWeather(p.latitude,p.longitude);if(active)setWeather(w);}catch{if(active)setWeather(null);}}}).catch(()=>{if(active)setError('Không thể đọc trạng thái công cụ.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]));
 useEffect(()=>()=>{void stopIncidentDetection().catch(()=>{});},[]);
 useEffect(()=>{latestIncident.current=incident;if(!incident)return;setCountdown(15);const timer=setInterval(()=>setCountdown(n=>Math.max(0,n-1)),1000);const timeout=setTimeout(()=>void openIncidentSOS(),15000);return()=>{clearInterval(timer);clearTimeout(timeout);};},[incident]);
 async function action(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError(null);setStatus(null);try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{pending.current=false;setBusy(false);}}
 async function openIncidentSOS(){const value=latestIncident.current;if(!value)return;latestIncident.current=null;setIncident(null);await resolveIncident(value.id,'sos_triggered').catch(()=>{});nav.navigate('SOS');}
 async function dismissIncident(){const value=latestIncident.current;if(!value)return;await resolveIncident(value.id,'dismissed');latestIncident.current=null;setIncident(null);}
 function checkLogin(){if(!signedIn)throw new Error('Đăng nhập để sử dụng chức năng kết nối người thân.');}
 function toggleTracking(){void action(async()=>{if(tracking)await stopTracking();else await startTracking();setTracking(await isTracking());});}
 function toggleSafety(){void action(async()=>{if(safety){await stopIncidentDetection();setSafety(false);}else{await startIncidentDetection(setIncident);setSafety(true);}});}
 function createAlert(){void action(async()=>{checkLogin();if(!label.trim())throw new Error('Nhập tên địa điểm.');await createPlaceAlert(label.trim(),radius,true,true);setAlerts(await listPlaceAlerts(true));setStatus(`Đã tạo cảnh báo ${radius} m tại vị trí hiện tại.`);setSheet(null);});}
 function sendEta(){void action(async()=>{checkLogin();if(!target||!destination)throw new Error('Chọn người thân và địa điểm đã lưu.');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(etaTime))throw new Error('Nhập giờ đến theo định dạng HH:MM.');const time=new Date();const[h,m]=etaTime.split(':').map(Number);time.setHours(h!,m!,0,0);if(time.getTime()<=Date.now())throw new Error('Giờ đến phải sau thời điểm hiện tại trong ngày hôm nay.');await createEtaShare(target,{label:destination.name,latitude:destination.latitude,longitude:destination.longitude},time.toISOString());setStatus('Đã lưu ETA chia sẻ với người thân bạn chọn.');setSheet(null);});}
 const tools:{title:string;body:string;icon:IconName;tone:'cyan'|'violet'|'rose';onPress:()=>void}[]=[
  {title:'Check-in an toàn',body:'Chia sẻ trạng thái đến nơi với người thân',icon:'shield-check',tone:'cyan',onPress:()=>void action(async()=>{checkLogin();await checkIn('Tôi đã đến nơi an toàn');setStatus('Đã lưu check-in an toàn cho người thân.');})},
  {title:'Nhắc khi đến/rời',body:'Nhận thông báo khi đến hoặc rời địa điểm',icon:'bell-ring',tone:'violet',onPress:()=>{setLabel('');setSheet('alert');}},
  {title:'ETA Sharing',body:'Chia sẻ giờ đến do bạn chọn với người thân',icon:'account-group',tone:'cyan',onPress:()=>setSheet('eta')},
  {title:'Crash/Fall Detection',body:safety?'Cảm biến đang bật':'Nhận diện chuyển động va chạm hoặc té ngã',icon:'shield-plus',tone:'rose',onPress:toggleSafety},
 ];
 return <ScreenScaffold title="MyMap Smart" hideTitle>
  <WeatherCard weather={weather}/><ScreenQuote text="Công nghệ kết nối những người bạn quan tâm"/>
  <SectionTitle action={<Pressable onPress={()=>nav.navigate('Settings')} style={s.link}><Text style={s.linkText}>Tìm hiểu thêm →</Text></Pressable>}>Công cụ thông minh</SectionTitle><Text style={s.subtitle}>Dành cho hành trình an toàn và kết nối hơn</Text>
  {loading&&<ActivityIndicator color={glassColors.cyan}/>} {error&&<EmptyGlass icon="alert-circle-outline" title="Chưa thể hoàn tất" body={error} action={!signedIn?<GlassButton onPress={()=>nav.navigate('Login')}><Text style={s.white}>Đăng nhập</Text></GlassButton>:undefined}/>} {status&&<GlassSurface tone="mint" style={s.status}><Text style={s.statusText}>{status}</Text></GlassSurface>}
  <View style={s.tools}>{tools.map(tool=><Pressable key={tool.title} accessibilityRole="button" disabled={busy||loading} style={{width:r.width<360&&r.fontScale>1.2?'100%':'48.6%'}} onPress={tool.onPress}><GlassSurface tone={tool.tone} style={s.tool}><IconBadge name={tool.icon} tone={tool.tone} size={28}/><View style={s.toolCopy}><View style={s.titleRow}><Text style={s.toolTitle}>{tool.title}</Text><MaterialCommunityIcons name="chevron-right" size={19} color="#B1D7FF"/></View><Text style={s.toolBody}>{tool.body}</Text>{tool.title==='Crash/Fall Detection'&&<Text style={[s.sensorState,{color:safety?glassColors.green:glassColors.muted}]}>{safety?'Đang bật':'Đang tắt'}</Text>}</View></GlassSurface></Pressable>)}</View>
  <Pressable accessibilityRole="button" accessibilityLabel={tracking?'Dừng ghi hành trình':'Bắt đầu ghi hành trình'} disabled={busy||loading} onPress={toggleTracking}><GlassSurface tone="violet" style={s.tracking}><IconBadge name="navigation-variant" tone="violet" size={32}/><View style={s.flex}><View style={s.titleRow}><Text style={s.trackingTitle}>Tracking</Text><Text style={[s.trackingState,{color:tracking?glassColors.green:glassColors.muted}]}>{tracking?'Đang ghi':'Đã dừng'}</Text></View><Text style={s.toolBody}>Theo dõi hành trình theo thời gian thực và xem lại lịch sử di chuyển</Text></View></GlassSurface></Pressable>
  <SectionTitle action={<Pressable accessibilityRole="button" onPress={()=>{setLabel('');setSheet('alert');}} style={s.link}><Text style={s.linkText}>Thêm mới +</Text></Pressable>}>Cảnh báo địa điểm</SectionTitle><Text style={s.subtitle}>{alerts.filter(a=>a.is_enabled).length} vùng đang bật</Text>
  {!alerts.length?<EmptyGlass icon="map-marker-radius-outline" title="Chưa có cảnh báo địa điểm" body="Tạo một vùng nhắc tại vị trí hiện tại và đặt tên dễ nhớ." action={<GlassButton onPress={()=>setSheet('alert')}><Text style={s.white}>Tạo cảnh báo đầu tiên</Text></GlassButton>}/>:<GlassSurface>{alerts.map((item,i)=><View key={item.id} style={[s.alertRow,i>0&&s.border]}><IconBadge name={item.label?.toLowerCase().includes('nhà')?'home':item.label?.toLowerCase().includes('công ty')?'briefcase':'map-marker'}/><View style={s.flex}><Text style={s.alertTitle}>{item.label||'Địa điểm đã lưu'}</Text><Text style={s.toolBody}>Bán kính {item.radius_m!=null?`${item.radius_m} m`:'chưa rõ'}</Text></View><Switch accessibilityLabel={`Cảnh báo ${item.label}`} disabled={busy} value={Boolean(item.is_enabled)} onValueChange={value=>void action(async()=>{const{error}=await supabase.from('vc_place_alerts').update({is_enabled:value}).eq('id',item.id);if(error)throw error;setAlerts(v=>v.map(a=>a.id===item.id?{...a,is_enabled:value}:a));await syncGeofences();})} trackColor={{false:'#49648E',true:'#13B5ED'}} thumbColor="#F5FBFF"/></View>)}</GlassSurface>}
  <NativeAdCard placement="smart"/>
  <Modal visible={!!sheet} transparent animationType="fade" onRequestClose={()=>{if(!busy)setSheet(null);}}><View style={s.overlay}><GlassSurface style={s.dialog}><Text style={s.dialogTitle}>{sheet==='alert'?'Nhắc khi đến/rời':'Chia sẻ ETA'}</Text>{sheet==='alert'?<><Text style={s.toolBody}>Tạo vùng cảnh báo quanh vị trí hiện tại của bạn.</Text><TextInput accessibilityLabel="Tên cảnh báo địa điểm" value={label} onChangeText={setLabel} style={s.input} placeholder="Tên địa điểm" placeholderTextColor={glassColors.faint} editable={!busy} maxLength={100}/><View style={s.choices}>{[300,500,1000].map(value=><GlassChip key={value} label={value===1000?'1 km':`${value} m`} active={radius===value} onPress={()=>setRadius(value)}/>)}</View></>:<><Text style={s.toolBody}>Chọn người thân có tài khoản MyMap và một địa điểm đã lưu.</Text><View style={s.choices}>{contacts.filter(c=>c.contact_user_id).map(c=><GlassChip key={c.id} label={c.name} active={target===c.contact_user_id} onPress={()=>setTarget(c.contact_user_id)}/>)}</View>{!contacts.some(c=>c.contact_user_id)&&<Text style={s.toolBody}>Chưa có người thân liên kết tài khoản. Bạn cần thêm người thân có tài khoản để chia sẻ ETA.</Text>}<View style={s.choices}>{savedPlaces.map(place=><GlassChip key={place.key} label={place.name} active={destination?.key===place.key} onPress={()=>setDestination(place)}/>)}</View>{!savedPlaces.length&&<Text style={s.toolBody}>Lưu một địa điểm từ chi tiết kỷ niệm để chọn điểm đến.</Text>}<TextInput accessibilityLabel="Giờ đến dự kiến" value={etaTime} onChangeText={setEtaTime} style={s.input} placeholder="Giờ đến hôm nay · HH:MM" placeholderTextColor={glassColors.faint} keyboardType="numbers-and-punctuation" maxLength={5} editable={!busy}/></>}{error&&<Text style={s.sheetError}>{error}</Text>}<View style={s.choices}><GlassButton style={s.flex} tone="neutral" disabled={busy} onPress={()=>setSheet(null)}><Text style={s.white}>Hủy</Text></GlassButton><GlassButton style={s.flex} disabled={busy||!signedIn||(sheet==='eta'&&(!target||!destination))} onPress={sheet==='alert'?createAlert:sendEta}><Text style={s.white}>{busy?'Đang lưu…':'Lưu'}</Text></GlassButton></View>{!signedIn&&<GlassButton onPress={()=>{setSheet(null);nav.navigate('Login');}}><Text style={s.white}>Đăng nhập</Text></GlassButton>}</GlassSurface></View></Modal>
  <Modal visible={!!incident} transparent animationType="fade" onRequestClose={()=>{}}><View style={s.overlay}><GlassSurface tone="rose" style={s.dialog}><IconBadge name="alarm-light" tone="rose" size={35}/><Text style={s.dialogTitle}>MyMap Safety</Text><Text style={s.toolBody}>Phát hiện chuyển động bất thường. Màn hình SOS sẽ mở sau {countdown} giây để bạn chọn hành động.</Text><GlassButton tone="neutral" onPress={()=>void action(dismissIncident)}><Text style={s.white}>Tôi ổn · Đóng cảnh báo</Text></GlassButton><GlassButton tone="red" onPress={()=>void openIncidentSOS()}><Text style={s.white}>Mở SOS ngay</Text></GlassButton></GlassSurface></View></Modal>
 </ScreenScaffold>;
}
const s=StyleSheet.create({subtitle:{fontSize:12,lineHeight:18,color:glassColors.muted,marginTop:-9},link:{minHeight:44,justifyContent:'center'},linkText:{fontSize:11,color:'#A7D9FF'},tools:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:10},tool:{padding:12,minHeight:139,gap:10},toolCopy:{flex:1},titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:7},toolTitle:{flex:1,fontSize:15,fontWeight:'800',color:'#fff',lineHeight:20},toolBody:{fontSize:11.5,lineHeight:17,color:glassColors.muted,marginTop:4},sensorState:{fontSize:10,fontWeight:'700',marginTop:5},tracking:{padding:17,flexDirection:'row',alignItems:'center',gap:13},flex:{flex:1},trackingTitle:{fontSize:19,fontWeight:'800',color:'#fff'},trackingState:{fontSize:11,fontWeight:'700'},status:{padding:12},statusText:{fontSize:13,lineHeight:19,color:'#91F0D4'},alertRow:{padding:14,flexDirection:'row',alignItems:'center',gap:12},border:{borderTopWidth:1,borderTopColor:'rgba(155,203,249,.23)'},alertTitle:{fontSize:14,fontWeight:'800',color:'#fff'},white:{fontSize:13,fontWeight:'700',color:'#fff'},overlay:{flex:1,padding:23,justifyContent:'center',backgroundColor:'rgba(2,10,30,.85)'},dialog:{padding:20,gap:13,width:'100%',maxWidth:580,alignSelf:'center'},dialogTitle:{fontSize:23,fontWeight:'800',color:'#fff'},input:{minHeight:50,borderWidth:1,borderColor:glassColors.border,borderRadius:15,padding:12,color:'#fff',backgroundColor:'rgba(4,20,55,.67)'},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},sheetError:{color:'#FFB6CD',fontSize:12,lineHeight:18}});
