import {TextInput} from '../ui/TextInput';
import React,{useCallback,useEffect,useRef,useState}from'react';
import{Alert,Modal,Pressable,Share,StyleSheet,Vibration,View}from'react-native';
import{useFocusEffect,useNavigation}from'@react-navigation/native';
import{MaterialCommunityIcons}from'@expo/vector-icons';
import{LinearGradient}from'expo-linear-gradient';
import * as Location from 'expo-location';
import {getSosLocation,startAutoSosLocation,type SosLocation} from '../services/sosLocation';
import {traceDistance} from '../services/traveledTrace';
import AsyncStorage from '@react-native-async-storage/async-storage';
import{triggerSos,openEmergencyDialer,composeEmergencySms,addTrustedContact,getTrustedContactsWithCache,syncPendingSosEvents}from'../services/liveSafety';
import {getSafetyState} from '../services/travelPlatform';
import{notifyWearDevice}from'../services/nativeSafety';
import{getCurrentSession}from'../services/auth';
import{searchByUsername,type FriendCandidate}from'../services/friendDiscovery';
import{GlassButton,GlassSurface,IconBadge,ScreenQuote,glassColors,useResponsiveLayout}from'../ui/glass';
import{ScreenScaffold,SectionTitle,EmptyGlass}from'../ui/ScreenScaffold';
import{Text}from'../ui/Text';

const LOG_KEY='mymap.sos.log.v1';
type SosLog={id:string;time:number};
type Contact={id:string;name:string;phone_e164:string|null;relationship:string|null;contact_user_id:string|null};
export default function SOSScreen(){
 const nav=useNavigation<any>();const r=useResponsiveLayout();const pending=useRef(false);const progressTimer=useRef<ReturnType<typeof setInterval>|null>(null);const holdTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const holdActive=useRef(false);
 const[contacts,setContacts]=useState<Contact[]>([]),[coords,setCoords]=useState<{latitude:number;longitude:number;accuracy:number|null;timestamp:number}|null>(null),[address,setAddress]=useState('Đang lấy vị trí…'),[locating,setLocating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[status,setStatus]=useState<string|null>(null),[signedIn,setSignedIn]=useState(false),[progress,setProgress]=useState(0),[addModal,setAddModal]=useState(false),[logModal,setLogModal]=useState(false),[logs,setLogs]=useState<SosLog[]>([]);
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[relationship,setRelationship]=useState(''),[username,setUsername]=useState(''),[account,setAccount]=useState<FriendCandidate|null>(null),[candidates,setCandidates]=useState<FriendCandidate[]>([]);
 const clearHold=useCallback(()=>{holdActive.current=false;Vibration.cancel();if(progressTimer.current)clearInterval(progressTimer.current);if(holdTimer.current)clearTimeout(holdTimer.current);progressTimer.current=null;holdTimer.current=null;setProgress(0);},[]);
 async function loadContacts(){const list=await getTrustedContactsWithCache();setContacts(list as Contact[]);}
 useFocusEffect(useCallback(()=>{let active=true;void getCurrentSession().then(async session=>{if(!active)return;setSignedIn(!!session);await loadContacts();void syncPendingSosEvents();}).catch(()=>{if(active)loadContacts();});void AsyncStorage.getItem(LOG_KEY).then(raw=>{if(active)setLogs(raw?JSON.parse(raw):[]);}).catch(()=>{});return()=>{active=false;clearHold();};},[clearHold]));
 async function action(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError(null);setStatus(null);try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{pending.current=false;setBusy(false);}}
 const locationActive=useRef(false),lastGeocode=useRef<{position:SosLocation;time:number}|null>(null),locationSequence=useRef(0);
 const[locationError,setLocationError]=useState<string|null>(null);
 const updateLocation=useCallback((current:SosLocation)=>{
  if(!locationActive.current)return;
  setCoords(current);setLocating(false);setLocationError(null);
  const last=lastGeocode.current;
  if(last&&traceDistance(last.position,current)<40&&Date.now()-last.time<60000)return;
  const sequence=++locationSequence.current;
  lastGeocode.current={position:current,time:Date.now()};
  setAddress(`${current.latitude.toFixed(5)}, ${current.longitude.toFixed(5)}`);
  void Location.reverseGeocodeAsync(current).then(result=>{
   if(!locationActive.current||sequence!==locationSequence.current)return;
   const a=result[0];if(a)setAddress([...new Set([a.name,a.street,a.district,a.city,a.region,a.country].filter(Boolean))].join(', ')||`${current.latitude.toFixed(5)}, ${current.longitude.toFixed(5)}`);
  }).catch(()=>{});
 },[]);
 useFocusEffect(useCallback(()=>{
  locationActive.current=true;lastGeocode.current=null;setCoords(null);setAddress('Đang lấy vị trí…');setLocating(true);setLocationError(null);
  const stop=startAutoSosLocation(updateLocation,message=>{if(locationActive.current){setLocationError(message);setLocating(false);}});
  return()=>{locationActive.current=false;locationSequence.current++;stop();};
 },[updateLocation]));
 async function currentLocation(){setLocating(true);try{const current=await getSosLocation();updateLocation(current);return current;}finally{if(locationActive.current)setLocating(false);}}
 async function sendSos(){const safety=await getSafetyState();let dialError:string|null=null;try{await openEmergencyDialer(safety.emergencyNumber);}catch(e){dialError=e instanceof Error?e.message:String(e);}await action(async()=>{Vibration.vibrate([0,300,150,300]);void notifyWearDevice('sos','Tín hiệu SOS MyMap đã được kích hoạt').catch(()=>{});let location=coords&&Date.now()-coords.timestamp<60000?coords:null;if(!location){try{location=await currentLocation();}catch{location=null;}}const result=await triggerSos({latitude:location?.latitude,longitude:location?.longitude,accuracy_m:location?.accuracy,emergency_type:'general',trigger_method:'sos_screen',note:'Kích hoạt từ màn hình SOS MyMap'});const next=[{id:result.event_id||`sos-${Date.now()}`,time:Date.now()},...logs];setLogs(next);void AsyncStorage.setItem(LOG_KEY,JSON.stringify(next)).catch(()=>{});setStatus(result.event_id?.startsWith('offline')?'Đã lưu tín hiệu SOS vào hàng đợi ngoại tuyến. Hệ thống sẽ tự động đồng bộ khi có mạng lại.':'Hệ thống đã ghi nhận sự kiện SOS thành công.');});if(dialError)setError(dialError);}
 function startHold(){if(busy)return;clearHold();holdActive.current=true;Vibration.vibrate([0,150,100,150,100,250],true);const start=Date.now();progressTimer.current=setInterval(()=>setProgress(Math.min(1,(Date.now()-start)/3000)),70);holdTimer.current=setTimeout(()=>{if(!holdActive.current)return;clearHold();void sendSos();},3000);}
 function dial(){void getSafetyState().then(state=>openEmergencyDialer(state.emergencyNumber)).catch(e=>setError(e.message));}
 function chooseEmergencyNumber(){Alert.alert('Chọn số khẩn cấp tại Việt Nam','Mở số trong ứng dụng gọi điện để bạn xác nhận.',[{text:'113 · Công an',onPress:()=>void openEmergencyDialer('113')},{text:'114 · Cứu hỏa',onPress:()=>void openEmergencyDialer('114')},{text:'115 · Cấp cứu',onPress:()=>void openEmergencyDialer('115')},{text:'Hủy',style:'cancel'}]);}
 async function smsTo(contact:Contact){await action(async()=>{const location=coords&&Date.now()-coords.timestamp<60000?coords:await currentLocation();await composeEmergencySms(contact.phone_e164!,`Tôi cần trợ giúp. Vị trí: https://maps.google.com/?q=${location.latitude},${location.longitude}`);});}
 function sms(){const phones=contacts.filter(c=>c.phone_e164);if(!phones.length){setError('Thêm người thân có số điện thoại để soạn SMS.');setAddModal(true);return;}Alert.alert('Nhắn tin cho người thân','Chọn người nhận. Bạn sẽ xác nhận gửi trong ứng dụng nhắn tin.',[...phones.slice(0,8).map(contact=>({text:contact.name,onPress:()=>void smsTo(contact)})),{text:'Hủy',style:'cancel'}]);}
 function shareLocation(){void action(async()=>{const location=coords&&Date.now()-coords.timestamp<60000?coords:await currentLocation();await Share.share({title:'Vị trí MyMap',message:`Vị trí của tôi: https://maps.google.com/?q=${location.latitude},${location.longitude}`});});}
 function addContact(){void action(async()=>{if(!name.trim())throw new Error('Nhập tên người thân.');if(!account&&!phone.trim())throw new Error('Thêm số điện thoại hoặc chọn tài khoản MyMap.');if(phone.trim()&&!/^\+[1-9][0-9]{6,14}$/.test(phone.trim()))throw new Error('Số điện thoại cần có mã quốc gia, ví dụ +84…');await addTrustedContact({name:name.trim(),phoneE164:phone.trim()||undefined,contactUserId:account?.user_id,relationship:relationship.trim()||undefined});await loadContacts();setAddModal(false);setName('');setPhone('');setRelationship('');setAccount(null);setCandidates([]);setUsername('');setStatus('Đã lưu người thân tin cậy.');});}
 return <ScreenScaffold title="SOS" hideTitle>
  <View style={s.hero}>
   <View style={s.ringOuter}/><View style={s.ringMid}/>
   <Pressable accessibilityRole="button" accessibilityLabel="SOS. Nhấn và giữ 3 giây để gửi" accessibilityHint="Thả tay trước 3 giây để hủy" accessibilityState={{disabled:busy,busy}} disabled={busy} onPressIn={startHold} onPressOut={clearHold} style={({pressed})=>[s.sos,pressed&&{transform:[{scale:.98}]}]}>
    <LinearGradient colors={['#FF9EAE','#ED496C','#C31F46','#EE4062']} locations={[0,.22,.7,1]} style={StyleSheet.absoluteFill}/><View style={s.sosInner}/><MaterialCommunityIcons name="phone" size={55} color="#fff"/><Text allowFontScaling={false} style={s.sosTitle}>{busy?'ĐANG GỬI':'SOS'}</Text><Text style={s.sosHint}>{busy?'Đang chờ hệ thống…':progress>0?`Giữ thêm ${Math.ceil(3*(1-progress))} giây`:'Nhấn và giữ 3 giây\nđể gửi tín hiệu khẩn cấp'}</Text>
   </Pressable>
   <ScreenQuote text="Bạn không bao giờ đơn độc" style={s.quote}/>
  </View>
  <GlassSurface style={s.location}><IconBadge name="map-marker" size={30}/><View style={s.flex}><Text style={s.muted}>Vị trí hiện tại của bạn</Text><Text style={s.address}>{coords?address:locating?'Đang lấy vị trí…':'Chưa xác định vị trí'}</Text>{coords&&<Text style={s.muted}>Cập nhật {new Date(coords.timestamp).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}{coords.accuracy!=null?` · Sai số ±${Math.round(coords.accuracy)} m`:''}</Text>}</View><Pressable accessibilityRole="button" accessibilityLabel="Cập nhật vị trí SOS" disabled={busy||locating} onPress={()=>void action(async()=>{await currentLocation();})} style={s.refresh}><MaterialCommunityIcons name="crosshairs-gps" size={26} color="#AEDDFF"/><Text style={s.refreshText}>{locating?'Đang lấy…':'Thử lại'}</Text></Pressable></GlassSurface>
  {locationError&&<EmptyGlass title="Vị trí SOS" body={locationError} icon="map-marker-alert-outline"/>} {error&&<EmptyGlass title="Chưa thể hoàn tất" body={error} icon="alert-circle-outline"/>} {status&&<GlassSurface tone="mint" style={s.status}><Text style={s.statusText}>{status}</Text></GlassSurface>}
  <GlassSurface tone="rose" style={s.emergency}><IconBadge name="phone" tone="rose" size={28}/><View style={s.flex}><Text style={s.muted}>Số khẩn cấp tại Việt Nam</Text><Text style={s.numbers}>112 · 113 · 114 · 115</Text><Text style={s.numberLabels}>Khẩn cấp chung · Công an · Cứu hỏa · Cấp cứu</Text></View><GlassButton tone="red" onPress={dial}><Text style={s.white}>Gọi ngay</Text></GlassButton></GlassSurface>
  <View style={s.actions}>{[{title:'Gửi vị trí trực tiếp',body:'Chọn người nhận vị trí của bạn',icon:'navigation-variant' as const,tone:'rose' as const,onPress:shareLocation},{title:'Tin nhắn cho người thân',body:'Soạn SMS khẩn cấp kèm tọa độ',icon:'message-text' as const,tone:'cyan' as const,onPress:sms},{title:'Nhật ký sự cố',body:'Sự kiện SOS đã lưu trên thiết bị',icon:'file-document-outline' as const,tone:'violet' as const,onPress:()=>setLogModal(true)}].map(item=><Pressable accessibilityRole="button" key={item.title} disabled={busy||locating} onPress={item.onPress} style={{width:r.width<360||r.fontScale>1.2?'100%':'31.5%'}}><GlassSurface tone={item.tone} style={s.action}><IconBadge name={item.icon} tone={item.tone} size={26}/><Text style={s.actionTitle}>{item.title}</Text><Text style={s.actionBody}>{item.body}</Text></GlassSurface></Pressable>)}</View>
  <GlassButton tone="neutral" onPress={chooseEmergencyNumber}><Text>Chọn 113 / 114 / 115 tại Việt Nam</Text></GlassButton>
  <SectionTitle action={<GlassButton tone="neutral" onPress={()=>setAddModal(true)}><Text style={s.white}>+ Thêm người thân</Text></GlassButton>}>Người thân đáng tin cậy</SectionTitle><Text style={s.muted}>Chọn người liên hệ để chia sẻ vị trí khi cần trợ giúp</Text>
  {contacts.length?<GlassSurface>{contacts.map((c,i)=><View key={c.id} style={[s.contact,i>0&&s.border]}><IconBadge name="account"/><View style={s.flex}><Text style={s.contactName}>{c.name}</Text><Text style={s.muted}>{c.phone_e164||'Tài khoản MyMap'}</Text>{c.relationship&&<Text style={s.relation}>{c.relationship}</Text>}</View><View style={s.contactBadge}><Text style={s.contactBadgeText}>{c.contact_user_id?'Liên kết MyMap':'Liên hệ SMS'}</Text></View></View>)}</GlassSurface>:<EmptyGlass icon="account-group-outline" title="Chưa có người thân tin cậy" body="Thêm số điện thoại hoặc tài khoản MyMap của người bạn tin tưởng." action={!signedIn?<GlassButton onPress={()=>nav.navigate('Login')}><Text style={s.white}>Đăng nhập để lưu người thân</Text></GlassButton>:undefined}/>}
  <Modal visible={addModal} transparent animationType="fade" onRequestClose={()=>{if(!busy)setAddModal(false);}}><View style={s.overlay}><GlassSurface style={s.dialog}><Text style={s.dialogTitle}>Thêm người thân tin cậy</Text><TextInput accessibilityLabel="Tên người thân" value={name} onChangeText={setName} style={s.input} placeholder="Tên người thân" placeholderTextColor={glassColors.faint} editable={!busy}/><TextInput accessibilityLabel="Số điện thoại người thân" value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={s.input} placeholder="Số điện thoại (+84…)" placeholderTextColor={glassColors.faint} editable={!busy}/><TextInput accessibilityLabel="Mối quan hệ" value={relationship} onChangeText={setRelationship} style={s.input} placeholder="Mối quan hệ (tùy chọn)" placeholderTextColor={glassColors.faint} editable={!busy}/><View style={s.searchRow}><TextInput accessibilityLabel="Username người thân trên MyMap" value={username} onChangeText={value=>{setUsername(value);setAccount(null);setCandidates([]);}} style={[s.input,s.flex]} placeholder="Username MyMap (tùy chọn)" placeholderTextColor={glassColors.faint} autoCapitalize="none" editable={!busy}/><GlassButton tone="neutral" disabled={busy||!signedIn||!username.trim()} onPress={()=>void action(async()=>setCandidates(await searchByUsername(username)))}><Text style={s.white}>Tìm</Text></GlassButton></View>{candidates.slice(0,3).map(c=><Pressable key={c.user_id} onPress={()=>{setAccount(c);if(!name)setName(c.display_name||c.username||'');}} style={s.candidate}><Text style={s.white}>{c.display_name||c.username}</Text><MaterialCommunityIcons name={account?.user_id===c.user_id?'check-circle':'circle-outline'} size={22} color={glassColors.cyan}/></Pressable>)}{error&&<Text style={s.sheetError}>{error}</Text>}<View style={s.searchRow}><GlassButton style={s.flex} tone="neutral" disabled={busy} onPress={()=>setAddModal(false)}><Text style={s.white}>Hủy</Text></GlassButton><GlassButton style={s.flex} disabled={busy||!signedIn} onPress={addContact}><Text style={s.white}>{busy?'Đang lưu…':'Lưu người thân'}</Text></GlassButton></View>{!signedIn&&<GlassButton onPress={()=>{setAddModal(false);nav.navigate('Login');}}><Text style={s.white}>Đăng nhập</Text></GlassButton>}</GlassSurface></View></Modal>
  <Modal visible={logModal} transparent animationType="fade" onRequestClose={()=>setLogModal(false)}><View style={s.overlay}><GlassSurface style={s.dialog}><Text style={s.dialogTitle}>Nhật ký sự cố</Text>{logs.length?logs.slice(0,8).map(log=><View key={log.id} style={s.log}><Text style={s.white}>SOS · {new Date(log.time).toLocaleString('vi-VN')}</Text><Text style={s.muted}>Hệ thống đã ghi nhận · {log.id}</Text></View>):<Text style={s.muted}>Chưa có sự kiện SOS được lưu trên thiết bị này.</Text>}<GlassButton onPress={()=>setLogModal(false)}><Text style={s.white}>Đóng</Text></GlassButton></GlassSurface></View></Modal>
 </ScreenScaffold>;
}
const s=StyleSheet.create({hero:{height:255,alignItems:'center',justifyContent:'center',marginVertical:4},ringOuter:{position:'absolute',width:249,height:249,borderRadius:125,borderWidth:1,borderColor:'rgba(255,66,108,.4)',backgroundColor:'rgba(255,39,85,.06)'},ringMid:{position:'absolute',width:225,height:225,borderRadius:113,borderWidth:2,borderColor:'rgba(255,109,146,.7)',backgroundColor:'rgba(255,52,93,.13)',boxShadow:'0 0 22px rgba(255,62,107,.33)'},sos:{width:198,height:198,borderRadius:100,overflow:'hidden',alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:'#FFD8E3',boxShadow:'0 0 24px rgba(255,52,94,.65)'},sosInner:{...StyleSheet.absoluteFill,borderRadius:100,borderWidth:6,borderColor:'rgba(255,209,224,.16)'},sosTitle:{fontSize:42,lineHeight:49,fontWeight:'800',color:'#fff'},sosHint:{fontSize:10.5,lineHeight:15,color:'#FFEAF1',textAlign:'center',marginTop:4},quote:{position:'absolute',right:0,top:9,width:95},location:{padding:14,flexDirection:'row',alignItems:'center',gap:11},flex:{flex:1},muted:{color:glassColors.muted,fontSize:11.5,lineHeight:17},address:{fontSize:14,fontWeight:'800',color:'#fff',lineHeight:20,marginTop:3},refresh:{minWidth:48,minHeight:49,alignItems:'center',justifyContent:'center',gap:4},refreshText:{fontSize:10,color:'#BDDFFF'},emergency:{padding:13,flexDirection:'row',alignItems:'center',gap:10},numbers:{fontSize:20,fontWeight:'800',color:'#fff',lineHeight:27},numberLabels:{fontSize:9.5,color:'#F5C4D8'},white:{color:'#fff',fontSize:12,fontWeight:'700'},actions:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:9},action:{padding:12,gap:8,minHeight:154},actionTitle:{fontSize:13,fontWeight:'800',color:'#fff',lineHeight:18},actionBody:{fontSize:10.5,lineHeight:15,color:glassColors.muted},contact:{padding:13,flexDirection:'row',alignItems:'center',gap:12},border:{borderTopWidth:1,borderTopColor:'rgba(152,208,250,.24)'},contactName:{fontSize:15,fontWeight:'800',color:'#fff'},relation:{fontSize:10,color:'#D1B6FF',marginTop:4},contactBadge:{paddingHorizontal:9,paddingVertical:6,borderRadius:12,borderWidth:1,borderColor:'rgba(174,151,244,.5)'},contactBadgeText:{fontSize:10,color:'#D5C3FF'},status:{padding:13},statusText:{fontSize:13,lineHeight:19,color:'#8FF1D5'},overlay:{flex:1,padding:22,justifyContent:'center',backgroundColor:'rgba(2,9,29,.86)'},dialog:{padding:19,gap:12,width:'100%',maxWidth:580,alignSelf:'center'},dialogTitle:{fontSize:22,fontWeight:'800',color:'#fff'},input:{minHeight:48,borderRadius:14,borderWidth:1,borderColor:glassColors.border,padding:12,color:'#fff',backgroundColor:'rgba(4,20,53,.66)'},searchRow:{flexDirection:'row',gap:8},candidate:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:9,borderBottomWidth:1,borderBottomColor:glassColors.border},sheetError:{fontSize:12,color:'#FFB9CB',lineHeight:18},log:{gap:4,paddingVertical:9}});
