export type LegalDocument = 'terms' | 'privacy' | 'about';
export const LEGAL_VERSION = '2026-10-05';
export const LEGAL_SUMMARY = 'Hành trình lưu trên máy; chia sẻ khi bạn bật.\nCó quảng cáo và dịch vụ bên thứ ba.\nĐọc Điều khoản & Quyền riêng tư trước khi tiếp tục.';
export const LEGAL_DOCUMENTS: Record<LegalDocument, {title: string; sections: {title: string; body: string}[]}> = {
 terms: {title: 'Điều khoản sử dụng', sections: [
  {title: '1. Phạm vi và chấp thuận', body: 'Cập nhật ngày 05/10/2026 cho MyMap 1.0.0. Khi tạo tài khoản hoặc tiếp tục sử dụng, bạn đồng ý với các điều khoản này và chính sách quyền riêng tư. Nếu không đồng ý, bạn có thể dừng sử dụng và xóa dữ liệu. Những thay đổi quan trọng sẽ được thông báo trong ứng dụng trước khi có hiệu lực.'},
  {title: '2. Tài khoản và đối tượng sử dụng', body: 'Bạn cần đủ độ tuổi sử dụng theo luật tại nơi cư trú và điều khoản của nhà cung cấp đăng nhập/âm nhạc. Người chưa đủ tuổi phải có sự đồng ý và giám sát của người giám hộ khi luật yêu cầu. Cung cấp thông tin hợp lệ, bảo vệ thông tin đăng nhập và chỉ liên kết tài khoản của chính mình. Không sử dụng MyMap để theo dõi người khác trái ý muốn.'},
  {title: '3. Hành trình, bản đồ và dẫn đường', body: 'GPS, thời tiết, tuyến đường, thời gian đến và giới hạn tốc độ có thể thiếu, trễ hoặc sai. Luôn tuân theo biển báo, luật địa phương và hướng dẫn của cơ quan chức năng. Không thao tác điện thoại khi đang điều khiển phương tiện. Lựa chọn tránh phà, cao tốc hoặc đường thô sơ phụ thuộc dữ liệu và khả năng của máy chủ định tuyến; ứng dụng thông báo khi không tìm được tuyến đáp ứng.'},
  {title: '4. SOS và phát hiện sự cố', body: 'MyMap hỗ trợ liên hệ khẩn cấp, không phải thiết bị cứu hộ hay chẩn đoán y tế. Cảm biến có thể báo nhầm hoặc bỏ sót; độ cao rơi không thể xác định đáng tin cậy nếu thiếu khí áp kế. Sau sự cố nghi ngờ trên 20 m và 5 phút không ghi nhận tương tác, ứng dụng kích hoạt cảnh báo và yêu cầu hệ thống mở trình gọi. Android yêu cầu người dùng xác nhận gọi số khẩn cấp; khi chạy nền, hệ thống có thể chỉ cho phép thông báo. Không có sóng, không có trình gọi hoặc bị hệ điều hành dừng thì không thể bảo đảm liên hệ. Sự kiện SOS được lưu không đồng nghĩa cứu hộ đã nhận hay đã được điều động.'},
  {title: '5. Nội dung và cộng đồng', body: 'Bạn giữ quyền đối với ảnh và nội dung của mình, đồng thời cho phép xử lý nội dung trong phạm vi các tính năng bạn sử dụng. Chỉ chia sẻ nội dung có quyền sử dụng. Không đăng nội dung vi phạm pháp luật, lừa đảo, xâm phạm quyền riêng tư, quấy rối hoặc phá hoại dịch vụ. Có thể chặn, báo cáo hoặc hủy kết nối bạn bè.'},
  {title: '6. Quảng cáo, âm nhạc và dịch vụ bên thứ ba', body: 'Ứng dụng có quảng cáo native được đánh dấu và đặt trong nội dung cuộn. Google AdMob và các dịch vụ bản đồ, thời tiết, đăng nhập, dữ liệu, âm nhạc áp dụng điều khoản riêng. Spotube là ứng dụng đồng hành được cài riêng; tìm nhạc và đăng nhập nhà cung cấp diễn ra trong Spotube, không trong MyMap. MyMap điều khiển phát nhạc sau khi bạn chấp thuận kết nối trong Spotube. Bạn cũng có thể nghe radio hoặc nhập tệp âm thanh mà mình có quyền sử dụng. Các gói trả phí, quyền phát và giới hạn khu vực do nhà cung cấp quyết định. MyMap không cấp quyền sở hữu, vượt giới hạn truy cập hoặc tải lại nhạc được bảo hộ.'},
  {title: '7. Khả dụng và trách nhiệm', body: 'Dịch vụ được cung cấp theo khả năng hiện có. Không bảo đảm GPS liên tục, độ chính xác hoặc dịch vụ bên thứ ba luôn sẵn sàng. Bạn nên xuất dữ liệu quan trọng. Trong phạm vi pháp luật cho phép, nhà cung cấp không chịu trách nhiệm cho thiệt hại gián tiếp do dữ liệu sai hoặc gián đoạn. Điều này không loại trừ quyền người tiêu dùng hay trách nhiệm không thể loại trừ theo luật áp dụng.'},
  {title: '8. Chấm dứt, yêu cầu và tranh chấp', body: 'Bạn có thể ngừng sử dụng bất kỳ lúc nào, xuất dữ liệu, xóa dữ liệu cục bộ và yêu cầu xóa tài khoản trong phần Cá nhân/Cài đặt. Dữ liệu đã gửi cho người khác có thể còn trên thiết bị của họ. Gửi yêu cầu hỗ trợ qua thông tin nhà phát triển trên trang cửa hàng đã cài MyMap. Tranh chấp được giải quyết theo pháp luật bắt buộc tại nơi người dùng cư trú; các quyền khiếu nại hợp pháp được bảo lưu.'},
 ]},
 privacy: {title: 'Chính sách quyền riêng tư', sections: [
  {title: 'Bản đồ mở rộng và nguồn dữ liệu', body: 'Các lớp giao thông, địa điểm, ảnh đường, biển báo, hạ tầng, đường cụt, lịch sử ảnh, phân tích ảnh, trợ lý biển báo và giá nhiên liệu mặc định tắt. Khi bật, TomTom, Mapillary hoặc máy chủ OpenStreetMap nhận vùng bản đồ đang xem, tọa độ truy vấn hoặc định danh ảnh/vật thể cần tải, cùng địa chỉ IP của kết nối. VietFuel chỉ nhận yêu cầu bảng giá tổng hợp hoặc hãng nhiên liệu, không nhận GPS hay tệp ảnh cá nhân từ tính năng này. Tắt lớp sẽ dừng yêu cầu mới và hủy các yêu cầu dữ liệu đang chạy của lớp; dữ liệu đã gửi trước đó không thể thu hồi. Ảnh Mapillary do cộng đồng cung cấp, có ngày chụp và ghi nguồn. Nhận diện biển báo không xác nhận hướng hiệu lực; giá nhiên liệu theo hãng/vùng không xác nhận giá riêng tại cửa hàng.'},
  {title: 'Khoảnh khắc, camera và widget', body: 'Camera MyMap chụp ảnh hoặc quay video khi bạn chủ động mở màn hình camera. Quyền micro chỉ phục vụ video có tiếng và lời nhắn giọng nói; không ghi âm ở nền. Khoảnh khắc được lưu trên máy trước. Gắn vị trí khi lưu và gửi vị trí cho người nhận là hai lựa chọn riêng, mặc định tắt. Khi chọn đồng bộ hoặc gửi, ảnh/video, ghi chú và người nhận được lưu trong kho riêng trên Supabase; chỉ tài khoản của bạn và người nhận hiện còn quyền được đọc. Thành viên nhóm có thể xem những nội dung được chia sẻ cho họ; rời nhóm hoặc hủy kết bạn chặn những lần tải mới. Người nhận vẫn có thể giữ bản tải/chụp màn hình trước đó. Liên kết tải riêng tồn tại ngắn hạn; widget lưu ảnh xem trước trong bộ nhớ riêng của ứng dụng, có thể xuất hiện trên màn hình chính. Đăng xuất xóa ảnh widget, nhưng bản lưu cá nhân vẫn ở thiết bị và được tách theo tài khoản. Widget cập nhật khi mở MyMap và định kỳ khi hệ điều hành cho phép. Bạn có thể xóa khoảnh khắc tại màn hình chi tiết. Video tổng kết được xuất trên thiết bị; chỉ được gửi ra ngoài khi bạn dùng chức năng chia sẻ.'},
  {title: '1. Ai xử lý dữ liệu', body: 'Chính sách cập nhật ngày 05/10/2026. Nhà phát triển MyMap được ghi trên trang cửa hàng phát hành là bên chịu trách nhiệm cho dữ liệu do MyMap thu thập. Dùng kênh liên hệ nhà phát triển trên trang cửa hàng để thực hiện quyền về dữ liệu. Nhà cung cấp dịch vụ bên thứ ba xử lý dữ liệu theo chính sách riêng được liên kết bên dưới.'},
  {title: '2. Dữ liệu và mục đích', body: 'Khi cấp quyền và bật ghi hành trình, MyMap lưu tọa độ, thời gian, độ chính xác, tốc độ và độ cao GPS trên thiết bị. Ảnh, ghi chú, hồ sơ và địa điểm đã lưu phục vụ kỷ niệm và lịch sử. Firebase xử lý email, số điện thoại hoặc định danh đăng nhập; Supabase xử lý thông tin hồ sơ, quan hệ bạn bè, vị trí chia sẻ, tin nhắn và sự kiện an toàn khi sử dụng các tính năng trực tuyến. Cảm biến chuyển động/khí áp phục vụ nhận diện sự cố. MyMap chỉ quan sát tương tác trong ứng dụng và sự kiện mở khóa màn hình, không đọc nội dung ứng dụng khác.'},
  {title: '3. Quyền và kiểm soát', body: 'Vị trí nền chỉ dùng khi bạn bật theo dõi nền hoặc tính năng cần thiết và cấp quyền. Máy ảnh/thư viện dùng khi chụp/chọn ảnh; thông báo để cảnh báo; cảm biến để nhận diện sự cố. Bạn có thể từ chối hoặc thu hồi quyền trong cài đặt thiết bị, dừng ghi, bật chế độ ẩn hoặc vùng riêng tư. Một số tính năng sẽ không hoạt động khi quyền bị từ chối. Không yêu cầu mật khẩu nhà cung cấp âm nhạc trong MyMap.'},
  {title: '4. Chia sẻ và các bên nhận', body: 'Vị trí bạn bật chia sẻ có thể được gửi tới bạn bè hoặc người thân được chọn. Khi mở bản đồ/tra cứu/định tuyến/thời tiết, máy chủ liên quan nhận IP và vùng hoặc tọa độ cần cho truy vấn. AdMob/APS có thể nhận định danh quảng cáo, thông tin thiết bị, IP và tương tác quảng cáo. MyMap không bán lịch sử GPS cho nhà quảng cáo. Firebase, Supabase, OpenFreeMap, OpenStreetMap, nhà cung cấp định tuyến/thời tiết và nhà cung cấp âm nhạc có thể xử lý dữ liệu ở nước khác; các điều khoản và cơ chế chuyển dữ liệu của họ áp dụng.'},
  {title: '5. Quảng cáo và lựa chọn đồng ý', body: 'Quảng cáo luôn được nhận diện rõ và không phủ lên bản đồ hay thao tác khẩn cấp. Lựa chọn đồng ý quảng cáo theo khu vực được xử lý qua cơ chế quyền riêng tư của Google khi đã cấu hình trong bảng điều khiển AdMob. Bạn có thể điều chỉnh/xóa ID quảng cáo ở cài đặt hệ điều hành. Việc từ chối cá nhân hóa không loại bỏ mọi quảng cáo. Không dùng nội dung nhạc hoặc lịch sử nghe để nhắm quảng cáo.'},
  {title: '6. Lưu giữ và bảo mật', body: 'Hành trình và ảnh cục bộ được lưu tới khi bạn xóa hoặc chính sách lưu giữ trong Cài đặt tự xóa. Gỡ ứng dụng hoặc xóa dữ liệu thiết bị có thể mất dữ liệu cục bộ. Dữ liệu tài khoản trên máy chủ được lưu để duy trì tài khoản và tính năng đã chọn, đến khi có yêu cầu xóa, trừ thời hạn bắt buộc theo luật. Truyền ra mạng dùng HTTPS; kết nối điều khiển Spotube dùng WebSocket cục bộ trên cùng thiết bị. Thông tin tài khoản và quyền truy cập dùng các cơ chế của nhà cung cấp. Không hệ thống nào bảo đảm an toàn tuyệt đối.'},
  {title: '7. Quyền của bạn', body: 'Tùy luật nơi bạn cư trú, bạn có quyền truy cập, sửa, xuất, xóa, hạn chế xử lý, phản đối và rút lại đồng ý. Xuất JSON/GPX/GeoJSON/CSV trong Cài đặt. Xóa dữ liệu thiết bị ở Cài đặt; quản lý tài khoản ở Cá nhân. Rút quyền vị trí hoặc hủy liên kết âm nhạc bất cứ lúc nào. Yêu cầu bổ sung qua trang nhà phát triển trên cửa hàng; bạn cũng có quyền khiếu nại với cơ quan bảo vệ dữ liệu có thẩm quyền.'},
  {title: '8. Trẻ em và cập nhật', body: 'Không chủ động thu thập dữ liệu của trẻ chưa đủ tuổi theo luật áp dụng. Nếu phát hiện dữ liệu thu thập không có sự đồng ý cần thiết, nhà phát triển sẽ xử lý yêu cầu xóa. Khi chính sách thay đổi quan trọng, ứng dụng sẽ thông báo và cập nhật ngày hiệu lực. Bản đầy đủ luôn có trong Cài đặt.'},
  {title: '9. Nhạc trên thiết bị và chia sẻ đang nghe', body: 'Khi bạn chọn tệp âm thanh, MyMap lưu bản sao trong vùng dữ liệu riêng của ứng dụng để nghe ngoại tuyến. Tệp gốc vẫn giữ nguyên; xóa nhạc đã nhập chỉ xóa bản sao trong MyMap. Hàng đợi, mục yêu thích, danh sách nghe gần đây và cài đặt phát được lưu trên thiết bị. MyMap không tự tải tệp nhạc của bạn lên máy chủ. Kết nối Spotube chỉ dùng địa chỉ cục bộ trên cùng thiết bị và cần bạn chấp thuận; MyMap nhận tên bài hát, nghệ sĩ, ảnh bìa, hàng đợi và trạng thái phát, không nhận mật khẩu hoặc mã đăng nhập của nhà cung cấp. Tìm radio, phát luồng trực tuyến và tải ảnh bìa gửi IP cùng truy vấn cần thiết đến dịch vụ liên quan. Chia sẻ bài đang nghe mặc định tắt. Khi bạn bật lựa chọn này và chia sẻ vị trí với bạn bè, tên bài hát và nghệ sĩ có thể được gửi kèm trạng thái của bạn. Bạn có thể tắt chia sẻ, ngắt kết nối Spotube hoặc xóa nhạc đã nhập bất cứ lúc nào.'},
 ]},
 about: {title: 'Giới thiệu MyMap', sections: [
  {title: 'Một chút hôm nay, dành cho người thân quen', body: 'Chụp ảnh và quay video ngắn bằng camera riêng của MyMap, xem lại trước khi lưu. Giữ riêng cho mình, gửi cho bạn bè đã kết nối hoặc góp vào nhật ký nhóm. Thả cảm xúc, bình luận và ghi lời nhắn giọng nói cho khoảnh khắc đã chia sẻ. Chọn ảnh mới của bạn bè, một nhóm, ảnh cá nhân gần nhất hoặc ngày này năm xưa cho widget màn hình chính trên launcher tương thích. Chọn ảnh/video đã lưu để xuất video tổng kết có ngày giờ theo thứ tự thời gian. Ảnh cá nhân có gắn vị trí vẫn có thể được ghim lên bản đồ; chia sẻ ảnh không tự bật chia sẻ vị trí.'},
  {title: 'Mỗi hành trình đều đáng nhớ', body: 'MyMap kết hợp bản đồ bạn bè, nhật ký di chuyển và kỷ niệm cá nhân. Xem ai đang ở gần, lưu một bức ảnh đúng nơi chụp và nhìn lại những con đường bạn đã đi. Bạn có thể dùng bản đồ và ghi hành trình cục bộ trước khi đăng nhập.'},
  {title: 'Hành trình và kỷ niệm', body: 'GPS được lưu trên thiết bị bằng SQLite, kể cả khi mất mạng trong chế độ ghi đã cấp quyền. Hành trình hiển thị theo ngày, quãng đường và điểm dừng; ảnh, ghi chú, dấu chân và vùng khám phá giúp bạn nhìn lại chuyến đi. Có thể xuất dữ liệu để lưu trữ hoặc dùng với công cụ bản đồ khác.'},
  {title: 'Kết nối theo cách của bạn', body: 'Tìm bạn bằng username, điện thoại, mã QR hoặc xung quanh. Chia sẻ vị trí, nhắn tin ghim trên bản đồ, hành trình trực tiếp, thông báo khi đến nơi, nhóm cùng đi và các tiện ích khám phá. Dùng chế độ ẩn/vùng riêng tư để kiểm soát việc chia sẻ.'},
  {title: 'Dẫn đường và an toàn', body: 'Chọn phương tiện và ưu tiên tránh phà, cao tốc, đường thô sơ. Xem khoảng cách đến điểm rẽ, tốc độ GPS, dữ liệu giới hạn tốc độ và thời tiết ở 5 km tiếp theo. Android Auto có màn hình riêng cho xe tương thích. SOS mở sẵn trình gọi điện; phát hiện va chạm/rơi chỉ là hỗ trợ và có thể thiếu hoặc báo nhầm.'},
  {title: 'Âm nhạc theo hành trình', body: 'Mở Spotube đã cài trên điện thoại để tìm nhạc và liên kết tài khoản nhà cung cấp trong ứng dụng đó. Sau khi bạn chấp thuận kết nối, MyMap có thể hiện bài đang nghe và điều khiển phát, tạm dừng, đổi bài, tua, trộn và lặp. Radio và nhạc nhập từ thiết bị dùng chung trình phát trong MyMap, với hàng đợi, yêu thích, nghe gần đây, âm lượng và hẹn giờ tắt. Nhạc nhập có thể nghe khi mất mạng; radio cần Internet. Có điều khiển phát/tạm dừng ở màn hình khóa cho nhạc MyMap. Ứng dụng không tự phát khi khởi động; chia sẻ bài đang nghe mặc định tắt. Hẹn giờ dùng thời gian tuyệt đối nhưng có thể trễ nếu hệ điều hành đình chỉ ứng dụng.'},
  {title: 'Quảng cáo và lựa chọn của bạn', body: 'Quảng cáo native nằm trong nội dung cuộn, không chắn bản đồ, dẫn đường hoặc SOS. Âm nhạc tiếp tục dùng trình phát bạn đã chọn; khi chuyển giữa MyMap và Spotube, MyMap giải phóng hoặc chuyển quyền phát để tránh hai nguồn nhạc chồng nhau.'},
  {title: 'Nền tảng và giấy phép', body: 'MyMap 1.0.0 dùng Expo/React Native, MapLibre, OpenFreeMap, SQLite, Firebase và Supabase. OpenFreeMap: MIT; OpenMapTiles: BSD/CC BY; dữ liệu OpenStreetMap: ODbL. Phông chữ Nunito Sans/Dancing Script: SIL OFL. Cần mạng cho tải bản đồ và dịch vụ trực tuyến; bản đồ ngoại tuyến cần nguồn được cấp phép. Fire OS có bản riêng dùng định vị hệ thống; thiết bị không có GPS/điện thoại chỉ sử dụng được những tính năng phần cứng hỗ trợ.'},
 ]},
};
