import type{TripPlan,Vehicle,Expense,RoadReport,TravelJournal,MeetupEvent,PlaceReview,PlaceCollection,CatalogKind}from'../types/catalog';
export function validCoordinate(latitude:number,longitude:number){return Number.isFinite(latitude)&&Number.isFinite(longitude)&&Math.abs(latitude)<=90&&Math.abs(longitude)<=180;}
export function validateTrip(plan:TripPlan){
 if(!plan||typeof plan.name!=='string'||!plan.name.trim()||plan.name.length>100)throw new Error('Tên chuyến đi cần 1–100 ký tự.');
 if(!['car','motorbike','foot','bike'].includes(plan.mode)||!Number.isFinite(plan.startsAt)||plan.startsAt<0||plan.startsAt>4102444800000)throw new Error('Phương tiện hoặc ngày đi không hợp lệ.');
 if(!Array.isArray(plan.stops)||plan.stops.length<2||plan.stops.length>20)throw new Error('Chọn từ 2 đến 20 điểm dừng.');
 if(plan.stops.some(p=>!p||typeof p.id!=='string'||!p.id.trim()||p.id.length>100||typeof p.name!=='string'||!p.name.trim()||p.name.length>300||!validCoordinate(p.latitude,p.longitude)||!Number.isFinite(p.stayMinutes)||p.stayMinutes<0||p.stayMinutes>1440)||new Set(plan.stops.map(p=>p.id)).size!==plan.stops.length)throw new Error('Điểm dừng không hợp lệ.');
}
export function validateCollection(value:PlaceCollection){if(!value||typeof value.name!=='string'||!value.name.trim()||value.name.length>100||!Array.isArray(value.places)||value.places.length>500)throw new Error('Danh sách cần tên hợp lệ và tối đa 500 địa điểm.');if(value.places.some(p=>!p||typeof p.id!=='string'||!p.id.trim()||p.id.length>100||typeof p.name!=='string'||!p.name.trim()||p.name.length>300||typeof p.note!=='string'||p.note.length>2000||!validCoordinate(p.latitude,p.longitude))||new Set(value.places.map(p=>p.id)).size!==value.places.length)throw new Error('Địa điểm trong danh sách không hợp lệ.');}
export function validateCatalogPayload(kind:CatalogKind,value:unknown){
 if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Dữ liệu không hợp lệ.');
 const data=value as any,finite=(n:unknown)=>typeof n==='number'&&Number.isFinite(n),date=(n:unknown)=>finite(n)&&Math.abs(n as number)<=8640000000000000;
 if(kind==='trip')validateTrip(data);
 else if(kind==='collection')validateCollection(data);
 else if(kind==='vehicle')validateVehicle(data);
 else if(kind==='expense'){validateExpense(data);if(!date(data.at)||data.odometerKm!=null&&(!finite(data.odometerKm)||data.odometerKm<0))throw new Error('Mốc chi phí không hợp lệ.');}
 else if(kind==='journal'){validateJournal(data);if(!date(data.at))throw new Error('Mốc nhật ký không hợp lệ.');}
 else if(kind==='event'){validateEvent(data);if(!date(data.startsAt)||!date(data.endsAt))throw new Error('Mốc sự kiện không hợp lệ.');}
 else if(kind==='review'){validateReview(data);if(!date(data.visitedAt))throw new Error('Mốc đánh giá không hợp lệ.');}
 else if(kind==='road_report')validateRoadReport(data);
 else if(kind==='parking'){if(typeof data.vehicleId!=='string'||!data.vehicleId||!validCoordinate(data.latitude,data.longitude)||!date(data.at)||typeof data.note!=='string'||data.reminderAt!=null&&!date(data.reminderAt)||data.photoUri!=null&&typeof data.photoUri!=='string')throw new Error('Thông tin đỗ xe không hợp lệ.');}
 else if(kind==='maintenance'){if(typeof data.vehicleId!=='string'||!data.vehicleId||typeof data.name!=='string'||!data.name.trim()||data.name.length>100||typeof data.done!=='boolean'||data.dueAt!=null&&!date(data.dueAt)||data.dueKm!=null&&(!finite(data.dueKm)||data.dueKm<0)||data.dueAt==null&&data.dueKm==null)throw new Error('Thông tin bảo dưỡng không hợp lệ.');}
 else if(kind==='emergency_card'){if(typeof data.ciphertext!=='string'||!data.ciphertext)throw new Error('Thẻ mã hóa không hợp lệ.');}
 else throw new Error('Loại dữ liệu chưa được hỗ trợ.');
}
export function validateVehicle(vehicle:Vehicle){if(!vehicle||typeof vehicle.name!=='string'||!vehicle.name.trim()||vehicle.name.length>100||!['petrol','diesel','electric'].includes(vehicle.fuel)||[vehicle.odometerKm,vehicle.unitPrice,vehicle.consumptionPer100Km].some(n=>!Number.isFinite(n)||n<0))throw new Error('Thông tin xe không hợp lệ.');if(vehicle.fuel==='electric'&&(vehicle.batteryKwh!=null&&(!Number.isFinite(vehicle.batteryKwh)||vehicle.batteryKwh<=0)||vehicle.reservePercent!=null&&(!Number.isFinite(vehicle.reservePercent)||vehicle.reservePercent<0||vehicle.reservePercent>100)))throw new Error('Dung lượng pin hoặc mức dự phòng không hợp lệ.');}
export function tripCost(vehicle:Vehicle,distanceMeters:number){if(!Number.isFinite(distanceMeters)||distanceMeters<0)throw new Error('Quãng đường không hợp lệ.');validateVehicle(vehicle);const units=distanceMeters/100000*vehicle.consumptionPer100Km;return{units,amount:units*vehicle.unitPrice,unit:vehicle.fuel==='electric'?'kWh':'lít'};}
export function expenseTotals(expenses:Expense[]){return{total:expenses.reduce((sum,e)=>sum+e.amount,0),quantity:expenses.reduce((sum,e)=>sum+(e.quantity||0),0),splits:expenses.map(e=>({amount:e.amount,perPerson:e.amount/Math.max(1,e.splitPeople)}))};}
export function validateRoadReport(report:RoadReport){if(!report||typeof report.note!=='string'||!['hazard','pothole','flood','accident','closure','broken_light'].includes(report.category)||!validCoordinate(report.latitude,report.longitude)||report.note.length>500||!Number.isFinite(report.createdAt))throw new Error('Báo cáo đường không hợp lệ.');}
export function remainingBatteryRange(vehicle:Vehicle,currentPercent:number){if(vehicle.fuel!=='electric'||!vehicle.batteryKwh||vehicle.consumptionPer100Km<=0||!Number.isFinite(currentPercent)||currentPercent<0||currentPercent>100)return null;return Math.max(0,currentPercent-(vehicle.reservePercent??15))/100*vehicle.batteryKwh/vehicle.consumptionPer100Km*100;}
export function validateExpense(expense:Expense){if(!expense||typeof expense.note!=='string'||!['fuel','charging','toll','parking','other'].includes(expense.category)||!Number.isFinite(expense.amount)||expense.amount<0||!Number.isInteger(expense.splitPeople)||expense.splitPeople<1||expense.splitPeople>100||!Number.isFinite(expense.at)||expense.note.length>2000||expense.quantity!=null&&(!Number.isFinite(expense.quantity)||expense.quantity<0))throw new Error('Chi phí không hợp lệ.');}
function content(value:{name:string;note:string}){if(!value||typeof value.name!=='string'||!value.name.trim()||value.name.length>100||typeof value.note!=='string'||!value.note.trim()||value.note.length>4000)throw new Error('Tên cần 1–100 ký tự; nội dung cần 1–4.000 ký tự.');}
function place(value:{name:string;latitude:number;longitude:number}|null){if(!value||typeof value.name!=='string'||!value.name.trim()||!validCoordinate(value.latitude,value.longitude))throw new Error('Chọn địa điểm hợp lệ.');}
export function validateJournal(value:TravelJournal){content(value);if(!Number.isFinite(value.at))throw new Error('Ngày ghi nhật ký không hợp lệ.');if(value.place)place(value.place);}
export function validateEvent(value:MeetupEvent){content(value);place(value.place);if(!Number.isFinite(value.startsAt)||!Number.isFinite(value.endsAt)||value.endsAt<=value.startsAt||value.endsAt-value.startsAt>7*86400000)throw new Error('Sự kiện cần giờ kết thúc sau giờ bắt đầu, tối đa 7 ngày.');}
export function validateReview(value:PlaceReview){content(value);place(value.place);if(![1,2,3,4,5].includes(value.rating)||!Number.isFinite(value.visitedAt))throw new Error('Đánh giá không hợp lệ.');}
export function localDateTime(value:number){const d=new Date(value),pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;}
export function parseLocalDateTime(value:string){const parts=/^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})$/.exec(value.trim());if(!parts)throw new Error('Nhập ngày giờ theo YYYY-MM-DD HH:mm.');const[y,m,d,h,n]=parts.slice(1).map(Number)as[number,number,number,number,number];const date=new Date(y,m-1,d,h,n);if(date.getFullYear()!==y||date.getMonth()!==m-1||date.getDate()!==d||date.getHours()!==h||date.getMinutes()!==n)throw new Error('Ngày giờ không tồn tại.');return date.getTime();}
